In [1]:
import anndata as ad
import pandas as pd
import numpy as np
from scipy.io import mmread, mmwrite
from scipy.sparse import csr_matrix
import muon
import scarches as sca
from multigrate.data import organize_multiome_anndatas
import scanpy as sc
import scib_metrics
from typing import Optional
import os, sys
from scipy.sparse import csr_matrix, coo_matrix
import scipy
from scipy import sparse
import importlib
import matplotlib.pyplot as plt
import seaborn as sns
import scib
import scib_metrics
from scib_metrics.benchmark import Benchmarker
from typing import Any, Callable, Optional, Union
from plottable import ColumnDefinition, Table
from plottable.cmap import normed_cmap
from plottable.plots import bar

import warnings
warnings.filterwarnings("ignore")

/home/zhouweige/anaconda3/envs/scib/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
WARNING:root:In order to use the mouse gastrulation seqFISH datsets, please install squidpy (see https://github.com/scverse/squidpy).
WARNING:root:In order to use sagenet models, please install pytorch geometric (see https://pytorch-geometric.readthedocs.io) and
 captum (see https://github.com/pytorch/captum).
WARNING:root:mvTCR is not installed. To use mvTCR models, please install it first using "pip install mvtcr"
WARNING:root:multigrate is not installed. To use multigrate models, please install it first using "pip install multigrate".

In [2]:
def read_RNA_ATAC(RNA_path,ATAC_path):
    # gene expression
    cell_names = pd.read_csv(RNA_path+'/barcodes.tsv', sep = '\t', header=None, index_col=None)
    cell_names.columns =  ['cell_ids'] 
    cell_names['cell_ids'] = cell_names['cell_ids'].str.replace('.','-')
    X = csr_matrix(mmread(RNA_path+'/matrix.mtx').T)
    gene_names = pd.read_csv(RNA_path+'/features.tsv', sep = '\t',  header=None, index_col=None) 
    gene_names.columns =  ['gene_ids'] 
    adata_RNA = ad.AnnData(X, obs=pd.DataFrame(index=cell_names.cell_ids), var=pd.DataFrame(index = gene_names.gene_ids))
    adata_RNA.var_names_make_unique()
    # peak information
    cell_names = pd.read_csv(ATAC_path + '/barcodes.tsv', sep = '\t', header=None, index_col=None)
    cell_names.columns =  ['cell_ids'] 
    cell_names['cell_ids'] = cell_names['cell_ids'].str.replace('.','-')
    X = csr_matrix(mmread(ATAC_path + '/matrix.mtx').T)
    peak_name = pd.read_csv(ATAC_path + '/features.tsv', sep = '\t',header=None,index_col=None)
    peak_name.columns = ['peak_ids']
    adata_ATAC  = ad.AnnData(X, obs=pd.DataFrame(index=cell_names.cell_ids), var=pd.DataFrame(index = peak_name.peak_ids))
    return adata_RNA, adata_ATAC

In [3]:
import os
import numpy as np
import scanpy as sc
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

def pca(adata, use_reps=None, n_comps=10):

    """Dimension reduction with PCA algorithm"""

    from sklearn.decomposition import PCA
    from scipy.sparse.csc import csc_matrix
    from scipy.sparse.csr import csr_matrix
    pca = PCA(n_components=n_comps)
    if use_reps is not None:
       feat_pca = pca.fit_transform(adata.obsm[use_reps])
    else:
       if isinstance(adata.X, csc_matrix) or isinstance(adata.X, csr_matrix):
          feat_pca = pca.fit_transform(adata.X.toarray())
       else:
          feat_pca = pca.fit_transform(adata.X)

    return feat_pca

def supervised_clustering(adata, n_clusters=7, key='Garfield', add_key='Garfield_cluster', cluster_method='leiden',
               start=0.5, end=2.0, increment=0.05, use_pca=False, n_comps=20):
    if use_pca:
       adata.obsm[key + '_pca'] = pca(adata, use_reps=key, n_comps=n_comps)

    method_cluster = add_key
    method = key
    
    if cluster_method == 'leiden':
       if use_pca:
          res = search_res(adata, n_clusters, use_rep=key + '_pca', cluster_method=cluster_method, 
                           start=start, end=end, increment=increment)
       else:
          res = search_res(adata, n_clusters, use_rep=method, cluster_method=cluster_method, 
                           start=start, end=end, increment=increment)
       sc.tl.leiden(adata, random_state=0, key_added=method_cluster, resolution=res, neighbors_key=method)
    elif cluster_method == 'louvain':
       if use_pca:
          res = search_res(adata, n_clusters, use_rep=key + '_pca', cluster_method=cluster_method, 
                           start=start, end=end, increment=increment)
       else:
          res = search_res(adata, n_clusters, use_rep=method, cluster_method=cluster_method, 
                           start=start, end=end, increment=increment)
       sc.tl.louvain(adata, random_state=0, key_added=method_cluster, resolution=res, neighbors_key=method)

def search_res(adata, n_clusters, use_rep='Garfield', cluster_method='leiden', start=0.5, end=2.0,
               increment=0.05, expansion_factor=1.75, max_iter=50):
    '''\
    Searching corresponding resolution according to given cluster number

    Parameters
    ----------
    adata : anndata
        AnnData object of spatial data.
    n_clusters : int
        Target number of clusters.
    method : string
        Tool for clustering. Supported tools include 'leiden' and 'louvain'. The default is 'leiden'.
    use_rep : string
        The indicated representation for clustering.
    start : float
        The start value for searching.
    end : float
        The end value for searching.
    increment : float
        The step size to increase.
    expansion_factor : float
        Factor to expand the search range if no resolution is found in the initial range.
    max_iter : int
        Maximum number of iterations to prevent infinite loops.

    Returns
    -------
    res : float
        Resolution.

    '''
    print('Searching resolution...')
    label = 0
    method = use_rep
    method_cluster = method + '_cluster'
    
    current_start, current_end = start, end
    best_res = None
    best_diff = float('inf')  # Track the best resolution so far
    best_count = 0
    iteration = 0  # Track number of iterations
    
    # 构图
    sc.pp.neighbors(adata, use_rep=use_rep, key_added=method)

    while label == 0 and iteration < max_iter:
        iteration += 1
        for res in sorted(list(np.arange(current_start, current_end, increment)), reverse=True):
            if cluster_method == 'leiden':
                sc.tl.leiden(adata, random_state=0, key_added=method_cluster,
                             resolution=res, neighbors_key=method)
                count_unique = adata.obs[method_cluster].nunique()
            elif cluster_method == 'louvain':
                sc.tl.louvain(adata,  random_state=0, key_added=method_cluster, 
                             resolution=method_reso, neighbors_key=method)
                count_unique = adata.obs[method_cluster].nunique()

            print(f'resolution={res}, cluster number={count_unique}')

            # Update the best resolution if it's closer to the target
            diff = abs(count_unique - n_clusters)
            if diff < best_diff:
                best_diff = diff
                best_res = res
                best_count = count_unique

            if count_unique == n_clusters:
                label = 1
                break

        if label == 0:
            if best_res is not None:
                # Instead of starting from scratch, continue from the closest found resolution
                if best_count > n_clusters:
                    current_start = min(best_res, current_start * 0.9)  # Avoid too small a search range
                    current_end = min(current_start * expansion_factor, end * 2)  # Limit max range
                    print(f"Expanding search range: new range ({current_start}, {current_end})")
                else:
                    current_start = max(best_res, current_start * 1.2)  # Avoid too small a search range
                    current_end = min(current_start * expansion_factor, end * 2)  # Limit max range
                    print(f"Expanding search range: new range ({current_start}, {current_end})")
            else:
                print("Warning: No valid resolution found yet, expanding the search range.")
                current_start *= expansion_factor
                current_end *= expansion_factor

    if iteration >= max_iter:
        print("Warning: Reached maximum iteration limit.")

    return best_res if label == 1 else None

In [4]:
def count_metrics_for_resolution(dataset, reso_dict=None, start=0.5, end=2.0, increment=0.05):
    rna_dir = f'/data2/zhouwg_data/project/Garfield_benchmark/datasets/MultiomicsBenchmark/Raw_data/RNA_ATAC/{dataset}/RNA'
    atac_dir = f'/data2/zhouwg_data/project/Garfield_benchmark/datasets/MultiomicsBenchmark/Raw_data/RNA_ATAC/{dataset}/ATAC'
    metadata_file = f'/data2/zhouwg_data/project/Garfield_benchmark/datasets/MultiomicsBenchmark/Raw_data/RNA_ATAC/{dataset}/meta_data.csv'
    res_dir = f'/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC/{dataset}'

    # 读取 RNA 和 ATAC 数据
    adata_RNA, adata_ATAC = read_RNA_ATAC(rna_dir, atac_dir)

    # 处理 RNA 数据
    adata_RNA.layers["counts"] = adata_RNA.X.copy()
    sc.pp.normalize_total(adata_RNA)
    sc.pp.log1p(adata_RNA)
    sc.pp.highly_variable_genes(adata_RNA, flavor="seurat_v3", n_top_genes=3000, subset=False)
    adata_RNA = adata_RNA[:, adata_RNA.var.highly_variable].copy()

    # 处理 ATAC 数据
    adata_ATAC.layers['counts'] = adata_ATAC.X.copy()
    sc.pp.normalize_total(adata_ATAC, target_sum=1e4)
    sc.pp.log1p(adata_ATAC)
    adata_ATAC.layers['log-norm'] = adata_ATAC.X.copy()
    sc.pp.highly_variable_genes(adata_ATAC, n_top_genes=10000)
    adata_ATAC = adata_ATAC[:, adata_ATAC.var.highly_variable].copy()

    # 合并 RNA 和 ATAC 数据
    adata = organize_multiome_anndatas(
        adatas=[[adata_RNA], [adata_ATAC]],    # RNA-seq 始终在第一位
        layers=[['counts'], ['log-norm']]      # 使用 .layers 中的数据
    )

    # 读取元数据
    metadata = pd.read_csv(metadata_file, index_col=0)
    metadata.index = adata.obs_names  # 修正元数据的索引
    adata.obs['cell_type'] = metadata['celltype'].astype('category')

    # 处理缺失的 cell_type
    if adata.obs["cell_type"].isna().sum() != 0:
        adata.obs["cell_type"] = adata.obs["cell_type"].cat.add_categories(['NaN'])
        adata.obs.loc[adata.obs["cell_type"].isna(), "cell_type"] = 'NaN'

    adata.obs['batch'] = ['batch1'] * adata.shape[0]

    result = pd.DataFrame()
    metrics_list = []
    method_list = ['Garfield', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat']

    # 计算不同方法的指标
    for method in method_list:
        method_file = f'{res_dir}/{method}.csv'
        if os.path.exists(method_file):
            latent = pd.read_csv(method_file, header=None)
            latent.index = adata.obs_names
            adata.obsm[method] = latent
            print('the length of cell type:', adata.obs['cell_type'].nunique())
            method_cluster = method+'_cluster'
            if reso_dict is not None and dataset in reso_dict.keys():
                data_reso_dict = reso_dict[dataset]
                method_reso = data_reso_dict[method]
                sc.pp.neighbors(adata, use_rep=method, key_added=method)
                if method_reso is not None:
                    print(f'method_reso is not None, using the {method_reso} as resolution for {method}...')
                    sc.tl.leiden(adata,  random_state=0, key_added=method_cluster, 
                                 resolution=method_reso, neighbors_key=method)
                    sc.tl.umap(adata, neighbors_key=method)
                    print('Number of clusters:', adata.obs[method_cluster].nunique())
                else:
                    print('Searching resolution for {}...'.format(method))
                    supervised_clustering(adata, n_clusters=adata.obs['cell_type'].nunique(),
                                          key=method, add_key=method_cluster, cluster_method='leiden',
                                          start=start, end=end, increment=increment)
                    sc.tl.umap(adata, neighbors_key=method)
                    print('Number of clusters:', adata.obs[method_cluster].nunique())
            else:
                print('Searching resolution for {}...'.format(method))
                supervised_clustering(adata, n_clusters=adata.obs['cell_type'].nunique(),
                                      key=method, add_key=method_cluster, cluster_method='leiden',
                                      start=start, end=end, increment=increment)
                sc.tl.umap(adata, neighbors_key=method)
                print('Number of clusters:', adata.obs[method_cluster].nunique())
            # 计算指标
            # scib.metrics.cluster_optimal_resolution(adata, cluster_key="cluster", label_key="cell_type")
            ari = scib.metrics.ari(adata, cluster_key=method_cluster, label_key="cell_type")
            iso_asw = scib.metrics.isolated_labels_asw(adata, label_key="cell_type", batch_key='batch', embed=method, verbose=False)
            nmi = scib.metrics.nmi(adata, cluster_key=method_cluster, label_key="cell_type")
            clisi = scib.metrics.clisi_graph(adata, label_key="cell_type", use_rep=method, type_='embed')
            sht = scib.metrics.silhouette(adata, label_key="cell_type", embed=method, scale=True) #  metric='euclidean',

            metrics_list.append([ari, iso_asw, nmi, clisi, sht, method])

    # 处理 Seurat 的结果 通过 graph 的方式
    if method == 'Seurat_graph':
        method = 'Seurat'
        con = mmread(f'{res_dir}/{method}_connectivities.mtx')
        dis = mmread(f'{res_dir}/{method}_distance.mtx')
        
        # uns['neighbors'] 的信息
        adata.uns['neighbors'] = {
            'connectivities_key': 'connectivities', 'distances_key': 'distances',
            'params': {'n_neighbors': 20, 'method': 'umap', 'random_state': 0, 'metric': 'euclidean'}
        }
        adata.uns['neighbors']['distances'] = csr_matrix(dis)
        adata.uns['neighbors']['connectivities'] = csr_matrix(con)
        adata.obsp['distances'] = csr_matrix(dis)
        adata.obsp['connectivities'] = csr_matrix(con)
        # Seurat 的信息   
        adata.uns['Seurat'] = {
            'connectivities_key': 'Seurat_connectivities', 'distances_key': 'Seurat_distances',
            'params': {'n_neighbors': 20, 'method': 'umap', 'random_state': 0, 'metric': 'euclidean', 'use_rep': 'Seurat'}
        }
        adata.uns['Seurat']['Seurat_distances'] = csr_matrix(dis)
        adata.uns['Seurat']['Seurat_connectivities'] = csr_matrix(con)
        adata.obsp['Seurat_distances'] = csr_matrix(dis)
        adata.obsp['Seurat_connectivities'] = csr_matrix(con)
        
        sc.tl.umap(adata) # , neighbors_key=method
        adata.obsm['Seurat'] = adata.obsm['X_umap'][:, :2]  # 确保只取二维的 UMAP 结果
        method_cluster = method+'_cluster'
        if reso_dict is not None and dataset in reso_dict.keys():
            data_reso_dict = reso_dict[dataset]
            method_reso = data_reso_dict[method]
            if method_reso is not None:
                print(f'method_reso is not None, using the {method_reso} as resolution for {method}...')
                sc.tl.leiden(adata,  random_state=0, key_added=method_cluster, 
                             resolution=method_reso, neighbors_key=method)
                print('Number of clusters:', adata.obs[method_cluster].nunique())
            else:
                print('Searching resolution for Seurat...')
                start = 0.3
                end = 1.5
                increment = 0.05
                for res in sorted(list(np.arange(start, end, increment)), reverse=True):
                   sc.tl.leiden(adata, random_state=0, resolution=res, neighbors_key='Seurat')
                   count_unique = adata.obs['leiden'].nunique()
                   print('resolution={}, cluster number={}'.format(res, count_unique))
                   if count_unique == adata.obs['cell_type'].nunique():
                        break
                print('resolution for Seurat:', res)
                sc.tl.leiden(adata, random_state=0, resolution=res, neighbors_key='Seurat')
                print('Number of clusters:', adata.obs['leiden'].nunique())
                adata.obs[method_cluster] = adata.obs['leiden']
        else:
            print('Searching resolution for Seurat...')
            start = 0.3
            end = 1.5
            increment = 0.05
            for res in sorted(list(np.arange(start, end, increment)), reverse=True):
               sc.tl.leiden(adata, random_state=0, resolution=res, neighbors_key='Seurat')
               count_unique = adata.obs['leiden'].nunique()
               print('resolution={}, cluster number={}'.format(res, count_unique))
               if count_unique == adata.obs['cell_type'].nunique():
                    break
            print('resolution for Seurat:', res)
            sc.tl.leiden(adata, random_state=0, resolution=res, neighbors_key='Seurat')
            print('Number of clusters:', adata.obs['leiden'].nunique())
            adata.obs[method_cluster] = adata.obs['leiden']
    
        # 计算 Seurat 的指标
        # scib.metrics.cluster_optimal_resolution(adata, cluster_key="cluster", label_key="cell_type")
        ari = scib.metrics.ari(adata, cluster_key=method_cluster, label_key="cell_type")
        iso_asw = scib.metrics.isolated_labels_asw(adata, label_key="cell_type", batch_key='batch', embed=method, verbose=False)
        nmi = scib.metrics.nmi(adata, cluster_key=method_cluster, label_key="cell_type")
        clisi = scib.metrics.clisi_graph(adata, label_key="cell_type", use_rep=method, type_='embed')
        sht = scib.metrics.silhouette(adata, label_key="cell_type", embed=method, scale=True) # metric='euclidean',
        metrics_list.append([ari, iso_asw, nmi, clisi, sht, 'Seurat'])

    # 保存结果
    df = pd.DataFrame(metrics_list, columns=['ARI', 'Isolated_Labels_ASW', 'NMI', 'cLISI_Graph', 'Silhouette', 'method'])
    result = pd.concat([result, df], ignore_index=True)
    result['Dataset'] = dataset
    result.to_csv(f'{res_dir}/../{dataset}_metrics_result.csv', index=False)
    print(dataset)

    return adata

In [10]:
def count_metrics_for_best_resolution(dataset):
    rna_dir = f'/data2/zhouwg_data/project/Garfield_benchmark/datasets/MultiomicsBenchmark/Raw_data/RNA_ATAC/{dataset}/RNA'
    atac_dir = f'/data2/zhouwg_data/project/Garfield_benchmark/datasets/MultiomicsBenchmark/Raw_data/RNA_ATAC/{dataset}/ATAC'
    metadata_file = f'/data2/zhouwg_data/project/Garfield_benchmark/datasets/MultiomicsBenchmark/Raw_data/RNA_ATAC/{dataset}/meta_data.csv'
    res_dir = f'/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC/{dataset}'

    # 读取 RNA 和 ATAC 数据
    adata_RNA, adata_ATAC = read_RNA_ATAC(rna_dir, atac_dir)

    # 处理 RNA 数据
    adata_RNA.layers["counts"] = adata_RNA.X.copy()
    sc.pp.normalize_total(adata_RNA)
    sc.pp.log1p(adata_RNA)
    sc.pp.highly_variable_genes(adata_RNA, flavor="seurat_v3", n_top_genes=3000, subset=False)
    adata_RNA = adata_RNA[:, adata_RNA.var.highly_variable].copy()

    # 处理 ATAC 数据
    adata_ATAC.layers['counts'] = adata_ATAC.X.copy()
    sc.pp.normalize_total(adata_ATAC, target_sum=1e4)
    sc.pp.log1p(adata_ATAC)
    adata_ATAC.layers['log-norm'] = adata_ATAC.X.copy()
    sc.pp.highly_variable_genes(adata_ATAC, n_top_genes=10000)
    adata_ATAC = adata_ATAC[:, adata_ATAC.var.highly_variable].copy()

    # 合并 RNA 和 ATAC 数据
    adata = organize_multiome_anndatas(
        adatas=[[adata_RNA], [adata_ATAC]],    # RNA-seq 始终在第一位
        layers=[['counts'], ['log-norm']]      # 使用 .layers 中的数据
    )

    # 读取元数据
    metadata = pd.read_csv(metadata_file, index_col=0)
    metadata.index = adata.obs_names  # 修正元数据的索引
    adata.obs['cell_type'] = metadata['celltype'].astype('category')

    # 处理缺失的 cell_type
    if adata.obs["cell_type"].isna().sum() != 0:
        adata.obs["cell_type"] = adata.obs["cell_type"].cat.add_categories(['NaN'])
        adata.obs.loc[adata.obs["cell_type"].isna(), "cell_type"] = 'NaN'

    adata.obs['batch'] = ['batch1'] * adata.shape[0]

    result = pd.DataFrame()
    metrics_list = []
    method_list = ['Garfield', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat']
    for method in method_list:
        method_file = f'{res_dir}/{method}.csv'
        if os.path.exists(method_file):
            latent = pd.read_csv(method_file, header=None)
            latent.index = adata.obs_names
            adata.obsm[method] = latent
            sc.pp.neighbors(adata, use_rep=method)
            sc.tl.umap(adata)
            # sc.tl.leiden(adata, key_added="cluster")
            scib.metrics.cluster_optimal_resolution(adata, cluster_key="cluster", label_key="cell_type")
            ari = scib.metrics.ari(adata, cluster_key="cluster", label_key="cell_type")
            iso_asw = scib.metrics.isolated_labels_asw(adata, label_key="cell_type", batch_key='batch', embed=method,  verbose = False)
            nmi = scib.metrics.nmi(adata, cluster_key="cluster", label_key="cell_type")
            clisi = scib.metrics.clisi_graph(adata, label_key="cell_type",use_rep=method, type_='embed')
            sht = scib.metrics.silhouette(adata, label_key="cell_type", embed=method, metric='euclidean', scale=True)
            metrics_list.append([ari, iso_asw, nmi, clisi, sht, method])

    # 保存结果
    df = pd.DataFrame(metrics_list, columns=['ARI', 'Isolated_Labels_ASW', 'NMI', 'cLISI_Graph', 'Silhouette', 'method'])
    result = pd.concat([result, df], ignore_index=True)
    result['Dataset'] = dataset
    result.to_csv(f'{res_dir}/../{dataset}_metrics_result_stable_reso.csv', index=False)
    print(dataset)
    
    return adata

### Not 数据集 10_GSE201402_down

In [31]:
## 记录resolution
reso_dict = {
    '10_GSE201402_down': {
        'Garfield': 0.55,
        'Multigrate': 0.8500000000000003,
        'MultiVI': 0.2657205000000001,
        'MOFA': 0.45,
        'Seurat': 0.01390641947218469, 
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('10_GSE201402_down', reso_dict=reso_dict)
adata

the length of cell type: 16
Searching resolution for Garfield...
Searching resolution...
resolution=1.9500000000000013, cluster number=33
resolution=1.9000000000000012, cluster number=34
resolution=1.8500000000000012, cluster number=33
resolution=1.8000000000000012, cluster number=33
resolution=1.750000000000001, cluster number=30
resolution=1.700000000000001, cluster number=31
resolution=1.650000000000001, cluster number=29
resolution=1.600000000000001, cluster number=29
resolution=1.550000000000001, cluster number=28
resolution=1.5000000000000009, cluster number=26
resolution=1.4500000000000008, cluster number=26
resolution=1.4000000000000008, cluster number=26
resolution=1.3500000000000008, cluster number=25
resolution=1.3000000000000007, cluster number=24
resolution=1.2500000000000007, cluster number=24
resolution=1.2000000000000006, cluster number=24
resolution=1.1500000000000006, cluster number=24
resolution=1.1000000000000005, cluster number=23
resolution=1.0500000000000005, cluster number=24
resolution=1.0000000000000004, cluster number=23
resolution=0.9500000000000004, cluster number=23
resolution=0.9000000000000004, cluster number=23
resolution=0.8500000000000003, cluster number=21
resolution=0.8000000000000003, cluster number=20
resolution=0.7500000000000002, cluster number=19
resolution=0.7000000000000002, cluster number=19
resolution=0.6500000000000001, cluster number=18
resolution=0.6000000000000001, cluster number=18
resolution=0.55, cluster number=16
Number of clusters: 16
the length of cell type: 16
method_reso is not None, using the 0.8500000000000003 as resolution for Multigrate...
Number of clusters: 16
the length of cell type: 16
method_reso is not None, using the 0.2657205000000001 as resolution for MultiVI...
Number of clusters: 16
Chunk 161 does not have enough neighbors. Skipping...
Chunk 650 does not have enough neighbors. Skipping...
Chunk 1092 does not have enough neighbors. Skipping...
Chunk 1656 does not have enough neighbors. Skipping...
Chunk 1726 does not have enough neighbors. Skipping...
Chunk 1734 does not have enough neighbors. Skipping...
Chunk 2009 does not have enough neighbors. Skipping...
Chunk 2255 does not have enough neighbors. Skipping...
Chunk 2774 does not have enough neighbors. Skipping...
Chunk 2883 does not have enough neighbors. Skipping...
Chunk 2976 does not have enough neighbors. Skipping...
Chunk 3627 does not have enough neighbors. Skipping...
Chunk 3828 does not have enough neighbors. Skipping...
Chunk 4812 does not have enough neighbors. Skipping...
Chunk 5097 does not have enough neighbors. Skipping...
Chunk 6137 does not have enough neighbors. Skipping...
Chunk 6487 does not have enough neighbors. Skipping...
Chunk 6624 does not have enough neighbors. Skipping...
Chunk 6690 does not have enough neighbors. Skipping...
Chunk 6788 does not have enough neighbors. Skipping...
Chunk 7672 does not have enough neighbors. Skipping...
Chunk 8131 does not have enough neighbors. Skipping...
Chunk 8224 does not have enough neighbors. Skipping...
Chunk 9210 does not have enough neighbors. Skipping...
the length of cell type: 16
method_reso is not None, using the 0.45 as resolution for MOFA...
Number of clusters: 16
the length of cell type: 16
method_reso is not None, using the 0.01390641947218469 as resolution for Seurat...
Number of clusters: 16
Chunk 83 does not have enough neighbors. Skipping...
Chunk 141 does not have enough neighbors. Skipping...
Chunk 161 does not have enough neighbors. Skipping...
Chunk 226 does not have enough neighbors. Skipping...
Chunk 296 does not have enough neighbors. Skipping...
Chunk 332 does not have enough neighbors. Skipping...
Chunk 417 does not have enough neighbors. Skipping...
Chunk 500 does not have enough neighbors. Skipping...
Chunk 541 does not have enough neighbors. Skipping...
Chunk 559 does not have enough neighbors. Skipping...
Chunk 576 does not have enough neighbors. Skipping...
Chunk 586 does not have enough neighbors. Skipping...
Chunk 593 does not have enough neighbors. Skipping...
Chunk 614 does not have enough neighbors. Skipping...
Chunk 639 does not have enough neighbors. Skipping...
Chunk 650 does not have enough neighbors. Skipping...
Chunk 663 does not have enough neighbors. Skipping...
Chunk 681 does not have enough neighbors. Skipping...
Chunk 683 does not have enough neighbors. Skipping...
Chunk 702 does not have enough neighbors. Skipping...
Chunk 749 does not have enough neighbors. Skipping...
Chunk 763 does not have enough neighbors. Skipping...
Chunk 776 does not have enough neighbors. Skipping...
Chunk 803 does not have enough neighbors. Skipping...
Chunk 824 does not have enough neighbors. Skipping...
Chunk 844 does not have enough neighbors. Skipping...
Chunk 921 does not have enough neighbors. Skipping...
Chunk 967 does not have enough neighbors. Skipping...
Chunk 991 does not have enough neighbors. Skipping...
Chunk 1010 does not have enough neighbors. Skipping...
Chunk 1054 does not have enough neighbors. Skipping...
Chunk 1070 does not have enough neighbors. Skipping...
Chunk 1086 does not have enough neighbors. Skipping...
Chunk 1092 does not have enough neighbors. Skipping...
Chunk 1127 does not have enough neighbors. Skipping...
Chunk 1171 does not have enough neighbors. Skipping...
Chunk 1198 does not have enough neighbors. Skipping...
Chunk 1233 does not have enough neighbors. Skipping...
Chunk 1241 does not have enough neighbors. Skipping...
Chunk 1246 does not have enough neighbors. Skipping...
Chunk 1275 does not have enough neighbors. Skipping...
Chunk 1289 does not have enough neighbors. Skipping...
Chunk 1342 does not have enough neighbors. Skipping...
Chunk 1376 does not have enough neighbors. Skipping...
Chunk 1378 does not have enough neighbors. Skipping...
Chunk 1396 does not have enough neighbors. Skipping...
Chunk 1436 does not have enough neighbors. Skipping...
Chunk 1458 does not have enough neighbors. Skipping...
Chunk 1543 does not have enough neighbors. Skipping...
Chunk 1599 does not have enough neighbors. Skipping...
Chunk 1639 does not have enough neighbors. Skipping...
Chunk 1656 does not have enough neighbors. Skipping...
Chunk 1681 does not have enough neighbors. Skipping...
Chunk 1726 does not have enough neighbors. Skipping...
Chunk 1734 does not have enough neighbors. Skipping...
Chunk 1747 does not have enough neighbors. Skipping...
Chunk 1757 does not have enough neighbors. Skipping...
Chunk 1856 does not have enough neighbors. Skipping...
Chunk 1879 does not have enough neighbors. Skipping...
Chunk 1888 does not have enough neighbors. Skipping...
Chunk 1922 does not have enough neighbors. Skipping...
Chunk 2004 does not have enough neighbors. Skipping...
Chunk 2009 does not have enough neighbors. Skipping...
Chunk 2033 does not have enough neighbors. Skipping...
Chunk 2092 does not have enough neighbors. Skipping...
Chunk 2133 does not have enough neighbors. Skipping...
Chunk 2139 does not have enough neighbors. Skipping...
Chunk 2161 does not have enough neighbors. Skipping...
Chunk 2203 does not have enough neighbors. Skipping...
Chunk 2255 does not have enough neighbors. Skipping...
Chunk 2313 does not have enough neighbors. Skipping...
Chunk 2329 does not have enough neighbors. Skipping...
Chunk 2343 does not have enough neighbors. Skipping...
Chunk 2406 does not have enough neighbors. Skipping...
Chunk 2429 does not have enough neighbors. Skipping...
Chunk 2451 does not have enough neighbors. Skipping...
Chunk 2491 does not have enough neighbors. Skipping...
Chunk 2529 does not have enough neighbors. Skipping...
Chunk 2541 does not have enough neighbors. Skipping...
Chunk 2597 does not have enough neighbors. Skipping...
Chunk 2655 does not have enough neighbors. Skipping...
Chunk 2656 does not have enough neighbors. Skipping...
Chunk 2721 does not have enough neighbors. Skipping...
Chunk 2766 does not have enough neighbors. Skipping...
Chunk 2774 does not have enough neighbors. Skipping...
Chunk 2785 does not have enough neighbors. Skipping...
Chunk 2883 does not have enough neighbors. Skipping...
Chunk 2941 does not have enough neighbors. Skipping...
Chunk 2942 does not have enough neighbors. Skipping...
Chunk 2976 does not have enough neighbors. Skipping...
Chunk 3025 does not have enough neighbors. Skipping...
Chunk 3055 does not have enough neighbors. Skipping...
Chunk 3103 does not have enough neighbors. Skipping...
Chunk 3115 does not have enough neighbors. Skipping...
Chunk 3189 does not have enough neighbors. Skipping...
Chunk 3190 does not have enough neighbors. Skipping...
Chunk 3203 does not have enough neighbors. Skipping...
Chunk 3223 does not have enough neighbors. Skipping...
Chunk 3224 does not have enough neighbors. Skipping...
Chunk 3229 does not have enough neighbors. Skipping...
Chunk 3233 does not have enough neighbors. Skipping...
Chunk 3245 does not have enough neighbors. Skipping...
Chunk 3246 does not have enough neighbors. Skipping...
Chunk 3263 does not have enough neighbors. Skipping...
Chunk 3270 does not have enough neighbors. Skipping...
Chunk 3287 does not have enough neighbors. Skipping...
Chunk 3296 does not have enough neighbors. Skipping...
Chunk 3316 does not have enough neighbors. Skipping...
Chunk 3343 does not have enough neighbors. Skipping...
Chunk 3363 does not have enough neighbors. Skipping...
Chunk 3380 does not have enough neighbors. Skipping...
Chunk 3423 does not have enough neighbors. Skipping...
Chunk 3530 does not have enough neighbors. Skipping...
Chunk 3589 does not have enough neighbors. Skipping...
Chunk 3605 does not have enough neighbors. Skipping...
Chunk 3623 does not have enough neighbors. Skipping...
Chunk 3627 does not have enough neighbors. Skipping...
Chunk 3630 does not have enough neighbors. Skipping...
Chunk 3666 does not have enough neighbors. Skipping...
Chunk 3694 does not have enough neighbors. Skipping...
Chunk 3708 does not have enough neighbors. Skipping...
Chunk 3764 does not have enough neighbors. Skipping...
Chunk 3788 does not have enough neighbors. Skipping...
Chunk 3806 does not have enough neighbors. Skipping...
Chunk 3828 does not have enough neighbors. Skipping...
Chunk 3853 does not have enough neighbors. Skipping...
Chunk 3859 does not have enough neighbors. Skipping...
Chunk 3868 does not have enough neighbors. Skipping...
Chunk 3906 does not have enough neighbors. Skipping...
Chunk 4010 does not have enough neighbors. Skipping...
Chunk 4034 does not have enough neighbors. Skipping...
Chunk 4041 does not have enough neighbors. Skipping...
Chunk 4056 does not have enough neighbors. Skipping...
Chunk 4068 does not have enough neighbors. Skipping...
Chunk 4076 does not have enough neighbors. Skipping...
Chunk 4117 does not have enough neighbors. Skipping...
Chunk 4189 does not have enough neighbors. Skipping...
Chunk 4234 does not have enough neighbors. Skipping...
Chunk 4265 does not have enough neighbors. Skipping...
Chunk 4269 does not have enough neighbors. Skipping...
Chunk 4275 does not have enough neighbors. Skipping...
Chunk 4337 does not have enough neighbors. Skipping...
Chunk 4366 does not have enough neighbors. Skipping...
Chunk 4393 does not have enough neighbors. Skipping...
Chunk 4401 does not have enough neighbors. Skipping...
Chunk 4422 does not have enough neighbors. Skipping...
Chunk 4453 does not have enough neighbors. Skipping...
Chunk 4618 does not have enough neighbors. Skipping...
Chunk 4625 does not have enough neighbors. Skipping...
Chunk 4642 does not have enough neighbors. Skipping...
Chunk 4647 does not have enough neighbors. Skipping...
Chunk 4655 does not have enough neighbors. Skipping...
Chunk 4664 does not have enough neighbors. Skipping...
Chunk 4678 does not have enough neighbors. Skipping...
Chunk 4695 does not have enough neighbors. Skipping...
Chunk 4812 does not have enough neighbors. Skipping...
Chunk 4864 does not have enough neighbors. Skipping...
Chunk 4909 does not have enough neighbors. Skipping...
Chunk 4933 does not have enough neighbors. Skipping...
Chunk 4955 does not have enough neighbors. Skipping...
Chunk 4991 does not have enough neighbors. Skipping...
Chunk 5066 does not have enough neighbors. Skipping...
Chunk 5091 does not have enough neighbors. Skipping...
Chunk 5097 does not have enough neighbors. Skipping...
Chunk 5121 does not have enough neighbors. Skipping...
Chunk 5173 does not have enough neighbors. Skipping...
Chunk 5206 does not have enough neighbors. Skipping...
Chunk 5328 does not have enough neighbors. Skipping...
Chunk 5378 does not have enough neighbors. Skipping...
Chunk 5380 does not have enough neighbors. Skipping...
Chunk 5386 does not have enough neighbors. Skipping...
Chunk 5473 does not have enough neighbors. Skipping...
Chunk 5507 does not have enough neighbors. Skipping...
Chunk 5519 does not have enough neighbors. Skipping...
Chunk 5552 does not have enough neighbors. Skipping...
Chunk 5599 does not have enough neighbors. Skipping...
Chunk 5624 does not have enough neighbors. Skipping...
Chunk 5681 does not have enough neighbors. Skipping...
Chunk 5682 does not have enough neighbors. Skipping...
Chunk 5733 does not have enough neighbors. Skipping...
Chunk 5739 does not have enough neighbors. Skipping...
Chunk 5752 does not have enough neighbors. Skipping...
Chunk 5755 does not have enough neighbors. Skipping...
Chunk 5780 does not have enough neighbors. Skipping...
Chunk 5841 does not have enough neighbors. Skipping...
Chunk 5853 does not have enough neighbors. Skipping...
Chunk 5859 does not have enough neighbors. Skipping...
Chunk 5863 does not have enough neighbors. Skipping...
Chunk 5914 does not have enough neighbors. Skipping...
Chunk 5936 does not have enough neighbors. Skipping...
Chunk 5937 does not have enough neighbors. Skipping...
Chunk 5953 does not have enough neighbors. Skipping...
Chunk 5993 does not have enough neighbors. Skipping...
Chunk 5995 does not have enough neighbors. Skipping...
Chunk 6016 does not have enough neighbors. Skipping...
Chunk 6020 does not have enough neighbors. Skipping...
Chunk 6047 does not have enough neighbors. Skipping...
Chunk 6051 does not have enough neighbors. Skipping...
Chunk 6067 does not have enough neighbors. Skipping...
Chunk 6083 does not have enough neighbors. Skipping...
Chunk 6137 does not have enough neighbors. Skipping...
Chunk 6187 does not have enough neighbors. Skipping...
Chunk 6193 does not have enough neighbors. Skipping...
Chunk 6197 does not have enough neighbors. Skipping...
Chunk 6206 does not have enough neighbors. Skipping...
Chunk 6215 does not have enough neighbors. Skipping...
Chunk 6290 does not have enough neighbors. Skipping...
Chunk 6298 does not have enough neighbors. Skipping...
Chunk 6300 does not have enough neighbors. Skipping...
Chunk 6314 does not have enough neighbors. Skipping...
Chunk 6376 does not have enough neighbors. Skipping...
Chunk 6402 does not have enough neighbors. Skipping...
Chunk 6487 does not have enough neighbors. Skipping...
Chunk 6526 does not have enough neighbors. Skipping...
Chunk 6534 does not have enough neighbors. Skipping...
Chunk 6539 does not have enough neighbors. Skipping...
Chunk 6566 does not have enough neighbors. Skipping...
Chunk 6575 does not have enough neighbors. Skipping...
Chunk 6590 does not have enough neighbors. Skipping...
Chunk 6594 does not have enough neighbors. Skipping...
Chunk 6624 does not have enough neighbors. Skipping...
Chunk 6669 does not have enough neighbors. Skipping...
Chunk 6678 does not have enough neighbors. Skipping...
Chunk 6679 does not have enough neighbors. Skipping...
Chunk 6690 does not have enough neighbors. Skipping...
Chunk 6701 does not have enough neighbors. Skipping...
Chunk 6774 does not have enough neighbors. Skipping...
Chunk 6788 does not have enough neighbors. Skipping...
Chunk 6815 does not have enough neighbors. Skipping...
Chunk 6875 does not have enough neighbors. Skipping...
Chunk 6904 does not have enough neighbors. Skipping...
Chunk 6935 does not have enough neighbors. Skipping...
Chunk 6955 does not have enough neighbors. Skipping...
Chunk 6983 does not have enough neighbors. Skipping...
Chunk 6986 does not have enough neighbors. Skipping...
Chunk 6998 does not have enough neighbors. Skipping...
Chunk 7010 does not have enough neighbors. Skipping...
Chunk 7011 does not have enough neighbors. Skipping...
Chunk 7014 does not have enough neighbors. Skipping...
Chunk 7091 does not have enough neighbors. Skipping...
Chunk 7114 does not have enough neighbors. Skipping...
Chunk 7124 does not have enough neighbors. Skipping...
Chunk 7192 does not have enough neighbors. Skipping...
Chunk 7201 does not have enough neighbors. Skipping...
Chunk 7219 does not have enough neighbors. Skipping...
Chunk 7220 does not have enough neighbors. Skipping...
Chunk 7236 does not have enough neighbors. Skipping...
Chunk 7253 does not have enough neighbors. Skipping...
Chunk 7257 does not have enough neighbors. Skipping...
Chunk 7273 does not have enough neighbors. Skipping...
Chunk 7317 does not have enough neighbors. Skipping...
Chunk 7321 does not have enough neighbors. Skipping...
Chunk 7423 does not have enough neighbors. Skipping...
Chunk 7479 does not have enough neighbors. Skipping...
Chunk 7505 does not have enough neighbors. Skipping...
Chunk 7534 does not have enough neighbors. Skipping...
Chunk 7555 does not have enough neighbors. Skipping...
Chunk 7625 does not have enough neighbors. Skipping...
Chunk 7629 does not have enough neighbors. Skipping...
Chunk 7641 does not have enough neighbors. Skipping...
Chunk 7665 does not have enough neighbors. Skipping...
Chunk 7670 does not have enough neighbors. Skipping...
Chunk 7672 does not have enough neighbors. Skipping...
Chunk 7683 does not have enough neighbors. Skipping...
Chunk 7750 does not have enough neighbors. Skipping...
Chunk 7765 does not have enough neighbors. Skipping...
Chunk 7774 does not have enough neighbors. Skipping...
Chunk 7836 does not have enough neighbors. Skipping...
Chunk 7847 does not have enough neighbors. Skipping...
Chunk 7869 does not have enough neighbors. Skipping...
Chunk 7878 does not have enough neighbors. Skipping...
Chunk 7989 does not have enough neighbors. Skipping...
Chunk 8075 does not have enough neighbors. Skipping...
Chunk 8080 does not have enough neighbors. Skipping...
Chunk 8112 does not have enough neighbors. Skipping...
Chunk 8131 does not have enough neighbors. Skipping...
Chunk 8146 does not have enough neighbors. Skipping...
Chunk 8186 does not have enough neighbors. Skipping...
Chunk 8224 does not have enough neighbors. Skipping...
Chunk 8225 does not have enough neighbors. Skipping...
Chunk 8235 does not have enough neighbors. Skipping...
Chunk 8255 does not have enough neighbors. Skipping...
Chunk 8368 does not have enough neighbors. Skipping...
Chunk 8371 does not have enough neighbors. Skipping...
Chunk 8374 does not have enough neighbors. Skipping...
Chunk 8431 does not have enough neighbors. Skipping...
Chunk 8453 does not have enough neighbors. Skipping...
Chunk 8506 does not have enough neighbors. Skipping...
Chunk 8516 does not have enough neighbors. Skipping...
Chunk 8535 does not have enough neighbors. Skipping...
Chunk 8561 does not have enough neighbors. Skipping...
Chunk 8570 does not have enough neighbors. Skipping...
Chunk 8583 does not have enough neighbors. Skipping...
Chunk 8630 does not have enough neighbors. Skipping...
Chunk 8668 does not have enough neighbors. Skipping...
Chunk 8704 does not have enough neighbors. Skipping...
Chunk 8721 does not have enough neighbors. Skipping...
Chunk 8779 does not have enough neighbors. Skipping...
Chunk 8816 does not have enough neighbors. Skipping...
Chunk 8840 does not have enough neighbors. Skipping...
Chunk 8865 does not have enough neighbors. Skipping...
Chunk 8901 does not have enough neighbors. Skipping...
Chunk 8939 does not have enough neighbors. Skipping...

AnnData object with n_obs × n_vars = 9383 × 13000
    obs: 'group', 'cell_type', 'batch', 'Garfield_cluster', 'silhouette_temp', 'Multigrate_cluster', 'MultiVI_cluster', 'MOFA_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'MultiVI', 'MultiVI_cluster', 'MOFA', 'MOFA_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'MultiVI_distances', 'MultiVI_connectivities', 'MOFA_distances', 'MOFA_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [32]:
import matplotlib.pyplot as plt

dataset = '10_GSE201402_down'
res_dir = f'/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC/{dataset}'

latent_key_list = ['Garfield', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat']
for latent_key in latent_key_list:
    sc.tl.umap(adata, neighbors_key=latent_key)
    latent_key_cluster = latent_key + '_cluster'
    
    # Create a new figure for each plot with an appropriate size
    plt.figure(figsize=(12, 6))  # Adjust the figsize as needed
    sc.pl.umap(adata, color=['cell_type', latent_key_cluster], wspace=0.5, hspace=0.5, show=False, ncols=2)
    # Save the figure
    plt.savefig(res_dir + f"/{latent_key}_UMAP_clusters.png", bbox_inches='tight')  # Use bbox_inches to ensure full legend display
    plt.close()

In [33]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '10_GSE201402_down'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.140319,0.588752,0.524695,1.0,0.734643,Garfield,10_GSE201402_down
1,0.248909,0.591281,0.622897,1.0,0.627959,Multigrate,10_GSE201402_down
2,0.197756,0.761025,0.583809,1.0,0.785782,MultiVI,10_GSE201402_down
3,0.264119,0.676466,0.633253,1.0,0.788906,MOFA,10_GSE201402_down
4,0.477558,0.831389,0.745378,1.0,0.761591,Seurat,10_GSE201402_down

#### 探索一下用最佳分辨率

In [20]:
# calculate the metrics based on the best resolution
adata = count_metrics_for_best_resolution('10_GSE201402_down')
adata

WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.707773672061088
resolution: 0.2, nmi: 0.7188311447696103
resolution: 0.3, nmi: 0.7188311447696103
resolution: 0.4, nmi: 0.7199456855325836
resolution: 0.5, nmi: 0.7249505132333783
resolution: 0.6, nmi: 0.7078065102280388
resolution: 0.7, nmi: 0.7149290383827273
resolution: 0.8, nmi: 0.7022986337209329
resolution: 0.9, nmi: 0.6711186766525109
resolution: 1.0, nmi: 0.6790145617863353
resolution: 1.1, nmi: 0.6656990046238804
resolution: 1.2, nmi: 0.6696040322364775
resolution: 1.3, nmi: 0.6644144153347636
resolution: 1.4, nmi: 0.6534915586972398
resolution: 1.5, nmi: 0.6502094566335053
resolution: 1.6, nmi: 0.6579376494847752
resolution: 1.7, nmi: 0.6439820276067458
resolution: 1.8, nmi: 0.6122456835491061
resolution: 1.9, nmi: 0.6262365923325991
resolution: 2.0, nmi: 0.6058718893678586
optimised clustering against cell_type
optimal cluster resolution: 0.5
optimal score: 0.7249505132333783
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.6158810825337998
resolution: 0.2, nmi: 0.6790802949165606
resolution: 0.3, nmi: 0.6741792430540924
resolution: 0.4, nmi: 0.6305252318947647
resolution: 0.5, nmi: 0.6281787122312906
resolution: 0.6, nmi: 0.6260984685916402
resolution: 0.7, nmi: 0.6259675290619542
resolution: 0.8, nmi: 0.6255037682498872
resolution: 0.9, nmi: 0.5840539923846025
resolution: 1.0, nmi: 0.5862234946982833
resolution: 1.1, nmi: 0.5630735948977236
resolution: 1.2, nmi: 0.5636332055580744
resolution: 1.3, nmi: 0.552477629159422
resolution: 1.4, nmi: 0.5432990468938222
resolution: 1.5, nmi: 0.5153858996349006
resolution: 1.6, nmi: 0.523256407003899
resolution: 1.7, nmi: 0.5131193522198684
resolution: 1.8, nmi: 0.510942957088587
resolution: 1.9, nmi: 0.5026688719965015
resolution: 2.0, nmi: 0.48963580478294705
optimised clustering against cell_type
optimal cluster resolution: 0.2
optimal score: 0.6790802949165606
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.7258247302648931
resolution: 0.2, nmi: 0.7457629471139692
resolution: 0.3, nmi: 0.7416615891990672
resolution: 0.4, nmi: 0.7401976314966857
resolution: 0.5, nmi: 0.7206015521304618
resolution: 0.6, nmi: 0.7065167925399849
resolution: 0.7, nmi: 0.6949998730192013
resolution: 0.8, nmi: 0.6849467666580544
resolution: 0.9, nmi: 0.6718156997721992
resolution: 1.0, nmi: 0.6702708352866996
resolution: 1.1, nmi: 0.6658746116781936
resolution: 1.2, nmi: 0.6727249577668037
resolution: 1.3, nmi: 0.6696537817305759
resolution: 1.4, nmi: 0.6706379710865672
resolution: 1.5, nmi: 0.6712729827859646
resolution: 1.6, nmi: 0.6679233577603171
resolution: 1.7, nmi: 0.6534035929866333
resolution: 1.8, nmi: 0.6542291327054798
resolution: 1.9, nmi: 0.6495425973381524
resolution: 2.0, nmi: 0.6478283307786904
optimised clustering against cell_type
optimal cluster resolution: 0.2
optimal score: 0.7457629471139692
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.7379284046315013
resolution: 0.2, nmi: 0.7062142647030357
resolution: 0.3, nmi: 0.700575022489436
resolution: 0.4, nmi: 0.6816561295017295
resolution: 0.5, nmi: 0.6656534980955203
resolution: 0.6, nmi: 0.6554917086589918
resolution: 0.7, nmi: 0.6525868546731051
resolution: 0.8, nmi: 0.6682183262289807
resolution: 0.9, nmi: 0.6667231597351525
resolution: 1.0, nmi: 0.6625680642599806
resolution: 1.1, nmi: 0.6482999879140341
resolution: 1.2, nmi: 0.6634765484516131
resolution: 1.3, nmi: 0.6510433240966645
resolution: 1.4, nmi: 0.64900057763038
resolution: 1.5, nmi: 0.6414541167084794
resolution: 1.6, nmi: 0.6527304551273824
resolution: 1.7, nmi: 0.6377736418017607
resolution: 1.8, nmi: 0.6226059238887123
resolution: 1.9, nmi: 0.6266960810637526
resolution: 2.0, nmi: 0.6174764078594958
optimised clustering against cell_type
optimal cluster resolution: 0.1
optimal score: 0.7379284046315013
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.7790004039231259
resolution: 0.2, nmi: 0.7901290024096919
resolution: 0.3, nmi: 0.7374805744648361
resolution: 0.4, nmi: 0.7241765883316433
resolution: 0.5, nmi: 0.722197934694869
resolution: 0.6, nmi: 0.705791697381625
resolution: 0.7, nmi: 0.6998714975122615
resolution: 0.8, nmi: 0.698308438955164
resolution: 0.9, nmi: 0.694089611692816
resolution: 1.0, nmi: 0.6887140204378595
resolution: 1.1, nmi: 0.6773723992787042
resolution: 1.2, nmi: 0.6764277995222006
resolution: 1.3, nmi: 0.6691529956539339
resolution: 1.4, nmi: 0.6613600365772826
resolution: 1.5, nmi: 0.6509258663549231
resolution: 1.6, nmi: 0.6504141286771317
resolution: 1.7, nmi: 0.6500297795983279
resolution: 1.8, nmi: 0.6445416064686703
resolution: 1.9, nmi: 0.6396274317910303
resolution: 2.0, nmi: 0.6360532145449
optimised clustering against cell_type
optimal cluster resolution: 0.2
optimal score: 0.7901290024096919
Chunk 138 does not have enough neighbors. Skipping...
Chunk 142 does not have enough neighbors. Skipping...
Chunk 204 does not have enough neighbors. Skipping...
Chunk 352 does not have enough neighbors. Skipping...
Chunk 379 does not have enough neighbors. Skipping...
Chunk 421 does not have enough neighbors. Skipping...
Chunk 804 does not have enough neighbors. Skipping...
Chunk 1016 does not have enough neighbors. Skipping...
Chunk 1491 does not have enough neighbors. Skipping...
Chunk 1754 does not have enough neighbors. Skipping...
Chunk 1889 does not have enough neighbors. Skipping...
Chunk 1928 does not have enough neighbors. Skipping...
Chunk 1990 does not have enough neighbors. Skipping...
Chunk 2070 does not have enough neighbors. Skipping...
Chunk 2094 does not have enough neighbors. Skipping...
Chunk 2146 does not have enough neighbors. Skipping...
Chunk 2259 does not have enough neighbors. Skipping...
Chunk 2383 does not have enough neighbors. Skipping...
Chunk 2413 does not have enough neighbors. Skipping...
9_pbmc_unsorted_3k

AnnData object with n_obs × n_vars = 2413 × 13000
    obs: 'group', 'cell_type', 'batch', 'silhouette_temp', 'cluster'
    var: 'modality'
    uns: 'modality_lengths', 'neighbors', 'umap', 'cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'distances', 'connectivities'

In [ ]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '10_GSE201402_down'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result_best_reso.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

### 数据集 9_pbmc_unsorted_3k

In [26]:
## 记录resolution
reso_dict = {
    '9_pbmc_unsorted_3k': {
        'Garfield': 1.2500000000000007,
        'Multigrate': 1.700000000000001,
        'MultiVI': 0.455,
        'MOFA': 0.45,
        'Seurat': 0.14121476824050008, 
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('9_pbmc_unsorted_3k', reso_dict=reso_dict)
adata

the length of cell type: 12
Searching resolution for Garfield...
Searching resolution...
resolution=1.9500000000000013, cluster number=17
resolution=1.9000000000000012, cluster number=16
resolution=1.8500000000000012, cluster number=16
resolution=1.8000000000000012, cluster number=16
resolution=1.750000000000001, cluster number=16
resolution=1.700000000000001, cluster number=16
resolution=1.650000000000001, cluster number=14
resolution=1.600000000000001, cluster number=15
resolution=1.550000000000001, cluster number=15
resolution=1.5000000000000009, cluster number=15
resolution=1.4500000000000008, cluster number=14
resolution=1.4000000000000008, cluster number=15
resolution=1.3500000000000008, cluster number=14
resolution=1.3000000000000007, cluster number=13
resolution=1.2500000000000007, cluster number=12
Number of clusters: 12
the length of cell type: 12
method_reso is not None, using the 1.700000000000001 as resolution for Multigrate...
Number of clusters: 12
the length of cell type: 12
method_reso is not None, using the 0.455 as resolution for MultiVI...
Number of clusters: 12
the length of cell type: 12
method_reso is not None, using the 0.45 as resolution for MOFA...
Number of clusters: 12
the length of cell type: 12
method_reso is not None, using the 0.14121476824050008 as resolution for Seurat...
Number of clusters: 12
Chunk 138 does not have enough neighbors. Skipping...
Chunk 142 does not have enough neighbors. Skipping...
Chunk 204 does not have enough neighbors. Skipping...
Chunk 352 does not have enough neighbors. Skipping...
Chunk 379 does not have enough neighbors. Skipping...
Chunk 421 does not have enough neighbors. Skipping...
Chunk 804 does not have enough neighbors. Skipping...
Chunk 1016 does not have enough neighbors. Skipping...
Chunk 1491 does not have enough neighbors. Skipping...
Chunk 1754 does not have enough neighbors. Skipping...
Chunk 1889 does not have enough neighbors. Skipping...
Chunk 1928 does not have enough neighbors. Skipping...
Chunk 1990 does not have enough neighbors. Skipping...
Chunk 2070 does not have enough neighbors. Skipping...
Chunk 2094 does not have enough neighbors. Skipping...
Chunk 2146 does not have enough neighbors. Skipping...
Chunk 2259 does not have enough neighbors. Skipping...
Chunk 2383 does not have enough neighbors. Skipping...
Chunk 2413 does not have enough neighbors. Skipping...
9_pbmc_unsorted_3k

AnnData object with n_obs × n_vars = 2413 × 13000
    obs: 'group', 'cell_type', 'batch', 'Garfield_cluster', 'silhouette_temp', 'Multigrate_cluster', 'MultiVI_cluster', 'MOFA_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'MultiVI', 'MultiVI_cluster', 'MOFA', 'MOFA_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'MultiVI_distances', 'MultiVI_connectivities', 'MOFA_distances', 'MOFA_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [27]:
import matplotlib.pyplot as plt

dataset = '9_pbmc_unsorted_3k'
res_dir = f'/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC/{dataset}'

latent_key_list = ['Garfield', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat']
for latent_key in latent_key_list:
    sc.tl.umap(adata, neighbors_key=latent_key)
    latent_key_cluster = latent_key + '_cluster'
    
    # Create a new figure for each plot with an appropriate size
    plt.figure(figsize=(12, 6))  # Adjust the figsize as needed
    sc.pl.umap(adata, color=['cell_type', latent_key_cluster], wspace=0.5, hspace=0.5, show=False, ncols=2)
    # Save the figure
    plt.savefig(res_dir + f"/{latent_key}_UMAP_clusters.png", bbox_inches='tight')  # Use bbox_inches to ensure full legend display
    plt.close()

In [28]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '9_pbmc_unsorted_3k'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.455839,0.559999,0.664593,0.958354,0.507223,Garfield,9_pbmc_unsorted_3k
1,0.270386,0.505980,0.513119,0.879847,0.503597,Multigrate,9_pbmc_unsorted_3k
2,0.486626,0.707436,0.729399,0.993246,0.658809,MultiVI,9_pbmc_unsorted_3k
3,0.519998,0.608050,0.674235,0.981996,0.575843,MOFA,9_pbmc_unsorted_3k
4,0.626682,0.795544,0.779000,0.997477,0.702561,Seurat,9_pbmc_unsorted_3k

#### 使用默认固定的resolution

In [11]:
# calculate the metrics based on the best resolution
adata = count_metrics_for_best_resolution('9_pbmc_unsorted_3k')
adata

Chunk 138 does not have enough neighbors. Skipping...
Chunk 142 does not have enough neighbors. Skipping...
Chunk 204 does not have enough neighbors. Skipping...
Chunk 352 does not have enough neighbors. Skipping...
Chunk 379 does not have enough neighbors. Skipping...
Chunk 421 does not have enough neighbors. Skipping...
Chunk 804 does not have enough neighbors. Skipping...
Chunk 1016 does not have enough neighbors. Skipping...
Chunk 1491 does not have enough neighbors. Skipping...
Chunk 1754 does not have enough neighbors. Skipping...
Chunk 1889 does not have enough neighbors. Skipping...
Chunk 1928 does not have enough neighbors. Skipping...
Chunk 1990 does not have enough neighbors. Skipping...
Chunk 2070 does not have enough neighbors. Skipping...
Chunk 2094 does not have enough neighbors. Skipping...
Chunk 2146 does not have enough neighbors. Skipping...
Chunk 2259 does not have enough neighbors. Skipping...
Chunk 2383 does not have enough neighbors. Skipping...
Chunk 2413 does not have enough neighbors. Skipping...
9_pbmc_unsorted_3k

AnnData object with n_obs × n_vars = 2413 × 13000
    obs: 'group', 'cell_type', 'batch', 'cluster', 'silhouette_temp'
    var: 'modality'
    uns: 'modality_lengths', 'neighbors', 'umap', 'cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'distances', 'connectivities'

In [12]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '9_pbmc_unsorted_3k'

# df = pd.read_csv(f'{save_path}/{dataset}_metrics_result_best_reso.csv')
df = pd.read_csv(f'{save_path}/{dataset}_metrics_result_stable_reso.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.539063,0.559999,0.718015,0.958354,0.507223,Garfield,9_pbmc_unsorted_3k
1,0.396722,0.505980,0.586223,0.879847,0.503597,Multigrate,9_pbmc_unsorted_3k
2,0.318746,0.707436,0.670271,0.993246,0.658809,MultiVI,9_pbmc_unsorted_3k
3,0.394702,0.608050,0.662568,0.981996,0.575843,MOFA,9_pbmc_unsorted_3k
4,0.301517,0.795544,0.688714,0.997477,0.702561,Seurat,9_pbmc_unsorted_3k

#### 利用最佳分辨率计算指标

In [6]:
## 记录resolution
reso_dict = {
    '9_pbmc_unsorted_3k': {
        'Garfield': 0.5, # 1.2500000000000007,
        'Multigrate': 1.700000000000001,
        'MultiVI': 0.455,
        'MOFA': 0.45,
        'Seurat': 0.14121476824050008, 
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('9_pbmc_unsorted_3k', reso_dict=reso_dict)
adata

the length of cell type: 12
method_reso is not None, using the 0.5 as resolution for Garfield...
Number of clusters: 7
the length of cell type: 12
method_reso is not None, using the 1.700000000000001 as resolution for Multigrate...
Number of clusters: 12
the length of cell type: 12
method_reso is not None, using the 0.455 as resolution for MultiVI...
Number of clusters: 12
the length of cell type: 12
method_reso is not None, using the 0.45 as resolution for MOFA...
Number of clusters: 12
the length of cell type: 12
method_reso is not None, using the 0.14121476824050008 as resolution for Seurat...
Number of clusters: 12
Chunk 138 does not have enough neighbors. Skipping...
Chunk 142 does not have enough neighbors. Skipping...
Chunk 204 does not have enough neighbors. Skipping...
Chunk 352 does not have enough neighbors. Skipping...
Chunk 379 does not have enough neighbors. Skipping...
Chunk 421 does not have enough neighbors. Skipping...
Chunk 804 does not have enough neighbors. Skipping...
Chunk 1016 does not have enough neighbors. Skipping...
Chunk 1491 does not have enough neighbors. Skipping...
Chunk 1754 does not have enough neighbors. Skipping...
Chunk 1889 does not have enough neighbors. Skipping...
Chunk 1928 does not have enough neighbors. Skipping...
Chunk 1990 does not have enough neighbors. Skipping...
Chunk 2070 does not have enough neighbors. Skipping...
Chunk 2094 does not have enough neighbors. Skipping...
Chunk 2146 does not have enough neighbors. Skipping...
Chunk 2259 does not have enough neighbors. Skipping...
Chunk 2383 does not have enough neighbors. Skipping...
Chunk 2413 does not have enough neighbors. Skipping...
9_pbmc_unsorted_3k

AnnData object with n_obs × n_vars = 2413 × 13000
    obs: 'group', 'cell_type', 'batch', 'Garfield_cluster', 'silhouette_temp', 'Multigrate_cluster', 'MultiVI_cluster', 'MOFA_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'MultiVI', 'MultiVI_cluster', 'MOFA', 'MOFA_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'MultiVI_distances', 'MultiVI_connectivities', 'MOFA_distances', 'MOFA_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [7]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '9_pbmc_unsorted_3k'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.698596,0.559999,0.755856,0.958354,0.507223,Garfield,9_pbmc_unsorted_3k
1,0.270386,0.505980,0.513119,0.879847,0.503597,Multigrate,9_pbmc_unsorted_3k
2,0.486626,0.707436,0.729399,0.993246,0.658809,MultiVI,9_pbmc_unsorted_3k
3,0.519998,0.608050,0.674235,0.981996,0.575843,MOFA,9_pbmc_unsorted_3k
4,0.626682,0.795544,0.779000,0.997477,0.702561,Seurat,9_pbmc_unsorted_3k

### 数据集 8_pbmc_unsorted_10k

In [12]:
## 记录resolution
reso_dict = {
    '8_pbmc_unsorted_10k': {
        'Garfield': 0.66,
        'Multigrate': 1.750000000000001,
        'MultiVI': 0.45,
        'MOFA': 0.8000000000000003,
        'Seurat': 0.14121476824050008, 
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('8_pbmc_unsorted_10k', reso_dict=reso_dict)
adata

the length of cell type: 17
method_reso is not None, using the 0.66 as resolution for Garfield...
Number of clusters: 17
the length of cell type: 17
Searching resolution for Multigrate...
Searching resolution...
resolution=1.9500000000000013, cluster number=18
resolution=1.9000000000000012, cluster number=18
resolution=1.8500000000000012, cluster number=18
resolution=1.8000000000000012, cluster number=18
resolution=1.750000000000001, cluster number=17
Number of clusters: 17
the length of cell type: 17
Searching resolution for MultiVI...
Searching resolution...
resolution=1.9500000000000013, cluster number=44
resolution=1.9000000000000012, cluster number=42
resolution=1.8500000000000012, cluster number=42
resolution=1.8000000000000012, cluster number=40
resolution=1.750000000000001, cluster number=40
resolution=1.700000000000001, cluster number=42
resolution=1.650000000000001, cluster number=41
resolution=1.600000000000001, cluster number=41
resolution=1.550000000000001, cluster number=39
resolution=1.5000000000000009, cluster number=38
resolution=1.4500000000000008, cluster number=38
resolution=1.4000000000000008, cluster number=35
resolution=1.3500000000000008, cluster number=34
resolution=1.3000000000000007, cluster number=34
resolution=1.2500000000000007, cluster number=33
resolution=1.2000000000000006, cluster number=34
resolution=1.1500000000000006, cluster number=30
resolution=1.1000000000000005, cluster number=31
resolution=1.0500000000000005, cluster number=31
resolution=1.0000000000000004, cluster number=29
resolution=0.9500000000000004, cluster number=27
resolution=0.9000000000000004, cluster number=27
resolution=0.8500000000000003, cluster number=29
resolution=0.8000000000000003, cluster number=27
resolution=0.7500000000000002, cluster number=25
resolution=0.7000000000000002, cluster number=24
resolution=0.6500000000000001, cluster number=22
resolution=0.6000000000000001, cluster number=20
resolution=0.55, cluster number=20
resolution=0.5, cluster number=19
Expanding search range: new range (0.45, 0.7875)
resolution=0.75, cluster number=25
resolution=0.7, cluster number=24
resolution=0.6499999999999999, cluster number=22
resolution=0.6, cluster number=20
resolution=0.55, cluster number=20
resolution=0.5, cluster number=19
resolution=0.45, cluster number=17
Number of clusters: 17
the length of cell type: 17
Searching resolution for MOFA...
Searching resolution...
resolution=1.9500000000000013, cluster number=31
resolution=1.9000000000000012, cluster number=28
resolution=1.8500000000000012, cluster number=27
resolution=1.8000000000000012, cluster number=29
resolution=1.750000000000001, cluster number=29
resolution=1.700000000000001, cluster number=27
resolution=1.650000000000001, cluster number=25
resolution=1.600000000000001, cluster number=24
resolution=1.550000000000001, cluster number=25
resolution=1.5000000000000009, cluster number=26
resolution=1.4500000000000008, cluster number=25
resolution=1.4000000000000008, cluster number=24
resolution=1.3500000000000008, cluster number=23
resolution=1.3000000000000007, cluster number=24
resolution=1.2500000000000007, cluster number=24
resolution=1.2000000000000006, cluster number=23
resolution=1.1500000000000006, cluster number=20
resolution=1.1000000000000005, cluster number=20
resolution=1.0500000000000005, cluster number=20
resolution=1.0000000000000004, cluster number=20
resolution=0.9500000000000004, cluster number=19
resolution=0.9000000000000004, cluster number=18
resolution=0.8500000000000003, cluster number=19
resolution=0.8000000000000003, cluster number=17
Number of clusters: 17
the length of cell type: 17
Searching resolution for Seurat...
Searching resolution...
resolution=1.9500000000000013, cluster number=74
resolution=1.9000000000000012, cluster number=76
resolution=1.8500000000000012, cluster number=72
resolution=1.8000000000000012, cluster number=68
resolution=1.750000000000001, cluster number=68
resolution=1.700000000000001, cluster number=67
resolution=1.650000000000001, cluster number=67
resolution=1.600000000000001, cluster number=68
resolution=1.550000000000001, cluster number=65
resolution=1.5000000000000009, cluster number=59
resolution=1.4500000000000008, cluster number=60
resolution=1.4000000000000008, cluster number=60
resolution=1.3500000000000008, cluster number=56
resolution=1.3000000000000007, cluster number=54
resolution=1.2500000000000007, cluster number=53
resolution=1.2000000000000006, cluster number=54
resolution=1.1500000000000006, cluster number=51
resolution=1.1000000000000005, cluster number=51
resolution=1.0500000000000005, cluster number=49
resolution=1.0000000000000004, cluster number=49
resolution=0.9500000000000004, cluster number=46
resolution=0.9000000000000004, cluster number=42
resolution=0.8500000000000003, cluster number=42
resolution=0.8000000000000003, cluster number=41
resolution=0.7500000000000002, cluster number=38
resolution=0.7000000000000002, cluster number=39
resolution=0.6500000000000001, cluster number=35
resolution=0.6000000000000001, cluster number=33
resolution=0.55, cluster number=34
resolution=0.5, cluster number=33
Expanding search range: new range (0.45, 0.7875)
resolution=0.75, cluster number=38
resolution=0.7, cluster number=39
resolution=0.6499999999999999, cluster number=35
resolution=0.6, cluster number=33
resolution=0.55, cluster number=34
resolution=0.5, cluster number=33
resolution=0.45, cluster number=30
Expanding search range: new range (0.405, 0.70875)
resolution=0.705, cluster number=37
resolution=0.655, cluster number=37
resolution=0.605, cluster number=33
resolution=0.5549999999999999, cluster number=34
resolution=0.505, cluster number=33
resolution=0.455, cluster number=30
resolution=0.405, cluster number=29
Expanding search range: new range (0.36450000000000005, 0.6378750000000001)
resolution=0.6145, cluster number=33
resolution=0.5645, cluster number=34
resolution=0.5145, cluster number=32
resolution=0.4645, cluster number=33
resolution=0.41450000000000004, cluster number=29
resolution=0.36450000000000005, cluster number=26
Expanding search range: new range (0.32805000000000006, 0.5740875000000001)
resolution=0.52805, cluster number=33
resolution=0.47805000000000003, cluster number=32
resolution=0.42805000000000004, cluster number=29
resolution=0.37805000000000005, cluster number=26
resolution=0.32805000000000006, cluster number=23
Expanding search range: new range (0.2952450000000001, 0.5166787500000002)
resolution=0.49524500000000005, cluster number=33
resolution=0.44524500000000006, cluster number=30
resolution=0.39524500000000007, cluster number=28
resolution=0.3452450000000001, cluster number=26
resolution=0.2952450000000001, cluster number=24
Expanding search range: new range (0.2657205000000001, 0.46501087500000016)
resolution=0.41572050000000005, cluster number=29
resolution=0.36572050000000006, cluster number=26
resolution=0.31572050000000007, cluster number=24
resolution=0.2657205000000001, cluster number=23
Expanding search range: new range (0.23914845000000007, 0.4185097875000001)
resolution=0.38914845000000003, cluster number=29
resolution=0.33914845000000005, cluster number=26
resolution=0.28914845000000006, cluster number=23
resolution=0.23914845000000007, cluster number=23
Expanding search range: new range (0.21523360500000008, 0.37665880875000013)
resolution=0.3652336050000001, cluster number=26
resolution=0.3152336050000001, cluster number=24
resolution=0.2652336050000001, cluster number=23
resolution=0.21523360500000008, cluster number=22
Expanding search range: new range (0.19371024450000007, 0.3389929278750001)
resolution=0.29371024450000005, cluster number=24
resolution=0.24371024450000006, cluster number=21
resolution=0.19371024450000007, cluster number=20
Expanding search range: new range (0.17433922005000008, 0.30509363508750015)
resolution=0.27433922005000005, cluster number=24
resolution=0.22433922005000007, cluster number=22
resolution=0.17433922005000008, cluster number=19
Expanding search range: new range (0.15690529804500009, 0.27458427157875015)
resolution=0.25690529804500006, cluster number=23
resolution=0.20690529804500007, cluster number=20
resolution=0.15690529804500009, cluster number=18
Expanding search range: new range (0.14121476824050008, 0.24712584442087515)
resolution=0.24121476824050012, cluster number=23
resolution=0.1912147682405001, cluster number=20
resolution=0.14121476824050008, cluster number=17
Number of clusters: 17
Chunk 81 does not have enough neighbors. Skipping...
Chunk 148 does not have enough neighbors. Skipping...
Chunk 201 does not have enough neighbors. Skipping...
Chunk 227 does not have enough neighbors. Skipping...
Chunk 346 does not have enough neighbors. Skipping...
Chunk 409 does not have enough neighbors. Skipping...
Chunk 538 does not have enough neighbors. Skipping...
Chunk 635 does not have enough neighbors. Skipping...
Chunk 947 does not have enough neighbors. Skipping...
Chunk 1035 does not have enough neighbors. Skipping...
Chunk 1214 does not have enough neighbors. Skipping...
Chunk 1299 does not have enough neighbors. Skipping...
Chunk 1379 does not have enough neighbors. Skipping...
Chunk 1659 does not have enough neighbors. Skipping...
Chunk 1708 does not have enough neighbors. Skipping...
Chunk 1729 does not have enough neighbors. Skipping...
Chunk 1838 does not have enough neighbors. Skipping...
Chunk 2083 does not have enough neighbors. Skipping...
Chunk 2243 does not have enough neighbors. Skipping...
Chunk 2272 does not have enough neighbors. Skipping...
Chunk 2320 does not have enough neighbors. Skipping...
Chunk 2368 does not have enough neighbors. Skipping...
Chunk 2670 does not have enough neighbors. Skipping...
Chunk 2892 does not have enough neighbors. Skipping...
Chunk 2954 does not have enough neighbors. Skipping...
Chunk 3048 does not have enough neighbors. Skipping...
Chunk 3118 does not have enough neighbors. Skipping...
Chunk 3279 does not have enough neighbors. Skipping...
Chunk 3416 does not have enough neighbors. Skipping...
Chunk 3445 does not have enough neighbors. Skipping...
Chunk 3630 does not have enough neighbors. Skipping...
Chunk 3633 does not have enough neighbors. Skipping...
Chunk 3686 does not have enough neighbors. Skipping...
Chunk 3730 does not have enough neighbors. Skipping...
Chunk 3750 does not have enough neighbors. Skipping...
Chunk 3785 does not have enough neighbors. Skipping...
Chunk 4051 does not have enough neighbors. Skipping...
Chunk 4238 does not have enough neighbors. Skipping...
Chunk 4330 does not have enough neighbors. Skipping...
Chunk 4349 does not have enough neighbors. Skipping...
Chunk 4644 does not have enough neighbors. Skipping...
Chunk 4648 does not have enough neighbors. Skipping...
Chunk 4799 does not have enough neighbors. Skipping...
Chunk 4812 does not have enough neighbors. Skipping...
Chunk 5172 does not have enough neighbors. Skipping...
Chunk 5336 does not have enough neighbors. Skipping...
Chunk 5376 does not have enough neighbors. Skipping...
Chunk 5602 does not have enough neighbors. Skipping...
Chunk 5792 does not have enough neighbors. Skipping...
Chunk 5814 does not have enough neighbors. Skipping...
Chunk 6035 does not have enough neighbors. Skipping...
Chunk 6061 does not have enough neighbors. Skipping...
Chunk 6166 does not have enough neighbors. Skipping...
Chunk 6250 does not have enough neighbors. Skipping...
Chunk 6353 does not have enough neighbors. Skipping...
Chunk 6531 does not have enough neighbors. Skipping...
Chunk 6567 does not have enough neighbors. Skipping...
Chunk 6592 does not have enough neighbors. Skipping...
Chunk 6692 does not have enough neighbors. Skipping...
Chunk 6731 does not have enough neighbors. Skipping...
Chunk 6915 does not have enough neighbors. Skipping...
Chunk 6989 does not have enough neighbors. Skipping...
Chunk 7050 does not have enough neighbors. Skipping...
Chunk 7194 does not have enough neighbors. Skipping...
Chunk 7205 does not have enough neighbors. Skipping...
Chunk 7404 does not have enough neighbors. Skipping...
Chunk 7506 does not have enough neighbors. Skipping...
Chunk 7512 does not have enough neighbors. Skipping...
Chunk 7592 does not have enough neighbors. Skipping...
Chunk 7797 does not have enough neighbors. Skipping...
Chunk 7808 does not have enough neighbors. Skipping...
Chunk 7840 does not have enough neighbors. Skipping...
Chunk 7992 does not have enough neighbors. Skipping...
8_pbmc_unsorted_10k

AnnData object with n_obs × n_vars = 8105 × 13000
    obs: 'group', 'cell_type', 'batch', 'Garfield_cluster', 'silhouette_temp', 'Multigrate_cluster', 'MultiVI_cluster', 'MOFA_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'MultiVI', 'MultiVI_cluster', 'MOFA', 'MOFA_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'MultiVI_distances', 'MultiVI_connectivities', 'MOFA_distances', 'MOFA_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [13]:
import matplotlib.pyplot as plt

dataset = '8_pbmc_unsorted_10k'
res_dir = f'/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC/{dataset}'

latent_key_list = ['Garfield', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat']
for latent_key in latent_key_list:
    sc.tl.umap(adata, neighbors_key=latent_key)
    latent_key_cluster = latent_key + '_cluster'
    
    # Create a new figure for each plot with an appropriate size
    plt.figure(figsize=(12, 6))  # Adjust the figsize as needed
    sc.pl.umap(adata, color=['cell_type', latent_key_cluster], wspace=0.5, hspace=0.5, show=False, ncols=2)
    # Save the figure
    plt.savefig(res_dir + f"/{latent_key}_UMAP_clusters.png", bbox_inches='tight')  # Use bbox_inches to ensure full legend display
    plt.close()

In [14]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '8_pbmc_unsorted_10k'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.493298,0.599320,0.718748,0.989912,0.563205,Garfield,8_pbmc_unsorted_10k
1,0.448551,0.562592,0.703769,0.984360,0.535793,Multigrate,8_pbmc_unsorted_10k
2,0.409304,0.635573,0.679667,0.991242,0.579317,MultiVI,8_pbmc_unsorted_10k
3,0.433904,0.610499,0.705069,0.988027,0.574253,MOFA,8_pbmc_unsorted_10k
4,0.428831,0.635575,0.687655,0.990538,0.594528,Seurat,8_pbmc_unsorted_10k

#### 使用默认固定的resolution

In [13]:
# calculate the metrics based on the best resolution
adata = count_metrics_for_best_resolution('8_pbmc_unsorted_10k')
adata

Chunk 81 does not have enough neighbors. Skipping...
Chunk 148 does not have enough neighbors. Skipping...
Chunk 201 does not have enough neighbors. Skipping...
Chunk 227 does not have enough neighbors. Skipping...
Chunk 346 does not have enough neighbors. Skipping...
Chunk 409 does not have enough neighbors. Skipping...
Chunk 538 does not have enough neighbors. Skipping...
Chunk 635 does not have enough neighbors. Skipping...
Chunk 947 does not have enough neighbors. Skipping...
Chunk 1035 does not have enough neighbors. Skipping...
Chunk 1214 does not have enough neighbors. Skipping...
Chunk 1299 does not have enough neighbors. Skipping...
Chunk 1379 does not have enough neighbors. Skipping...
Chunk 1659 does not have enough neighbors. Skipping...
Chunk 1708 does not have enough neighbors. Skipping...
Chunk 1729 does not have enough neighbors. Skipping...
Chunk 1838 does not have enough neighbors. Skipping...
Chunk 2083 does not have enough neighbors. Skipping...
Chunk 2243 does not have enough neighbors. Skipping...
Chunk 2272 does not have enough neighbors. Skipping...
Chunk 2320 does not have enough neighbors. Skipping...
Chunk 2368 does not have enough neighbors. Skipping...
Chunk 2670 does not have enough neighbors. Skipping...
Chunk 2892 does not have enough neighbors. Skipping...
Chunk 2954 does not have enough neighbors. Skipping...
Chunk 3048 does not have enough neighbors. Skipping...
Chunk 3118 does not have enough neighbors. Skipping...
Chunk 3279 does not have enough neighbors. Skipping...
Chunk 3416 does not have enough neighbors. Skipping...
Chunk 3445 does not have enough neighbors. Skipping...
Chunk 3630 does not have enough neighbors. Skipping...
Chunk 3633 does not have enough neighbors. Skipping...
Chunk 3686 does not have enough neighbors. Skipping...
Chunk 3730 does not have enough neighbors. Skipping...
Chunk 3750 does not have enough neighbors. Skipping...
Chunk 3785 does not have enough neighbors. Skipping...
Chunk 4051 does not have enough neighbors. Skipping...
Chunk 4238 does not have enough neighbors. Skipping...
Chunk 4330 does not have enough neighbors. Skipping...
Chunk 4349 does not have enough neighbors. Skipping...
Chunk 4644 does not have enough neighbors. Skipping...
Chunk 4648 does not have enough neighbors. Skipping...
Chunk 4799 does not have enough neighbors. Skipping...
Chunk 4812 does not have enough neighbors. Skipping...
Chunk 5172 does not have enough neighbors. Skipping...
Chunk 5336 does not have enough neighbors. Skipping...
Chunk 5376 does not have enough neighbors. Skipping...
Chunk 5602 does not have enough neighbors. Skipping...
Chunk 5792 does not have enough neighbors. Skipping...
Chunk 5814 does not have enough neighbors. Skipping...
Chunk 6035 does not have enough neighbors. Skipping...
Chunk 6061 does not have enough neighbors. Skipping...
Chunk 6166 does not have enough neighbors. Skipping...
Chunk 6250 does not have enough neighbors. Skipping...
Chunk 6353 does not have enough neighbors. Skipping...
Chunk 6531 does not have enough neighbors. Skipping...
Chunk 6567 does not have enough neighbors. Skipping...
Chunk 6592 does not have enough neighbors. Skipping...
Chunk 6692 does not have enough neighbors. Skipping...
Chunk 6731 does not have enough neighbors. Skipping...
Chunk 6915 does not have enough neighbors. Skipping...
Chunk 6989 does not have enough neighbors. Skipping...
Chunk 7050 does not have enough neighbors. Skipping...
Chunk 7194 does not have enough neighbors. Skipping...
Chunk 7205 does not have enough neighbors. Skipping...
Chunk 7404 does not have enough neighbors. Skipping...
Chunk 7506 does not have enough neighbors. Skipping...
Chunk 7512 does not have enough neighbors. Skipping...
Chunk 7592 does not have enough neighbors. Skipping...
Chunk 7797 does not have enough neighbors. Skipping...
Chunk 7808 does not have enough neighbors. Skipping...
Chunk 7840 does not have enough neighbors. Skipping...
Chunk 7992 does not have enough neighbors. Skipping...
8_pbmc_unsorted_10k

AnnData object with n_obs × n_vars = 8105 × 13000
    obs: 'group', 'cell_type', 'batch', 'cluster', 'silhouette_temp'
    var: 'modality'
    uns: 'modality_lengths', 'neighbors', 'umap', 'cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'distances', 'connectivities'

In [14]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '8_pbmc_unsorted_10k'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result_stable_reso.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.387091,0.599320,0.689900,0.989912,0.563205,Garfield,8_pbmc_unsorted_10k
1,0.497786,0.562592,0.713214,0.984360,0.535793,Multigrate,8_pbmc_unsorted_10k
2,0.272640,0.635573,0.641279,0.991242,0.579317,MultiVI,8_pbmc_unsorted_10k
3,0.406799,0.610499,0.690732,0.988027,0.574253,MOFA,8_pbmc_unsorted_10k
4,0.177652,0.635575,0.597946,0.990538,0.594528,Seurat,8_pbmc_unsorted_10k

#### 利用最佳分辨率计算指标(Garfield);

In [8]:
## 记录resolution
reso_dict = {
    '8_pbmc_unsorted_10k': {
        'Garfield': 0.2, #  0.66,
        'Multigrate': 1.750000000000001,
        'MultiVI': 0.45,
        'MOFA': 0.8000000000000003,
        'Seurat': 0.14121476824050008, 
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('8_pbmc_unsorted_10k', reso_dict=reso_dict)
adata

the length of cell type: 17
method_reso is not None, using the 0.2 as resolution for Garfield...
Number of clusters: 10
the length of cell type: 17
method_reso is not None, using the 1.750000000000001 as resolution for Multigrate...
Number of clusters: 17
the length of cell type: 17
method_reso is not None, using the 0.45 as resolution for MultiVI...
Number of clusters: 17
the length of cell type: 17
method_reso is not None, using the 0.8000000000000003 as resolution for MOFA...
Number of clusters: 17
the length of cell type: 17
method_reso is not None, using the 0.14121476824050008 as resolution for Seurat...
Number of clusters: 17
Chunk 81 does not have enough neighbors. Skipping...
Chunk 148 does not have enough neighbors. Skipping...
Chunk 201 does not have enough neighbors. Skipping...
Chunk 227 does not have enough neighbors. Skipping...
Chunk 346 does not have enough neighbors. Skipping...
Chunk 409 does not have enough neighbors. Skipping...
Chunk 538 does not have enough neighbors. Skipping...
Chunk 635 does not have enough neighbors. Skipping...
Chunk 947 does not have enough neighbors. Skipping...
Chunk 1035 does not have enough neighbors. Skipping...
Chunk 1214 does not have enough neighbors. Skipping...
Chunk 1299 does not have enough neighbors. Skipping...
Chunk 1379 does not have enough neighbors. Skipping...
Chunk 1659 does not have enough neighbors. Skipping...
Chunk 1708 does not have enough neighbors. Skipping...
Chunk 1729 does not have enough neighbors. Skipping...
Chunk 1838 does not have enough neighbors. Skipping...
Chunk 2083 does not have enough neighbors. Skipping...
Chunk 2243 does not have enough neighbors. Skipping...
Chunk 2272 does not have enough neighbors. Skipping...
Chunk 2320 does not have enough neighbors. Skipping...
Chunk 2368 does not have enough neighbors. Skipping...
Chunk 2670 does not have enough neighbors. Skipping...
Chunk 2892 does not have enough neighbors. Skipping...
Chunk 2954 does not have enough neighbors. Skipping...
Chunk 3048 does not have enough neighbors. Skipping...
Chunk 3118 does not have enough neighbors. Skipping...
Chunk 3279 does not have enough neighbors. Skipping...
Chunk 3416 does not have enough neighbors. Skipping...
Chunk 3445 does not have enough neighbors. Skipping...
Chunk 3630 does not have enough neighbors. Skipping...
Chunk 3633 does not have enough neighbors. Skipping...
Chunk 3686 does not have enough neighbors. Skipping...
Chunk 3730 does not have enough neighbors. Skipping...
Chunk 3750 does not have enough neighbors. Skipping...
Chunk 3785 does not have enough neighbors. Skipping...
Chunk 4051 does not have enough neighbors. Skipping...
Chunk 4238 does not have enough neighbors. Skipping...
Chunk 4330 does not have enough neighbors. Skipping...
Chunk 4349 does not have enough neighbors. Skipping...
Chunk 4644 does not have enough neighbors. Skipping...
Chunk 4648 does not have enough neighbors. Skipping...
Chunk 4799 does not have enough neighbors. Skipping...
Chunk 4812 does not have enough neighbors. Skipping...
Chunk 5172 does not have enough neighbors. Skipping...
Chunk 5336 does not have enough neighbors. Skipping...
Chunk 5376 does not have enough neighbors. Skipping...
Chunk 5602 does not have enough neighbors. Skipping...
Chunk 5792 does not have enough neighbors. Skipping...
Chunk 5814 does not have enough neighbors. Skipping...
Chunk 6035 does not have enough neighbors. Skipping...
Chunk 6061 does not have enough neighbors. Skipping...
Chunk 6166 does not have enough neighbors. Skipping...
Chunk 6250 does not have enough neighbors. Skipping...
Chunk 6353 does not have enough neighbors. Skipping...
Chunk 6531 does not have enough neighbors. Skipping...
Chunk 6567 does not have enough neighbors. Skipping...
Chunk 6592 does not have enough neighbors. Skipping...
Chunk 6692 does not have enough neighbors. Skipping...
Chunk 6731 does not have enough neighbors. Skipping...
Chunk 6915 does not have enough neighbors. Skipping...
Chunk 6989 does not have enough neighbors. Skipping...
Chunk 7050 does not have enough neighbors. Skipping...
Chunk 7194 does not have enough neighbors. Skipping...
Chunk 7205 does not have enough neighbors. Skipping...
Chunk 7404 does not have enough neighbors. Skipping...
Chunk 7506 does not have enough neighbors. Skipping...
Chunk 7512 does not have enough neighbors. Skipping...
Chunk 7592 does not have enough neighbors. Skipping...
Chunk 7797 does not have enough neighbors. Skipping...
Chunk 7808 does not have enough neighbors. Skipping...
Chunk 7840 does not have enough neighbors. Skipping...
Chunk 7992 does not have enough neighbors. Skipping...
8_pbmc_unsorted_10k

AnnData object with n_obs × n_vars = 8105 × 13000
    obs: 'group', 'cell_type', 'batch', 'Garfield_cluster', 'silhouette_temp', 'Multigrate_cluster', 'MultiVI_cluster', 'MOFA_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'MultiVI', 'MultiVI_cluster', 'MOFA', 'MOFA_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'MultiVI_distances', 'MultiVI_connectivities', 'MOFA_distances', 'MOFA_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [9]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '8_pbmc_unsorted_10k'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.680520,0.599320,0.754724,0.989912,0.563205,Garfield,8_pbmc_unsorted_10k
1,0.448551,0.562592,0.703769,0.984360,0.535793,Multigrate,8_pbmc_unsorted_10k
2,0.409304,0.635573,0.679667,0.991242,0.579317,MultiVI,8_pbmc_unsorted_10k
3,0.433904,0.610499,0.705069,0.988027,0.574253,MOFA,8_pbmc_unsorted_10k
4,0.428831,0.635575,0.687655,0.990538,0.594528,Seurat,8_pbmc_unsorted_10k

### 数据集 7_human_pbmc_10x

In [6]:
## 记录resolution
reso_dict = {
    '7_human_pbmc_10x': {
        'Garfield': 0.405,
        'Multigrate': 1.550000000000001,
        'MultiVI': 0.17433922005000008,
        'MOFA': 0.32805000000000006,
        'Seurat': 0.08338590849833288, 
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('7_human_pbmc_10x', reso_dict=None)
adata

the length of cell type: 10
Searching resolution for Garfield...
Searching resolution...
resolution=1.9500000000000013, cluster number=23
resolution=1.9000000000000012, cluster number=22
resolution=1.8500000000000012, cluster number=22
resolution=1.8000000000000012, cluster number=22
resolution=1.750000000000001, cluster number=22
resolution=1.700000000000001, cluster number=20
resolution=1.650000000000001, cluster number=20
resolution=1.600000000000001, cluster number=19
resolution=1.550000000000001, cluster number=20
resolution=1.5000000000000009, cluster number=20
resolution=1.4500000000000008, cluster number=20
resolution=1.4000000000000008, cluster number=19
resolution=1.3500000000000008, cluster number=19
resolution=1.3000000000000007, cluster number=19
resolution=1.2500000000000007, cluster number=19
resolution=1.2000000000000006, cluster number=17
resolution=1.1500000000000006, cluster number=16
resolution=1.1000000000000005, cluster number=16
resolution=1.0500000000000005, cluster number=16
resolution=1.0000000000000004, cluster number=15
resolution=0.9500000000000004, cluster number=15
resolution=0.9000000000000004, cluster number=16
resolution=0.8500000000000003, cluster number=16
resolution=0.8000000000000003, cluster number=15
resolution=0.7500000000000002, cluster number=15
resolution=0.7000000000000002, cluster number=14
resolution=0.6500000000000001, cluster number=12
resolution=0.6000000000000001, cluster number=12
resolution=0.55, cluster number=12
resolution=0.5, cluster number=12
Expanding search range: new range (0.45, 0.7875)
resolution=0.75, cluster number=15
resolution=0.7, cluster number=14
resolution=0.6499999999999999, cluster number=12
resolution=0.6, cluster number=12
resolution=0.55, cluster number=12
resolution=0.5, cluster number=12
resolution=0.45, cluster number=12
Expanding search range: new range (0.405, 0.70875)
resolution=0.705, cluster number=14
resolution=0.655, cluster number=13
resolution=0.605, cluster number=12
resolution=0.5549999999999999, cluster number=12
resolution=0.505, cluster number=12
resolution=0.455, cluster number=11
resolution=0.405, cluster number=10
Number of clusters: 10
the length of cell type: 10
Searching resolution for Multigrate...
Searching resolution...
resolution=1.9500000000000013, cluster number=15
resolution=1.9000000000000012, cluster number=14
resolution=1.8500000000000012, cluster number=13
resolution=1.8000000000000012, cluster number=13
resolution=1.750000000000001, cluster number=13
resolution=1.700000000000001, cluster number=12
resolution=1.650000000000001, cluster number=12
resolution=1.600000000000001, cluster number=12
resolution=1.550000000000001, cluster number=10
Number of clusters: 10
the length of cell type: 10
Searching resolution for MultiVI...
Searching resolution...
resolution=1.9500000000000013, cluster number=30
resolution=1.9000000000000012, cluster number=30
resolution=1.8500000000000012, cluster number=28
resolution=1.8000000000000012, cluster number=29
resolution=1.750000000000001, cluster number=28
resolution=1.700000000000001, cluster number=28
resolution=1.650000000000001, cluster number=27
resolution=1.600000000000001, cluster number=26
resolution=1.550000000000001, cluster number=25
resolution=1.5000000000000009, cluster number=25
resolution=1.4500000000000008, cluster number=24
resolution=1.4000000000000008, cluster number=23
resolution=1.3500000000000008, cluster number=24
resolution=1.3000000000000007, cluster number=22
resolution=1.2500000000000007, cluster number=22
resolution=1.2000000000000006, cluster number=24
resolution=1.1500000000000006, cluster number=24
resolution=1.1000000000000005, cluster number=23
resolution=1.0500000000000005, cluster number=22
resolution=1.0000000000000004, cluster number=20
resolution=0.9500000000000004, cluster number=19
resolution=0.9000000000000004, cluster number=18
resolution=0.8500000000000003, cluster number=19
resolution=0.8000000000000003, cluster number=18
resolution=0.7500000000000002, cluster number=18
resolution=0.7000000000000002, cluster number=16
resolution=0.6500000000000001, cluster number=16
resolution=0.6000000000000001, cluster number=15
resolution=0.55, cluster number=15
resolution=0.5, cluster number=15
Expanding search range: new range (0.45, 0.7875)
resolution=0.75, cluster number=18
resolution=0.7, cluster number=16
resolution=0.6499999999999999, cluster number=16
resolution=0.6, cluster number=15
resolution=0.55, cluster number=15
resolution=0.5, cluster number=15
resolution=0.45, cluster number=13
Expanding search range: new range (0.405, 0.70875)
resolution=0.705, cluster number=16
resolution=0.655, cluster number=16
resolution=0.605, cluster number=15
resolution=0.5549999999999999, cluster number=14
resolution=0.505, cluster number=15
resolution=0.455, cluster number=13
resolution=0.405, cluster number=13
Expanding search range: new range (0.36450000000000005, 0.6378750000000001)
resolution=0.6145, cluster number=15
resolution=0.5645, cluster number=15
resolution=0.5145, cluster number=15
resolution=0.4645, cluster number=12
resolution=0.41450000000000004, cluster number=13
resolution=0.36450000000000005, cluster number=12
Expanding search range: new range (0.32805000000000006, 0.5740875000000001)
resolution=0.52805, cluster number=16
resolution=0.47805000000000003, cluster number=12
resolution=0.42805000000000004, cluster number=13
resolution=0.37805000000000005, cluster number=12
resolution=0.32805000000000006, cluster number=11
Expanding search range: new range (0.2952450000000001, 0.5166787500000002)
resolution=0.49524500000000005, cluster number=15
resolution=0.44524500000000006, cluster number=13
resolution=0.39524500000000007, cluster number=13
resolution=0.3452450000000001, cluster number=12
resolution=0.2952450000000001, cluster number=11
Expanding search range: new range (0.2657205000000001, 0.46501087500000016)
resolution=0.41572050000000005, cluster number=13
resolution=0.36572050000000006, cluster number=12
resolution=0.31572050000000007, cluster number=11
resolution=0.2657205000000001, cluster number=11
Expanding search range: new range (0.23914845000000007, 0.4185097875000001)
resolution=0.38914845000000003, cluster number=13
resolution=0.33914845000000005, cluster number=11
resolution=0.28914845000000006, cluster number=11
resolution=0.23914845000000007, cluster number=12
Expanding search range: new range (0.21523360500000008, 0.37665880875000013)
resolution=0.3652336050000001, cluster number=12
resolution=0.3152336050000001, cluster number=11
resolution=0.2652336050000001, cluster number=11
resolution=0.21523360500000008, cluster number=9
Expanding search range: new range (0.19371024450000007, 0.3389929278750001)
resolution=0.29371024450000005, cluster number=11
resolution=0.24371024450000006, cluster number=12
resolution=0.19371024450000007, cluster number=9
Expanding search range: new range (0.17433922005000008, 0.30509363508750015)
resolution=0.27433922005000005, cluster number=11
resolution=0.22433922005000007, cluster number=12
resolution=0.17433922005000008, cluster number=10
Number of clusters: 10
the length of cell type: 10
Searching resolution for MOFA...
Searching resolution...
resolution=1.9500000000000013, cluster number=27
resolution=1.9000000000000012, cluster number=27
resolution=1.8500000000000012, cluster number=26
resolution=1.8000000000000012, cluster number=27
resolution=1.750000000000001, cluster number=27
resolution=1.700000000000001, cluster number=26
resolution=1.650000000000001, cluster number=26
resolution=1.600000000000001, cluster number=26
resolution=1.550000000000001, cluster number=25
resolution=1.5000000000000009, cluster number=25
resolution=1.4500000000000008, cluster number=25
resolution=1.4000000000000008, cluster number=24
resolution=1.3500000000000008, cluster number=23
resolution=1.3000000000000007, cluster number=22
resolution=1.2500000000000007, cluster number=23
resolution=1.2000000000000006, cluster number=22
resolution=1.1500000000000006, cluster number=21
resolution=1.1000000000000005, cluster number=19
resolution=1.0500000000000005, cluster number=19
resolution=1.0000000000000004, cluster number=19
resolution=0.9500000000000004, cluster number=17
resolution=0.9000000000000004, cluster number=16
resolution=0.8500000000000003, cluster number=15
resolution=0.8000000000000003, cluster number=15
resolution=0.7500000000000002, cluster number=15
resolution=0.7000000000000002, cluster number=13
resolution=0.6500000000000001, cluster number=13
resolution=0.6000000000000001, cluster number=14
resolution=0.55, cluster number=13
resolution=0.5, cluster number=13
Expanding search range: new range (0.45, 0.7875)
resolution=0.75, cluster number=15
resolution=0.7, cluster number=13
resolution=0.6499999999999999, cluster number=13
resolution=0.6, cluster number=14
resolution=0.55, cluster number=13
resolution=0.5, cluster number=13
resolution=0.45, cluster number=13
Expanding search range: new range (0.405, 0.70875)
resolution=0.705, cluster number=13
resolution=0.655, cluster number=13
resolution=0.605, cluster number=14
resolution=0.5549999999999999, cluster number=13
resolution=0.505, cluster number=13
resolution=0.455, cluster number=13
resolution=0.405, cluster number=12
Expanding search range: new range (0.36450000000000005, 0.6378750000000001)
resolution=0.6145, cluster number=14
resolution=0.5645, cluster number=13
resolution=0.5145, cluster number=14
resolution=0.4645, cluster number=12
resolution=0.41450000000000004, cluster number=12
resolution=0.36450000000000005, cluster number=11
Expanding search range: new range (0.32805000000000006, 0.5740875000000001)
resolution=0.52805, cluster number=13
resolution=0.47805000000000003, cluster number=13
resolution=0.42805000000000004, cluster number=12
resolution=0.37805000000000005, cluster number=11
resolution=0.32805000000000006, cluster number=10
Number of clusters: 10
Chunk 26 does not have enough neighbors. Skipping...
Chunk 136 does not have enough neighbors. Skipping...
Chunk 195 does not have enough neighbors. Skipping...
Chunk 216 does not have enough neighbors. Skipping...
Chunk 341 does not have enough neighbors. Skipping...
Chunk 359 does not have enough neighbors. Skipping...
Chunk 452 does not have enough neighbors. Skipping...
Chunk 497 does not have enough neighbors. Skipping...
Chunk 529 does not have enough neighbors. Skipping...
Chunk 565 does not have enough neighbors. Skipping...
Chunk 644 does not have enough neighbors. Skipping...
Chunk 820 does not have enough neighbors. Skipping...
Chunk 921 does not have enough neighbors. Skipping...
Chunk 1003 does not have enough neighbors. Skipping...
Chunk 1091 does not have enough neighbors. Skipping...
Chunk 1228 does not have enough neighbors. Skipping...
Chunk 1568 does not have enough neighbors. Skipping...
Chunk 1618 does not have enough neighbors. Skipping...
Chunk 1623 does not have enough neighbors. Skipping...
Chunk 1770 does not have enough neighbors. Skipping...
Chunk 1903 does not have enough neighbors. Skipping...
Chunk 1914 does not have enough neighbors. Skipping...
Chunk 1927 does not have enough neighbors. Skipping...
Chunk 2057 does not have enough neighbors. Skipping...
Chunk 2210 does not have enough neighbors. Skipping...
Chunk 2252 does not have enough neighbors. Skipping...
Chunk 2310 does not have enough neighbors. Skipping...
Chunk 2479 does not have enough neighbors. Skipping...
Chunk 2485 does not have enough neighbors. Skipping...
the length of cell type: 10
Searching resolution for Seurat...
Searching resolution...
resolution=1.9500000000000013, cluster number=45
resolution=1.9000000000000012, cluster number=43
resolution=1.8500000000000012, cluster number=44
resolution=1.8000000000000012, cluster number=43
resolution=1.750000000000001, cluster number=41
resolution=1.700000000000001, cluster number=44
resolution=1.650000000000001, cluster number=43
resolution=1.600000000000001, cluster number=41
resolution=1.550000000000001, cluster number=40
resolution=1.5000000000000009, cluster number=40
resolution=1.4500000000000008, cluster number=40
resolution=1.4000000000000008, cluster number=40
resolution=1.3500000000000008, cluster number=39
resolution=1.3000000000000007, cluster number=38
resolution=1.2500000000000007, cluster number=39
resolution=1.2000000000000006, cluster number=38
resolution=1.1500000000000006, cluster number=35
resolution=1.1000000000000005, cluster number=34
resolution=1.0500000000000005, cluster number=34
resolution=1.0000000000000004, cluster number=31
resolution=0.9500000000000004, cluster number=32
resolution=0.9000000000000004, cluster number=31
resolution=0.8500000000000003, cluster number=28
resolution=0.8000000000000003, cluster number=26
resolution=0.7500000000000002, cluster number=25
resolution=0.7000000000000002, cluster number=25
resolution=0.6500000000000001, cluster number=24
resolution=0.6000000000000001, cluster number=23
resolution=0.55, cluster number=23
resolution=0.5, cluster number=20
Expanding search range: new range (0.45, 0.7875)
resolution=0.75, cluster number=25
resolution=0.7, cluster number=25
resolution=0.6499999999999999, cluster number=24
resolution=0.6, cluster number=23
resolution=0.55, cluster number=23
resolution=0.5, cluster number=20
resolution=0.45, cluster number=21
Expanding search range: new range (0.405, 0.70875)
resolution=0.705, cluster number=25
resolution=0.655, cluster number=25
resolution=0.605, cluster number=23
resolution=0.5549999999999999, cluster number=23
resolution=0.505, cluster number=20
resolution=0.455, cluster number=21
resolution=0.405, cluster number=20
Expanding search range: new range (0.36450000000000005, 0.6378750000000001)
resolution=0.6145, cluster number=24
resolution=0.5645, cluster number=22
resolution=0.5145, cluster number=20
resolution=0.4645, cluster number=20
resolution=0.41450000000000004, cluster number=20
resolution=0.36450000000000005, cluster number=20
Expanding search range: new range (0.32805000000000006, 0.5740875000000001)
resolution=0.52805, cluster number=23
resolution=0.47805000000000003, cluster number=20
resolution=0.42805000000000004, cluster number=20
resolution=0.37805000000000005, cluster number=20
resolution=0.32805000000000006, cluster number=17
Expanding search range: new range (0.2952450000000001, 0.5166787500000002)
resolution=0.49524500000000005, cluster number=20
resolution=0.44524500000000006, cluster number=20
resolution=0.39524500000000007, cluster number=21
resolution=0.3452450000000001, cluster number=18
resolution=0.2952450000000001, cluster number=16
Expanding search range: new range (0.2657205000000001, 0.46501087500000016)
resolution=0.41572050000000005, cluster number=20
resolution=0.36572050000000006, cluster number=20
resolution=0.31572050000000007, cluster number=16
resolution=0.2657205000000001, cluster number=15
Expanding search range: new range (0.23914845000000007, 0.4185097875000001)
resolution=0.38914845000000003, cluster number=20
resolution=0.33914845000000005, cluster number=18
resolution=0.28914845000000006, cluster number=16
resolution=0.23914845000000007, cluster number=15
Expanding search range: new range (0.21523360500000008, 0.37665880875000013)
resolution=0.3652336050000001, cluster number=20
resolution=0.3152336050000001, cluster number=16
resolution=0.2652336050000001, cluster number=15
resolution=0.21523360500000008, cluster number=15
Expanding search range: new range (0.19371024450000007, 0.3389929278750001)
resolution=0.29371024450000005, cluster number=16
resolution=0.24371024450000006, cluster number=15
resolution=0.19371024450000007, cluster number=14
Expanding search range: new range (0.17433922005000008, 0.30509363508750015)
resolution=0.27433922005000005, cluster number=15
resolution=0.22433922005000007, cluster number=14
resolution=0.17433922005000008, cluster number=14
Expanding search range: new range (0.15690529804500009, 0.27458427157875015)
resolution=0.25690529804500006, cluster number=15
resolution=0.20690529804500007, cluster number=15
resolution=0.15690529804500009, cluster number=13
Expanding search range: new range (0.14121476824050008, 0.24712584442087515)
resolution=0.24121476824050012, cluster number=15
resolution=0.1912147682405001, cluster number=14
resolution=0.14121476824050008, cluster number=13
Expanding search range: new range (0.12709329141645007, 0.2224132599787876)
resolution=0.17709329141645008, cluster number=14
resolution=0.12709329141645007, cluster number=13
Expanding search range: new range (0.11438396227480506, 0.20017193398090885)
resolution=0.16438396227480506, cluster number=14
resolution=0.11438396227480506, cluster number=12
Expanding search range: new range (0.10294556604732455, 0.18015474058281797)
resolution=0.15294556604732457, cluster number=13
resolution=0.10294556604732455, cluster number=12
Expanding search range: new range (0.0926510094425921, 0.16213926652453617)
resolution=0.1426510094425921, cluster number=13
resolution=0.0926510094425921, cluster number=11
Expanding search range: new range (0.08338590849833288, 0.14592533987208256)
resolution=0.13338590849833287, cluster number=13
resolution=0.08338590849833288, cluster number=10
Number of clusters: 10
Chunk 26 does not have enough neighbors. Skipping...
Chunk 136 does not have enough neighbors. Skipping...
Chunk 195 does not have enough neighbors. Skipping...
Chunk 216 does not have enough neighbors. Skipping...
Chunk 341 does not have enough neighbors. Skipping...
Chunk 359 does not have enough neighbors. Skipping...
Chunk 452 does not have enough neighbors. Skipping...
Chunk 497 does not have enough neighbors. Skipping...
Chunk 529 does not have enough neighbors. Skipping...
Chunk 565 does not have enough neighbors. Skipping...
Chunk 644 does not have enough neighbors. Skipping...
Chunk 820 does not have enough neighbors. Skipping...
Chunk 921 does not have enough neighbors. Skipping...
Chunk 1003 does not have enough neighbors. Skipping...
Chunk 1091 does not have enough neighbors. Skipping...
Chunk 1228 does not have enough neighbors. Skipping...
Chunk 1568 does not have enough neighbors. Skipping...
Chunk 1618 does not have enough neighbors. Skipping...
Chunk 1623 does not have enough neighbors. Skipping...
Chunk 1770 does not have enough neighbors. Skipping...
Chunk 1903 does not have enough neighbors. Skipping...
Chunk 1914 does not have enough neighbors. Skipping...
Chunk 1927 does not have enough neighbors. Skipping...
Chunk 2057 does not have enough neighbors. Skipping...
Chunk 2210 does not have enough neighbors. Skipping...
Chunk 2252 does not have enough neighbors. Skipping...
Chunk 2310 does not have enough neighbors. Skipping...
Chunk 2479 does not have enough neighbors. Skipping...
Chunk 2485 does not have enough neighbors. Skipping...
7_human_pbmc_10x

AnnData object with n_obs × n_vars = 2592 × 13000
    obs: 'group', 'cell_type', 'batch', 'Garfield_cluster', 'silhouette_temp', 'Multigrate_cluster', 'MultiVI_cluster', 'MOFA_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'MultiVI', 'MultiVI_cluster', 'MOFA', 'MOFA_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'MultiVI_distances', 'MultiVI_connectivities', 'MOFA_distances', 'MOFA_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [7]:
import matplotlib.pyplot as plt

dataset = '7_human_pbmc_10x'
res_dir = f'/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC/{dataset}'

latent_key_list = ['Garfield', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat']
for latent_key in latent_key_list:
    sc.tl.umap(adata, neighbors_key=latent_key)
    latent_key_cluster = latent_key + '_cluster'
    
    # Create a new figure for each plot with an appropriate size
    plt.figure(figsize=(12, 6))  # Adjust the figsize as needed
    sc.pl.umap(adata, color=['cell_type', latent_key_cluster], wspace=0.5, hspace=0.5, show=False, ncols=2)
    # Save the figure
    plt.savefig(res_dir + f"/{latent_key}_UMAP_clusters.png", bbox_inches='tight')  # Use bbox_inches to ensure full legend display
    plt.close()

In [8]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '7_human_pbmc_10x'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.664271,0.689879,0.768072,0.989808,0.661599,Garfield,7_human_pbmc_10x
1,0.540047,0.565031,0.712995,0.930917,0.568089,Multigrate,7_human_pbmc_10x
2,0.791090,0.711974,0.820206,0.996757,0.648317,MultiVI,7_human_pbmc_10x
3,0.573762,0.678811,0.709448,0.984283,0.648767,MOFA,7_human_pbmc_10x
4,0.654868,0.796970,0.778771,0.996275,0.719270,Seurat,7_human_pbmc_10x

#### 探索一下用最佳分辨率

In [9]:
# calculate the metrics based on the best resolution
adata = count_metrics_for_best_resolution('7_human_pbmc_10x')
adata

WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.7548250486811503
resolution: 0.2, nmi: 0.7727208318775747
resolution: 0.3, nmi: 0.7766032905563575
resolution: 0.4, nmi: 0.7680720232818008
resolution: 0.5, nmi: 0.7414096358489178
resolution: 0.6, nmi: 0.7412102399731031
resolution: 0.7, nmi: 0.7313968635832362
resolution: 0.8, nmi: 0.7234353599305173
resolution: 0.9, nmi: 0.7126437547504965
resolution: 1.0, nmi: 0.7143406085174687
resolution: 1.1, nmi: 0.7132795202055161
resolution: 1.2, nmi: 0.7084406263403178
resolution: 1.3, nmi: 0.6887413344749832
resolution: 1.4, nmi: 0.6857555295772277
resolution: 1.5, nmi: 0.6824804655781431
resolution: 1.6, nmi: 0.685031497890369
resolution: 1.7, nmi: 0.6849403050743973
resolution: 1.8, nmi: 0.6793120458178192
resolution: 1.9, nmi: 0.6737338164869416
resolution: 2.0, nmi: 0.677368910577878
optimised clustering against cell_type
optimal cluster resolution: 0.3
optimal score: 0.7766032905563575
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.6988915760510876
resolution: 0.2, nmi: 0.7576971532507751
resolution: 0.3, nmi: 0.7613945020059358
resolution: 0.4, nmi: 0.7589756645807875
resolution: 0.5, nmi: 0.7618044980848426
resolution: 0.6, nmi: 0.7617621147315116
resolution: 0.7, nmi: 0.7153718292231213
resolution: 0.8, nmi: 0.7075668219559678
resolution: 0.9, nmi: 0.7181332647562388
resolution: 1.0, nmi: 0.7226312560658471
resolution: 1.1, nmi: 0.7222141197053551
resolution: 1.2, nmi: 0.7200706451901275
resolution: 1.3, nmi: 0.7207214069724589
resolution: 1.4, nmi: 0.7120346240536751
resolution: 1.5, nmi: 0.7007604304167545
resolution: 1.6, nmi: 0.6977705104051284
resolution: 1.7, nmi: 0.7006172281480391
resolution: 1.8, nmi: 0.6824824371200352
resolution: 1.9, nmi: 0.6601102171184449
resolution: 2.0, nmi: 0.6455628886157102
optimised clustering against cell_type
optimal cluster resolution: 0.5
optimal score: 0.7618044980848426
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.7625776260755992
resolution: 0.2, nmi: 0.8179023280491814
resolution: 0.3, nmi: 0.7906240025649138
resolution: 0.4, nmi: 0.7908144734765499
resolution: 0.5, nmi: 0.747267429557023
resolution: 0.6, nmi: 0.7477816758006333
resolution: 0.7, nmi: 0.7360187989699862
resolution: 0.8, nmi: 0.7243898706205243
resolution: 0.9, nmi: 0.7259695090642063
resolution: 1.0, nmi: 0.7082213824503073
resolution: 1.1, nmi: 0.6953599396280397
resolution: 1.2, nmi: 0.6866286464479174
resolution: 1.3, nmi: 0.6951654517244085
resolution: 1.4, nmi: 0.6867941469988442
resolution: 1.5, nmi: 0.6780558403224248
resolution: 1.6, nmi: 0.6786073570060592
resolution: 1.7, nmi: 0.6720238663665843
resolution: 1.8, nmi: 0.6685143995850873
resolution: 1.9, nmi: 0.6657515850000401
resolution: 2.0, nmi: 0.6744725585851267
optimised clustering against cell_type
optimal cluster resolution: 0.2
optimal score: 0.8179023280491814
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.7559946472064181
resolution: 0.2, nmi: 0.7250221103913331
resolution: 0.3, nmi: 0.7293866439081002
resolution: 0.4, nmi: 0.7106479706033272
resolution: 0.5, nmi: 0.7042909205435928
resolution: 0.6, nmi: 0.7115747930043036
resolution: 0.7, nmi: 0.7027477659663245
resolution: 0.8, nmi: 0.6906792462384703
resolution: 0.9, nmi: 0.6842381217222233
resolution: 1.0, nmi: 0.6746286164610907
resolution: 1.1, nmi: 0.6794971068492125
resolution: 1.2, nmi: 0.6602311181252248
resolution: 1.3, nmi: 0.6641746990221151
resolution: 1.4, nmi: 0.6492948807755126
resolution: 1.5, nmi: 0.6442975818212686
resolution: 1.6, nmi: 0.6375095134135397
resolution: 1.7, nmi: 0.6405112363578068
resolution: 1.8, nmi: 0.6415075970700671
resolution: 1.9, nmi: 0.6434871478970196
resolution: 2.0, nmi: 0.6427659917560156
optimised clustering against cell_type
optimal cluster resolution: 0.1
optimal score: 0.7559946472064181
Chunk 26 does not have enough neighbors. Skipping...
Chunk 136 does not have enough neighbors. Skipping...
Chunk 195 does not have enough neighbors. Skipping...
Chunk 216 does not have enough neighbors. Skipping...
Chunk 341 does not have enough neighbors. Skipping...
Chunk 359 does not have enough neighbors. Skipping...
Chunk 452 does not have enough neighbors. Skipping...
Chunk 497 does not have enough neighbors. Skipping...
Chunk 529 does not have enough neighbors. Skipping...
Chunk 565 does not have enough neighbors. Skipping...
Chunk 644 does not have enough neighbors. Skipping...
Chunk 820 does not have enough neighbors. Skipping...
Chunk 921 does not have enough neighbors. Skipping...
Chunk 1003 does not have enough neighbors. Skipping...
Chunk 1091 does not have enough neighbors. Skipping...
Chunk 1228 does not have enough neighbors. Skipping...
Chunk 1568 does not have enough neighbors. Skipping...
Chunk 1618 does not have enough neighbors. Skipping...
Chunk 1623 does not have enough neighbors. Skipping...
Chunk 1770 does not have enough neighbors. Skipping...
Chunk 1903 does not have enough neighbors. Skipping...
Chunk 1914 does not have enough neighbors. Skipping...
Chunk 1927 does not have enough neighbors. Skipping...
Chunk 2057 does not have enough neighbors. Skipping...
Chunk 2210 does not have enough neighbors. Skipping...
Chunk 2252 does not have enough neighbors. Skipping...
Chunk 2310 does not have enough neighbors. Skipping...
Chunk 2479 does not have enough neighbors. Skipping...
Chunk 2485 does not have enough neighbors. Skipping...
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.7495137583415105
resolution: 0.2, nmi: 0.7634962907772535
resolution: 0.3, nmi: 0.7455675606560643
resolution: 0.4, nmi: 0.7093279146879223
resolution: 0.5, nmi: 0.7012280096377296
resolution: 0.6, nmi: 0.7013574235070011
resolution: 0.7, nmi: 0.686186717097471
resolution: 0.8, nmi: 0.6834352513348859
resolution: 0.9, nmi: 0.6605602355702614
resolution: 1.0, nmi: 0.664750163039799
resolution: 1.1, nmi: 0.6538168732138814
resolution: 1.2, nmi: 0.6405328408273612
resolution: 1.3, nmi: 0.636827077060537
resolution: 1.4, nmi: 0.6368800539572737
resolution: 1.5, nmi: 0.6322040215676917
resolution: 1.6, nmi: 0.6318729297554846
resolution: 1.7, nmi: 0.6253677449991242
resolution: 1.8, nmi: 0.6242319940999657
resolution: 1.9, nmi: 0.6272539453052468
resolution: 2.0, nmi: 0.622390982814109
optimised clustering against cell_type
optimal cluster resolution: 0.2
optimal score: 0.7634962907772535
Chunk 26 does not have enough neighbors. Skipping...
Chunk 136 does not have enough neighbors. Skipping...
Chunk 195 does not have enough neighbors. Skipping...
Chunk 216 does not have enough neighbors. Skipping...
Chunk 341 does not have enough neighbors. Skipping...
Chunk 359 does not have enough neighbors. Skipping...
Chunk 452 does not have enough neighbors. Skipping...
Chunk 497 does not have enough neighbors. Skipping...
Chunk 529 does not have enough neighbors. Skipping...
Chunk 565 does not have enough neighbors. Skipping...
Chunk 644 does not have enough neighbors. Skipping...
Chunk 820 does not have enough neighbors. Skipping...
Chunk 921 does not have enough neighbors. Skipping...
Chunk 1003 does not have enough neighbors. Skipping...
Chunk 1091 does not have enough neighbors. Skipping...
Chunk 1228 does not have enough neighbors. Skipping...
Chunk 1568 does not have enough neighbors. Skipping...
Chunk 1618 does not have enough neighbors. Skipping...
Chunk 1623 does not have enough neighbors. Skipping...
Chunk 1770 does not have enough neighbors. Skipping...
Chunk 1903 does not have enough neighbors. Skipping...
Chunk 1914 does not have enough neighbors. Skipping...
Chunk 1927 does not have enough neighbors. Skipping...
Chunk 2057 does not have enough neighbors. Skipping...
Chunk 2210 does not have enough neighbors. Skipping...
Chunk 2252 does not have enough neighbors. Skipping...
Chunk 2310 does not have enough neighbors. Skipping...
Chunk 2479 does not have enough neighbors. Skipping...
Chunk 2485 does not have enough neighbors. Skipping...
7_human_pbmc_10x

AnnData object with n_obs × n_vars = 2592 × 13000
    obs: 'group', 'cell_type', 'batch', 'silhouette_temp', 'cluster'
    var: 'modality'
    uns: 'modality_lengths', 'neighbors', 'umap', 'cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'distances', 'connectivities'

In [10]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '7_human_pbmc_10x'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result_best_reso.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.674823,0.689879,0.776603,0.989808,0.661599,Garfield,7_human_pbmc_10x
1,0.679863,0.565031,0.761804,0.930917,0.568089,Multigrate,7_human_pbmc_10x
2,0.782798,0.711974,0.817902,0.996757,0.648317,MultiVI,7_human_pbmc_10x
3,0.630354,0.678811,0.755995,0.984283,0.648767,MOFA,7_human_pbmc_10x
4,0.586445,0.796970,0.763496,0.996275,0.719270,Seurat,7_human_pbmc_10x

#### 利用最佳分辨率计算指标(Garfield);

In [16]:
## 记录resolution
reso_dict = {
    '7_human_pbmc_10x': {
        'Garfield': 0.3, # 0.405,
        'Multigrate': 1.550000000000001,
        'MultiVI': 0.17433922005000008,
        'MOFA': 0.32805000000000006,
        'Seurat': 0.08338590849833288, 
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('7_human_pbmc_10x', reso_dict=reso_dict)
adata

the length of cell type: 10
method_reso is not None, using the 0.3 as resolution for Garfield...
Number of clusters: 10
the length of cell type: 10
method_reso is not None, using the 1.550000000000001 as resolution for Multigrate...
Number of clusters: 10
the length of cell type: 10
method_reso is not None, using the 0.17433922005000008 as resolution for MultiVI...
Number of clusters: 10
the length of cell type: 10
method_reso is not None, using the 0.32805000000000006 as resolution for MOFA...
Number of clusters: 10
Chunk 26 does not have enough neighbors. Skipping...
Chunk 136 does not have enough neighbors. Skipping...
Chunk 195 does not have enough neighbors. Skipping...
Chunk 216 does not have enough neighbors. Skipping...
Chunk 341 does not have enough neighbors. Skipping...
Chunk 359 does not have enough neighbors. Skipping...
Chunk 452 does not have enough neighbors. Skipping...
Chunk 497 does not have enough neighbors. Skipping...
Chunk 529 does not have enough neighbors. Skipping...
Chunk 565 does not have enough neighbors. Skipping...
Chunk 644 does not have enough neighbors. Skipping...
Chunk 820 does not have enough neighbors. Skipping...
Chunk 921 does not have enough neighbors. Skipping...
Chunk 1003 does not have enough neighbors. Skipping...
Chunk 1091 does not have enough neighbors. Skipping...
Chunk 1228 does not have enough neighbors. Skipping...
Chunk 1568 does not have enough neighbors. Skipping...
Chunk 1618 does not have enough neighbors. Skipping...
Chunk 1623 does not have enough neighbors. Skipping...
Chunk 1770 does not have enough neighbors. Skipping...
Chunk 1903 does not have enough neighbors. Skipping...
Chunk 1914 does not have enough neighbors. Skipping...
Chunk 1927 does not have enough neighbors. Skipping...
Chunk 2057 does not have enough neighbors. Skipping...
Chunk 2210 does not have enough neighbors. Skipping...
Chunk 2252 does not have enough neighbors. Skipping...
Chunk 2310 does not have enough neighbors. Skipping...
Chunk 2479 does not have enough neighbors. Skipping...
Chunk 2485 does not have enough neighbors. Skipping...
the length of cell type: 10
method_reso is not None, using the 0.08338590849833288 as resolution for Seurat...
Number of clusters: 10
Chunk 26 does not have enough neighbors. Skipping...
Chunk 136 does not have enough neighbors. Skipping...
Chunk 195 does not have enough neighbors. Skipping...
Chunk 216 does not have enough neighbors. Skipping...
Chunk 341 does not have enough neighbors. Skipping...
Chunk 359 does not have enough neighbors. Skipping...
Chunk 452 does not have enough neighbors. Skipping...
Chunk 497 does not have enough neighbors. Skipping...
Chunk 529 does not have enough neighbors. Skipping...
Chunk 565 does not have enough neighbors. Skipping...
Chunk 644 does not have enough neighbors. Skipping...
Chunk 820 does not have enough neighbors. Skipping...
Chunk 921 does not have enough neighbors. Skipping...
Chunk 1003 does not have enough neighbors. Skipping...
Chunk 1091 does not have enough neighbors. Skipping...
Chunk 1228 does not have enough neighbors. Skipping...
Chunk 1568 does not have enough neighbors. Skipping...
Chunk 1618 does not have enough neighbors. Skipping...
Chunk 1623 does not have enough neighbors. Skipping...
Chunk 1770 does not have enough neighbors. Skipping...
Chunk 1903 does not have enough neighbors. Skipping...
Chunk 1914 does not have enough neighbors. Skipping...
Chunk 1927 does not have enough neighbors. Skipping...
Chunk 2057 does not have enough neighbors. Skipping...
Chunk 2210 does not have enough neighbors. Skipping...
Chunk 2252 does not have enough neighbors. Skipping...
Chunk 2310 does not have enough neighbors. Skipping...
Chunk 2479 does not have enough neighbors. Skipping...
Chunk 2485 does not have enough neighbors. Skipping...
7_human_pbmc_10x

AnnData object with n_obs × n_vars = 2592 × 13000
    obs: 'group', 'cell_type', 'batch', 'Garfield_cluster', 'silhouette_temp', 'Multigrate_cluster', 'MultiVI_cluster', 'MOFA_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'MultiVI', 'MultiVI_cluster', 'MOFA', 'MOFA_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'MultiVI_distances', 'MultiVI_connectivities', 'MOFA_distances', 'MOFA_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [17]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '7_human_pbmc_10x'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.674823,0.689879,0.776603,0.989808,0.661599,Garfield,7_human_pbmc_10x
1,0.540047,0.565031,0.712995,0.930917,0.568089,Multigrate,7_human_pbmc_10x
2,0.791090,0.711974,0.820206,0.996757,0.648317,MultiVI,7_human_pbmc_10x
3,0.573762,0.678811,0.709448,0.984283,0.648767,MOFA,7_human_pbmc_10x
4,0.654868,0.796970,0.778771,0.996275,0.719270,Seurat,7_human_pbmc_10x

### 数据集 6_pbmc_granulocyte_sorted_10x

In [15]:
## 记录resolution
reso_dict = {
    '6_pbmc_granulocyte_sorted_10x': {
        'Garfield': 0.6000000000000001,
        'Multigrate': 0.9500000000000004,
        'MultiVI': 0.47,
        'MOFA': 0.6500000000000001,
        'Seurat': 0.0926510094425921, 
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('6_pbmc_granulocyte_sorted_10x', reso_dict=reso_dict)
adata

the length of cell type: 17
method_reso is not None, using the 0.6000000000000001 as resolution for Garfield...
Number of clusters: 17
the length of cell type: 17
method_reso is not None, using the 0.9500000000000004 as resolution for Multigrate...
Number of clusters: 17
the length of cell type: 17
method_reso is not None, using the 0.47 as resolution for MultiVI...
Number of clusters: 17
the length of cell type: 17
Searching resolution for MOFA...
Searching resolution...
resolution=1.9500000000000013, cluster number=36
resolution=1.9000000000000012, cluster number=34
resolution=1.8500000000000012, cluster number=34
resolution=1.8000000000000012, cluster number=31
resolution=1.750000000000001, cluster number=32
resolution=1.700000000000001, cluster number=31
resolution=1.650000000000001, cluster number=29
resolution=1.600000000000001, cluster number=31
resolution=1.550000000000001, cluster number=28
resolution=1.5000000000000009, cluster number=30
resolution=1.4500000000000008, cluster number=26
resolution=1.4000000000000008, cluster number=27
resolution=1.3500000000000008, cluster number=26
resolution=1.3000000000000007, cluster number=28
resolution=1.2500000000000007, cluster number=24
resolution=1.2000000000000006, cluster number=23
resolution=1.1500000000000006, cluster number=23
resolution=1.1000000000000005, cluster number=24
resolution=1.0500000000000005, cluster number=22
resolution=1.0000000000000004, cluster number=22
resolution=0.9500000000000004, cluster number=22
resolution=0.9000000000000004, cluster number=21
resolution=0.8500000000000003, cluster number=20
resolution=0.8000000000000003, cluster number=19
resolution=0.7500000000000002, cluster number=18
resolution=0.7000000000000002, cluster number=18
resolution=0.6500000000000001, cluster number=17
Number of clusters: 17
the length of cell type: 17
Searching resolution for Seurat...
Searching resolution...
resolution=1.9500000000000013, cluster number=82
resolution=1.9000000000000012, cluster number=80
resolution=1.8500000000000012, cluster number=80
resolution=1.8000000000000012, cluster number=78
resolution=1.750000000000001, cluster number=78
resolution=1.700000000000001, cluster number=77
resolution=1.650000000000001, cluster number=77
resolution=1.600000000000001, cluster number=76
resolution=1.550000000000001, cluster number=75
resolution=1.5000000000000009, cluster number=73
resolution=1.4500000000000008, cluster number=70
resolution=1.4000000000000008, cluster number=68
resolution=1.3500000000000008, cluster number=66
resolution=1.3000000000000007, cluster number=64
resolution=1.2500000000000007, cluster number=61
resolution=1.2000000000000006, cluster number=57
resolution=1.1500000000000006, cluster number=57
resolution=1.1000000000000005, cluster number=53
resolution=1.0500000000000005, cluster number=53
resolution=1.0000000000000004, cluster number=52
resolution=0.9500000000000004, cluster number=50
resolution=0.9000000000000004, cluster number=47
resolution=0.8500000000000003, cluster number=47
resolution=0.8000000000000003, cluster number=48
resolution=0.7500000000000002, cluster number=44
resolution=0.7000000000000002, cluster number=42
resolution=0.6500000000000001, cluster number=42
resolution=0.6000000000000001, cluster number=41
resolution=0.55, cluster number=38
resolution=0.5, cluster number=37
Expanding search range: new range (0.45, 0.7875)
resolution=0.75, cluster number=44
resolution=0.7, cluster number=42
resolution=0.6499999999999999, cluster number=42
resolution=0.6, cluster number=41
resolution=0.55, cluster number=38
resolution=0.5, cluster number=37
resolution=0.45, cluster number=33
Expanding search range: new range (0.405, 0.70875)
resolution=0.705, cluster number=43
resolution=0.655, cluster number=42
resolution=0.605, cluster number=40
resolution=0.5549999999999999, cluster number=38
resolution=0.505, cluster number=35
resolution=0.455, cluster number=33
resolution=0.405, cluster number=31
Expanding search range: new range (0.36450000000000005, 0.6378750000000001)
resolution=0.6145, cluster number=40
resolution=0.5645, cluster number=38
resolution=0.5145, cluster number=36
resolution=0.4645, cluster number=33
resolution=0.41450000000000004, cluster number=29
resolution=0.36450000000000005, cluster number=30
Expanding search range: new range (0.32805000000000006, 0.5740875000000001)
resolution=0.52805, cluster number=36
resolution=0.47805000000000003, cluster number=35
resolution=0.42805000000000004, cluster number=31
resolution=0.37805000000000005, cluster number=30
resolution=0.32805000000000006, cluster number=27
Expanding search range: new range (0.2952450000000001, 0.5166787500000002)
resolution=0.49524500000000005, cluster number=37
resolution=0.44524500000000006, cluster number=33
resolution=0.39524500000000007, cluster number=30
resolution=0.3452450000000001, cluster number=28
resolution=0.2952450000000001, cluster number=27
Expanding search range: new range (0.2657205000000001, 0.46501087500000016)
resolution=0.41572050000000005, cluster number=30
resolution=0.36572050000000006, cluster number=30
resolution=0.31572050000000007, cluster number=28
resolution=0.2657205000000001, cluster number=25
Expanding search range: new range (0.23914845000000007, 0.4185097875000001)
resolution=0.38914845000000003, cluster number=30
resolution=0.33914845000000005, cluster number=27
resolution=0.28914845000000006, cluster number=27
resolution=0.23914845000000007, cluster number=24
Expanding search range: new range (0.21523360500000008, 0.37665880875000013)
resolution=0.3652336050000001, cluster number=30
resolution=0.3152336050000001, cluster number=28
resolution=0.2652336050000001, cluster number=25
resolution=0.21523360500000008, cluster number=24
Expanding search range: new range (0.19371024450000007, 0.3389929278750001)
resolution=0.29371024450000005, cluster number=27
resolution=0.24371024450000006, cluster number=24
resolution=0.19371024450000007, cluster number=22
Expanding search range: new range (0.17433922005000008, 0.30509363508750015)
resolution=0.27433922005000005, cluster number=26
resolution=0.22433922005000007, cluster number=24
resolution=0.17433922005000008, cluster number=20
Expanding search range: new range (0.15690529804500009, 0.27458427157875015)
resolution=0.25690529804500006, cluster number=24
resolution=0.20690529804500007, cluster number=24
resolution=0.15690529804500009, cluster number=20
Expanding search range: new range (0.14121476824050008, 0.24712584442087515)
resolution=0.24121476824050012, cluster number=24
resolution=0.1912147682405001, cluster number=21
resolution=0.14121476824050008, cluster number=19
Expanding search range: new range (0.12709329141645007, 0.2224132599787876)
resolution=0.17709329141645008, cluster number=20
resolution=0.12709329141645007, cluster number=19
Expanding search range: new range (0.11438396227480506, 0.20017193398090885)
resolution=0.16438396227480506, cluster number=20
resolution=0.11438396227480506, cluster number=18
Expanding search range: new range (0.10294556604732455, 0.18015474058281797)
resolution=0.15294556604732457, cluster number=19
resolution=0.10294556604732455, cluster number=18
Expanding search range: new range (0.0926510094425921, 0.16213926652453617)
resolution=0.1426510094425921, cluster number=19
resolution=0.0926510094425921, cluster number=17
Number of clusters: 17
6_pbmc_granulocyte_sorted_10x

AnnData object with n_obs × n_vars = 10137 × 13000
    obs: 'group', 'cell_type', 'batch', 'Garfield_cluster', 'silhouette_temp', 'Multigrate_cluster', 'MultiVI_cluster', 'MOFA_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'MultiVI', 'MultiVI_cluster', 'MOFA', 'MOFA_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'MultiVI_distances', 'MultiVI_connectivities', 'MOFA_distances', 'MOFA_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [16]:
import matplotlib.pyplot as plt

dataset = '6_pbmc_granulocyte_sorted_10x'
res_dir = f'/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC/{dataset}'

latent_key_list = ['Garfield', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat']
for latent_key in latent_key_list:
    sc.tl.umap(adata, neighbors_key=latent_key)
    latent_key_cluster = latent_key + '_cluster'
    
    # Create a new figure for each plot with an appropriate size
    plt.figure(figsize=(12, 6))  # Adjust the figsize as needed
    sc.pl.umap(adata, color=['cell_type', latent_key_cluster], wspace=0.5, hspace=0.5, show=False, ncols=2)
    # Save the figure
    plt.savefig(res_dir + f"/{latent_key}_UMAP_clusters.png", bbox_inches='tight')  # Use bbox_inches to ensure full legend display
    plt.close()

In [17]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '6_pbmc_granulocyte_sorted_10x'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.554142,0.648922,0.751475,0.992975,0.602007,Garfield,6_pbmc_granulocyte_sorted_10x
1,0.533804,0.597531,0.717887,0.986449,0.549878,Multigrate,6_pbmc_granulocyte_sorted_10x
2,0.426603,0.645374,0.689509,0.992112,0.574815,MultiVI,6_pbmc_granulocyte_sorted_10x
3,0.492799,0.627424,0.715005,0.990376,0.569079,MOFA,6_pbmc_granulocyte_sorted_10x
4,0.581648,0.676489,0.731705,0.992321,0.600173,Seurat,6_pbmc_granulocyte_sorted_10x

#### 探索一下用最佳分辨率

In [20]:
# calculate the metrics based on the best resolution
adata = count_metrics_for_best_resolution('6_pbmc_granulocyte_sorted_10x')
adata

WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.7626309050410545
resolution: 0.2, nmi: 0.7757976702108258
resolution: 0.3, nmi: 0.7671757649936511
resolution: 0.4, nmi: 0.7529705870286229
resolution: 0.5, nmi: 0.7663532958988659
resolution: 0.6, nmi: 0.7514754169419015
resolution: 0.7, nmi: 0.7285444394906712
resolution: 0.8, nmi: 0.7200502175502791
resolution: 0.9, nmi: 0.7051785602148432
resolution: 1.0, nmi: 0.711517867495174
resolution: 1.1, nmi: 0.7038227577420872
resolution: 1.2, nmi: 0.6970653119746127
resolution: 1.3, nmi: 0.6890439920006236
resolution: 1.4, nmi: 0.6845148520241829
resolution: 1.5, nmi: 0.6781082407926855
resolution: 1.6, nmi: 0.6783780952730941
resolution: 1.7, nmi: 0.6693900209083833
resolution: 1.8, nmi: 0.6685127042791499
resolution: 1.9, nmi: 0.6576845767325323
resolution: 2.0, nmi: 0.657188554631055
optimised clustering against cell_type
optimal cluster resolution: 0.2
optimal score: 0.7757976702108258
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.7056741548743519
resolution: 0.2, nmi: 0.7602790552697961
resolution: 0.3, nmi: 0.773145418556605
resolution: 0.4, nmi: 0.7695321190350597
resolution: 0.5, nmi: 0.770377892604125
resolution: 0.6, nmi: 0.7406021512332768
resolution: 0.7, nmi: 0.7321746276385238
resolution: 0.8, nmi: 0.7162660908076052
resolution: 0.9, nmi: 0.7148549924669106
resolution: 1.0, nmi: 0.711482233093798
resolution: 1.1, nmi: 0.7102004135869923
resolution: 1.2, nmi: 0.7114857369171608
resolution: 1.3, nmi: 0.7046395050983213
resolution: 1.4, nmi: 0.6952432037395279
resolution: 1.5, nmi: 0.6926786362184724
resolution: 1.6, nmi: 0.6934263529945609
resolution: 1.7, nmi: 0.6936623814541291
resolution: 1.8, nmi: 0.6848892704695982
resolution: 1.9, nmi: 0.6813429412681918
resolution: 2.0, nmi: 0.6864947569839538
optimised clustering against cell_type
optimal cluster resolution: 0.3
optimal score: 0.773145418556605
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.7341537861593529
resolution: 0.2, nmi: 0.7710784324900125
resolution: 0.3, nmi: 0.7347392337692618
resolution: 0.4, nmi: 0.7099653696429885
resolution: 0.5, nmi: 0.7067934171394925
resolution: 0.6, nmi: 0.6836055165879883
resolution: 0.7, nmi: 0.6789841545718927
resolution: 0.8, nmi: 0.674689379972787
resolution: 0.9, nmi: 0.6771960208447593
resolution: 1.0, nmi: 0.6713792253945947
resolution: 1.1, nmi: 0.6672499336920021
resolution: 1.2, nmi: 0.658127990387459
resolution: 1.3, nmi: 0.6519790654465311
resolution: 1.4, nmi: 0.6478731194078432
resolution: 1.5, nmi: 0.6451233236814247
resolution: 1.6, nmi: 0.6415329058549121
resolution: 1.7, nmi: 0.6420841474333154
resolution: 1.8, nmi: 0.6349577203979918
resolution: 1.9, nmi: 0.6350245662035904
resolution: 2.0, nmi: 0.6310261775145294
optimised clustering against cell_type
optimal cluster resolution: 0.2
optimal score: 0.7710784324900125
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.76359846885491
resolution: 0.2, nmi: 0.7704554439442448
resolution: 0.3, nmi: 0.7564643125543056
resolution: 0.4, nmi: 0.7322386734967417
resolution: 0.5, nmi: 0.7174592499739858
resolution: 0.6, nmi: 0.734376355149797
resolution: 0.7, nmi: 0.7035361776598892
resolution: 0.8, nmi: 0.6904579567684576
resolution: 0.9, nmi: 0.6911797223660792
resolution: 1.0, nmi: 0.6860631629013838
resolution: 1.1, nmi: 0.6760842784366516
resolution: 1.2, nmi: 0.6757957417110877
resolution: 1.3, nmi: 0.6602702430383035
resolution: 1.4, nmi: 0.671091256894782
resolution: 1.5, nmi: 0.660504285950677
resolution: 1.6, nmi: 0.6591685059505674
resolution: 1.7, nmi: 0.656652883146178
resolution: 1.8, nmi: 0.6546894896875753
resolution: 1.9, nmi: 0.6469114538821503
resolution: 2.0, nmi: 0.6426179907487526
optimised clustering against cell_type
optimal cluster resolution: 0.2
optimal score: 0.7704554439442448
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.723239794451729
resolution: 0.2, nmi: 0.6940176925543075
resolution: 0.3, nmi: 0.6745168991425732
resolution: 0.4, nmi: 0.6635268748252543
resolution: 0.5, nmi: 0.646002821005307
resolution: 0.6, nmi: 0.6337673566338153
resolution: 0.7, nmi: 0.6339970892101979
resolution: 0.8, nmi: 0.6211172539998647
resolution: 0.9, nmi: 0.6245099994461086
resolution: 1.0, nmi: 0.6152989208227791
resolution: 1.1, nmi: 0.6131828548039753
resolution: 1.2, nmi: 0.6057553372133083
resolution: 1.3, nmi: 0.5996213704255712
resolution: 1.4, nmi: 0.5949200803952299
resolution: 1.5, nmi: 0.5899550054225151
resolution: 1.6, nmi: 0.5853290618518104
resolution: 1.7, nmi: 0.5841272106369984
resolution: 1.8, nmi: 0.5849474763484741
resolution: 1.9, nmi: 0.583364943517835
resolution: 2.0, nmi: 0.5785591597367664
optimised clustering against cell_type
optimal cluster resolution: 0.1
optimal score: 0.723239794451729
6_pbmc_granulocyte_sorted_10x

AnnData object with n_obs × n_vars = 10137 × 13000
    obs: 'group', 'cell_type', 'batch', 'silhouette_temp', 'cluster'
    var: 'modality'
    uns: 'modality_lengths', 'neighbors', 'umap', 'cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'distances', 'connectivities'

In [6]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '6_pbmc_granulocyte_sorted_10x'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result_best_reso.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.748856,0.648922,0.775798,0.992975,0.602007,Garfield,6_pbmc_granulocyte_sorted_10x
1,0.752448,0.597531,0.773145,0.986449,0.549878,Multigrate,6_pbmc_granulocyte_sorted_10x
2,0.748852,0.645374,0.771078,0.992112,0.574815,MultiVI,6_pbmc_granulocyte_sorted_10x
3,0.647237,0.627424,0.770455,0.990376,0.569079,MOFA,6_pbmc_granulocyte_sorted_10x
4,0.548936,0.676489,0.723240,0.992321,0.600173,Seurat,6_pbmc_granulocyte_sorted_10x

#### 利用最佳分辨率计算指标(Garfield);

In [18]:
## 记录resolution
reso_dict = {
    '6_pbmc_granulocyte_sorted_10x': {
        'Garfield': 0.2, # 0.6000000000000001,
        'Multigrate': 0.9500000000000004,
        'MultiVI': 0.47,
        'MOFA': 0.6500000000000001,
        'Seurat': 0.0926510094425921, 
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('6_pbmc_granulocyte_sorted_10x', reso_dict=reso_dict)
adata

the length of cell type: 17
method_reso is not None, using the 0.2 as resolution for Garfield...
Number of clusters: 9
the length of cell type: 17
method_reso is not None, using the 0.9500000000000004 as resolution for Multigrate...
Number of clusters: 17
the length of cell type: 17
method_reso is not None, using the 0.47 as resolution for MultiVI...
Number of clusters: 17
the length of cell type: 17
method_reso is not None, using the 0.6500000000000001 as resolution for MOFA...
Number of clusters: 17
the length of cell type: 17
method_reso is not None, using the 0.0926510094425921 as resolution for Seurat...
Number of clusters: 17
6_pbmc_granulocyte_sorted_10x

AnnData object with n_obs × n_vars = 10137 × 13000
    obs: 'group', 'cell_type', 'batch', 'Garfield_cluster', 'silhouette_temp', 'Multigrate_cluster', 'MultiVI_cluster', 'MOFA_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'MultiVI', 'MultiVI_cluster', 'MOFA', 'MOFA_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'MultiVI_distances', 'MultiVI_connectivities', 'MOFA_distances', 'MOFA_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [19]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '6_pbmc_granulocyte_sorted_10x'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.748856,0.648922,0.775798,0.992975,0.602007,Garfield,6_pbmc_granulocyte_sorted_10x
1,0.533804,0.597531,0.717887,0.986449,0.549878,Multigrate,6_pbmc_granulocyte_sorted_10x
2,0.426603,0.645374,0.689509,0.992112,0.574815,MultiVI,6_pbmc_granulocyte_sorted_10x
3,0.492799,0.627424,0.715005,0.990376,0.569079,MOFA,6_pbmc_granulocyte_sorted_10x
4,0.581648,0.676489,0.731705,0.992321,0.600173,Seurat,6_pbmc_granulocyte_sorted_10x

### 数据集 5_human_brain_10x

In [11]:
## 记录resolution
reso_dict = {
    '5_human_brain_10x': {
        'Garfield': 0.245,
        'Multigrate': 0.7500000000000002,
        'MultiVI': 0.0750473176484996,
        'MOFA': 0.17709329141645008,
        'Seurat': 0.021195579137608122, 
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('5_human_brain_10x', reso_dict=reso_dict)
adata

the length of cell type: 8
method_reso is not None, using the 0.245 as resolution for Garfield...
Number of clusters: 9
the length of cell type: 8
method_reso is not None, using the 0.7500000000000002 as resolution for Multigrate...
Number of clusters: 8
the length of cell type: 8
method_reso is not None, using the 0.0750473176484996 as resolution for MultiVI...
Number of clusters: 8
the length of cell type: 8
method_reso is not None, using the 0.17709329141645008 as resolution for MOFA...
Number of clusters: 8
the length of cell type: 8
method_reso is not None, using the 0.021195579137608122 as resolution for Seurat...
Number of clusters: 8
Chunk 126 does not have enough neighbors. Skipping...
Chunk 218 does not have enough neighbors. Skipping...
Chunk 378 does not have enough neighbors. Skipping...
Chunk 606 does not have enough neighbors. Skipping...
Chunk 851 does not have enough neighbors. Skipping...
Chunk 1175 does not have enough neighbors. Skipping...
Chunk 1326 does not have enough neighbors. Skipping...
Chunk 1478 does not have enough neighbors. Skipping...
Chunk 1508 does not have enough neighbors. Skipping...
Chunk 1718 does not have enough neighbors. Skipping...
Chunk 1790 does not have enough neighbors. Skipping...
Chunk 2101 does not have enough neighbors. Skipping...
Chunk 2385 does not have enough neighbors. Skipping...
Chunk 2515 does not have enough neighbors. Skipping...
Chunk 2550 does not have enough neighbors. Skipping...
Chunk 2751 does not have enough neighbors. Skipping...
5_human_brain_10x

AnnData object with n_obs × n_vars = 2855 × 13000
    obs: 'group', 'cell_type', 'batch', 'Garfield_cluster', 'silhouette_temp', 'Multigrate_cluster', 'MultiVI_cluster', 'MOFA_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'MultiVI', 'MultiVI_cluster', 'MOFA', 'MOFA_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'MultiVI_distances', 'MultiVI_connectivities', 'MOFA_distances', 'MOFA_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [12]:
import matplotlib.pyplot as plt

dataset = '5_human_brain_10x'
res_dir = f'/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC/{dataset}'

latent_key_list = ['Garfield', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat']
for latent_key in latent_key_list:
    sc.tl.umap(adata, neighbors_key=latent_key)
    latent_key_cluster = latent_key + '_cluster'
    
    # Create a new figure for each plot with an appropriate size
    plt.figure(figsize=(12, 6))  # Adjust the figsize as needed
    sc.pl.umap(adata, color=['cell_type', latent_key_cluster], wspace=0.5, hspace=0.5, show=False, ncols=2)
    # Save the figure
    plt.savefig(res_dir + f"/{latent_key}_UMAP_clusters.png", bbox_inches='tight')  # Use bbox_inches to ensure full legend display
    plt.close()

In [13]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '5_human_brain_10x'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.604645,0.715671,0.807935,1.0,0.825768,Garfield,5_human_brain_10x
1,0.576274,0.606063,0.723754,1.0,0.741968,Multigrate,5_human_brain_10x
2,0.547282,0.718769,0.713029,1.0,0.722927,MultiVI,5_human_brain_10x
3,0.576093,0.707015,0.775741,1.0,0.760355,MOFA,5_human_brain_10x
4,0.674943,0.812406,0.820338,1.0,0.789231,Seurat,5_human_brain_10x

#### 探索一下用最佳分辨率

In [7]:
# calculate the metrics based on the best resolution
adata = count_metrics_for_best_resolution('5_human_brain_10x')
adata

WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.7829232729989649
resolution: 0.2, nmi: 0.8013067242474287
resolution: 0.3, nmi: 0.7309640391062733
resolution: 0.4, nmi: 0.7207422629546304
resolution: 0.5, nmi: 0.7261748581681903
resolution: 0.6, nmi: 0.6942114506851838
resolution: 0.7, nmi: 0.6695791534759318
resolution: 0.8, nmi: 0.6427437823971089
resolution: 0.9, nmi: 0.6364089273473252
resolution: 1.0, nmi: 0.6207374905333479
resolution: 1.1, nmi: 0.6311015513479621
resolution: 1.2, nmi: 0.609930130253816
resolution: 1.3, nmi: 0.6122000955115091
resolution: 1.4, nmi: 0.6049432765477988
resolution: 1.5, nmi: 0.5967870520318065
resolution: 1.6, nmi: 0.5888017749026527
resolution: 1.7, nmi: 0.5803193157058757
resolution: 1.8, nmi: 0.5721182149858675
resolution: 1.9, nmi: 0.5671236964986385
resolution: 2.0, nmi: 0.5645492917793165
optimised clustering against cell_type
optimal cluster resolution: 0.2
optimal score: 0.8013067242474287
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.7745229101914064
resolution: 0.2, nmi: 0.7930579559701197
resolution: 0.3, nmi: 0.7862425426502363
resolution: 0.4, nmi: 0.7862425426502363
resolution: 0.5, nmi: 0.785348006744825
resolution: 0.6, nmi: 0.7819458193005016
resolution: 0.7, nmi: 0.7211065384122809
resolution: 0.8, nmi: 0.6823273386946755
resolution: 0.9, nmi: 0.6767042188474627
resolution: 1.0, nmi: 0.6416895871765826
resolution: 1.1, nmi: 0.6271928856233366
resolution: 1.2, nmi: 0.5946275769525273
resolution: 1.3, nmi: 0.5801173266514869
resolution: 1.4, nmi: 0.5804925102198506
resolution: 1.5, nmi: 0.5619140560292255
resolution: 1.6, nmi: 0.5573666501309688
resolution: 1.7, nmi: 0.5635042192927044
resolution: 1.8, nmi: 0.5568148108273757
resolution: 1.9, nmi: 0.5493037521890141
resolution: 2.0, nmi: 0.544176215811841
optimised clustering against cell_type
optimal cluster resolution: 0.2
optimal score: 0.7930579559701197
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.6642249308035656
resolution: 0.2, nmi: 0.6579929482845002
resolution: 0.3, nmi: 0.6640533608760563
resolution: 0.4, nmi: 0.6273228482271286
resolution: 0.5, nmi: 0.6197034453403782
resolution: 0.6, nmi: 0.6050843812429365
resolution: 0.7, nmi: 0.5951438402453268
resolution: 0.8, nmi: 0.5915326620422474
resolution: 0.9, nmi: 0.5851353628157397
resolution: 1.0, nmi: 0.5846537365174921
resolution: 1.1, nmi: 0.5843989128910183
resolution: 1.2, nmi: 0.578833979401379
resolution: 1.3, nmi: 0.5800728444326309
resolution: 1.4, nmi: 0.5833897427936885
resolution: 1.5, nmi: 0.5665788309488006
resolution: 1.6, nmi: 0.5601658384914913
resolution: 1.7, nmi: 0.5511806650464952
resolution: 1.8, nmi: 0.5463900997007384
resolution: 1.9, nmi: 0.5485925610874933
resolution: 2.0, nmi: 0.5437027535898196
optimised clustering against cell_type
optimal cluster resolution: 0.1
optimal score: 0.6642249308035656
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.7496794709946208
resolution: 0.2, nmi: 0.7521150301729776
resolution: 0.3, nmi: 0.6593889784741375
resolution: 0.4, nmi: 0.6675313301195489
resolution: 0.5, nmi: 0.6663268807365136
resolution: 0.6, nmi: 0.6644631363681746
resolution: 0.7, nmi: 0.6554856548651465
resolution: 0.8, nmi: 0.6341619288120377
resolution: 0.9, nmi: 0.633020416693343
resolution: 1.0, nmi: 0.6281483884550901
resolution: 1.1, nmi: 0.636924513990928
resolution: 1.2, nmi: 0.6050668702148029
resolution: 1.3, nmi: 0.6019736427129824
resolution: 1.4, nmi: 0.6022408991142151
resolution: 1.5, nmi: 0.5967102317918999
resolution: 1.6, nmi: 0.5892133708069491
resolution: 1.7, nmi: 0.5917825635354974
resolution: 1.8, nmi: 0.5906966071716501
resolution: 1.9, nmi: 0.578959608463912
resolution: 2.0, nmi: 0.5794553760655667
optimised clustering against cell_type
optimal cluster resolution: 0.2
optimal score: 0.7521150301729776
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.6903899168068397
resolution: 0.2, nmi: 0.6322470610104038
resolution: 0.3, nmi: 0.6339844326882773
resolution: 0.4, nmi: 0.5933318669046369
resolution: 0.5, nmi: 0.5681208583766527
resolution: 0.6, nmi: 0.5602607040729208
resolution: 0.7, nmi: 0.5561596069545993
resolution: 0.8, nmi: 0.5563693882454266
resolution: 0.9, nmi: 0.5550371663904327
resolution: 1.0, nmi: 0.5550371663904327
resolution: 1.1, nmi: 0.5503703649796429
resolution: 1.2, nmi: 0.5408965661828853
resolution: 1.3, nmi: 0.5355875280369887
resolution: 1.4, nmi: 0.531062566488159
resolution: 1.5, nmi: 0.5262970843443774
resolution: 1.6, nmi: 0.5229118363917216
resolution: 1.7, nmi: 0.5196859508899163
resolution: 1.8, nmi: 0.5169294783294388
resolution: 1.9, nmi: 0.5176172573411281
resolution: 2.0, nmi: 0.5169912518958522
optimised clustering against cell_type
optimal cluster resolution: 0.1
optimal score: 0.6903899168068397
Chunk 126 does not have enough neighbors. Skipping...
Chunk 218 does not have enough neighbors. Skipping...
Chunk 378 does not have enough neighbors. Skipping...
Chunk 606 does not have enough neighbors. Skipping...
Chunk 851 does not have enough neighbors. Skipping...
Chunk 1175 does not have enough neighbors. Skipping...
Chunk 1326 does not have enough neighbors. Skipping...
Chunk 1478 does not have enough neighbors. Skipping...
Chunk 1508 does not have enough neighbors. Skipping...
Chunk 1718 does not have enough neighbors. Skipping...
Chunk 1790 does not have enough neighbors. Skipping...
Chunk 2101 does not have enough neighbors. Skipping...
Chunk 2385 does not have enough neighbors. Skipping...
Chunk 2515 does not have enough neighbors. Skipping...
Chunk 2550 does not have enough neighbors. Skipping...
Chunk 2751 does not have enough neighbors. Skipping...
5_human_brain_10x

AnnData object with n_obs × n_vars = 2855 × 13000
    obs: 'group', 'cell_type', 'batch', 'silhouette_temp', 'cluster'
    var: 'modality'
    uns: 'modality_lengths', 'neighbors', 'umap', 'cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'distances', 'connectivities'

In [9]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '5_human_brain_10x'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result_best_reso.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.610099,0.715671,0.801307,1.0,0.825768,Garfield,5_human_brain_10x
1,0.925922,0.606063,0.793058,1.0,0.741968,Multigrate,5_human_brain_10x
2,0.390442,0.718769,0.664225,1.0,0.722927,MultiVI,5_human_brain_10x
3,0.535730,0.707015,0.752115,1.0,0.760355,MOFA,5_human_brain_10x
4,0.340883,0.812406,0.690390,1.0,0.789231,Seurat,5_human_brain_10x

#### 利用最佳分辨率计算指标(Garfield);

In [20]:
## 记录resolution
reso_dict = {
    '5_human_brain_10x': {
        'Garfield': 0.2, # 0.245,
        'Multigrate': 0.7500000000000002,
        'MultiVI': 0.0750473176484996,
        'MOFA': 0.17709329141645008,
        'Seurat': 0.021195579137608122, 
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('5_human_brain_10x', reso_dict=reso_dict)
adata

the length of cell type: 8
method_reso is not None, using the 0.2 as resolution for Garfield...
Number of clusters: 7
the length of cell type: 8
method_reso is not None, using the 0.7500000000000002 as resolution for Multigrate...
Number of clusters: 8
the length of cell type: 8
method_reso is not None, using the 0.0750473176484996 as resolution for MultiVI...
Number of clusters: 8
the length of cell type: 8
method_reso is not None, using the 0.17709329141645008 as resolution for MOFA...
Number of clusters: 8
the length of cell type: 8
method_reso is not None, using the 0.021195579137608122 as resolution for Seurat...
Number of clusters: 8
Chunk 126 does not have enough neighbors. Skipping...
Chunk 218 does not have enough neighbors. Skipping...
Chunk 378 does not have enough neighbors. Skipping...
Chunk 606 does not have enough neighbors. Skipping...
Chunk 851 does not have enough neighbors. Skipping...
Chunk 1175 does not have enough neighbors. Skipping...
Chunk 1326 does not have enough neighbors. Skipping...
Chunk 1478 does not have enough neighbors. Skipping...
Chunk 1508 does not have enough neighbors. Skipping...
Chunk 1718 does not have enough neighbors. Skipping...
Chunk 1790 does not have enough neighbors. Skipping...
Chunk 2101 does not have enough neighbors. Skipping...
Chunk 2385 does not have enough neighbors. Skipping...
Chunk 2515 does not have enough neighbors. Skipping...
Chunk 2550 does not have enough neighbors. Skipping...
Chunk 2751 does not have enough neighbors. Skipping...
5_human_brain_10x

AnnData object with n_obs × n_vars = 2855 × 13000
    obs: 'group', 'cell_type', 'batch', 'Garfield_cluster', 'silhouette_temp', 'Multigrate_cluster', 'MultiVI_cluster', 'MOFA_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'MultiVI', 'MultiVI_cluster', 'MOFA', 'MOFA_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'MultiVI_distances', 'MultiVI_connectivities', 'MOFA_distances', 'MOFA_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [21]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '5_human_brain_10x'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.610099,0.715671,0.801307,1.0,0.825768,Garfield,5_human_brain_10x
1,0.576274,0.606063,0.723754,1.0,0.741968,Multigrate,5_human_brain_10x
2,0.547282,0.718769,0.713029,1.0,0.722927,MultiVI,5_human_brain_10x
3,0.576093,0.707015,0.775741,1.0,0.760355,MOFA,5_human_brain_10x
4,0.674943,0.812406,0.820338,1.0,0.789231,Seurat,5_human_brain_10x

### 数据集 4_brain_ISSAAC_seq

In [24]:
## 记录resolution
reso_dict = {
    '4_brain_ISSAAC_seq': {
        'Garfield': 0.8800000000000003,
        'Multigrate': 1.2400000000000007,
        'MultiVI': 0.8300000000000003,
        'MOFA': 0.9200000000000004,
        'Seurat': 0.11438396227480506, #0.11438396227480506
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('4_brain_ISSAAC_seq', reso_dict=reso_dict, 
                                     start=0.5, end=0.75, increment=0.05)
adata

the length of cell type: 20
method_reso is not None, using the 0.8800000000000003 as resolution for Garfield...
Number of clusters: 20
the length of cell type: 20
method_reso is not None, using the 1.2400000000000007 as resolution for Multigrate...
Number of clusters: 20
the length of cell type: 20
method_reso is not None, using the 0.8300000000000003 as resolution for MultiVI...
Number of clusters: 20
the length of cell type: 20
method_reso is not None, using the 0.9200000000000004 as resolution for MOFA...
Number of clusters: 20
the length of cell type: 20
Searching resolution for Seurat...
Searching resolution...
resolution=0.7000000000000002, cluster number=47
resolution=0.6500000000000001, cluster number=45
resolution=0.6000000000000001, cluster number=44
resolution=0.55, cluster number=42
resolution=0.5, cluster number=40
Expanding search range: new range (0.45, 0.7875)
resolution=0.75, cluster number=49
resolution=0.7, cluster number=47
resolution=0.6499999999999999, cluster number=45
resolution=0.6, cluster number=44
resolution=0.55, cluster number=42
resolution=0.5, cluster number=40
resolution=0.45, cluster number=38
Expanding search range: new range (0.405, 0.70875)
resolution=0.705, cluster number=47
resolution=0.655, cluster number=45
resolution=0.605, cluster number=44
resolution=0.5549999999999999, cluster number=42
resolution=0.505, cluster number=41
resolution=0.455, cluster number=38
resolution=0.405, cluster number=34
Expanding search range: new range (0.36450000000000005, 0.6378750000000001)
resolution=0.6145, cluster number=44
resolution=0.5645, cluster number=41
resolution=0.5145, cluster number=42
resolution=0.4645, cluster number=39
resolution=0.41450000000000004, cluster number=37
resolution=0.36450000000000005, cluster number=32
Expanding search range: new range (0.32805000000000006, 0.5740875000000001)
resolution=0.52805, cluster number=41
resolution=0.47805000000000003, cluster number=42
resolution=0.42805000000000004, cluster number=39
resolution=0.37805000000000005, cluster number=32
resolution=0.32805000000000006, cluster number=30
Expanding search range: new range (0.2952450000000001, 0.5166787500000002)
resolution=0.49524500000000005, cluster number=41
resolution=0.44524500000000006, cluster number=39
resolution=0.39524500000000007, cluster number=33
resolution=0.3452450000000001, cluster number=33
resolution=0.2952450000000001, cluster number=29
Expanding search range: new range (0.2657205000000001, 0.46501087500000016)
resolution=0.41572050000000005, cluster number=37
resolution=0.36572050000000006, cluster number=33
resolution=0.31572050000000007, cluster number=30
resolution=0.2657205000000001, cluster number=26
Expanding search range: new range (0.23914845000000007, 0.4185097875000001)
resolution=0.38914845000000003, cluster number=33
resolution=0.33914845000000005, cluster number=31
resolution=0.28914845000000006, cluster number=28
resolution=0.23914845000000007, cluster number=24
Expanding search range: new range (0.21523360500000008, 0.37665880875000013)
resolution=0.3652336050000001, cluster number=33
resolution=0.3152336050000001, cluster number=29
resolution=0.2652336050000001, cluster number=26
resolution=0.21523360500000008, cluster number=24
Expanding search range: new range (0.19371024450000007, 0.3389929278750001)
resolution=0.29371024450000005, cluster number=29
resolution=0.24371024450000006, cluster number=24
resolution=0.19371024450000007, cluster number=23
Expanding search range: new range (0.17433922005000008, 0.30509363508750015)
resolution=0.27433922005000005, cluster number=27
resolution=0.22433922005000007, cluster number=24
resolution=0.17433922005000008, cluster number=23
Expanding search range: new range (0.15690529804500009, 0.27458427157875015)
resolution=0.25690529804500006, cluster number=25
resolution=0.20690529804500007, cluster number=24
resolution=0.15690529804500009, cluster number=23
Expanding search range: new range (0.14121476824050008, 0.24712584442087515)
resolution=0.24121476824050012, cluster number=24
resolution=0.1912147682405001, cluster number=23
resolution=0.14121476824050008, cluster number=21
Expanding search range: new range (0.12709329141645007, 0.2224132599787876)
resolution=0.17709329141645008, cluster number=23
resolution=0.12709329141645007, cluster number=21
Expanding search range: new range (0.11438396227480506, 0.20017193398090885)
resolution=0.16438396227480506, cluster number=22
resolution=0.11438396227480506, cluster number=20
Number of clusters: 20
Chunk 766 does not have enough neighbors. Skipping...
Chunk 1157 does not have enough neighbors. Skipping...
Chunk 1459 does not have enough neighbors. Skipping...
Chunk 2504 does not have enough neighbors. Skipping...
Chunk 3266 does not have enough neighbors. Skipping...
Chunk 3631 does not have enough neighbors. Skipping...
Chunk 3643 does not have enough neighbors. Skipping...
Chunk 4018 does not have enough neighbors. Skipping...
Chunk 4731 does not have enough neighbors. Skipping...
Chunk 4849 does not have enough neighbors. Skipping...
Chunk 4916 does not have enough neighbors. Skipping...
Chunk 5120 does not have enough neighbors. Skipping...
Chunk 5129 does not have enough neighbors. Skipping...
Chunk 5560 does not have enough neighbors. Skipping...
Chunk 5614 does not have enough neighbors. Skipping...
Chunk 5857 does not have enough neighbors. Skipping...
Chunk 5949 does not have enough neighbors. Skipping...
Chunk 6371 does not have enough neighbors. Skipping...
Chunk 6393 does not have enough neighbors. Skipping...
Chunk 6444 does not have enough neighbors. Skipping...
Chunk 6527 does not have enough neighbors. Skipping...
Chunk 6548 does not have enough neighbors. Skipping...
Chunk 6583 does not have enough neighbors. Skipping...
Chunk 6627 does not have enough neighbors. Skipping...
Chunk 6735 does not have enough neighbors. Skipping...
Chunk 6781 does not have enough neighbors. Skipping...
Chunk 6845 does not have enough neighbors. Skipping...
Chunk 6996 does not have enough neighbors. Skipping...
Chunk 7026 does not have enough neighbors. Skipping...
Chunk 7104 does not have enough neighbors. Skipping...
Chunk 7107 does not have enough neighbors. Skipping...
Chunk 7134 does not have enough neighbors. Skipping...
Chunk 7440 does not have enough neighbors. Skipping...
Chunk 8009 does not have enough neighbors. Skipping...
Chunk 8060 does not have enough neighbors. Skipping...
Chunk 8267 does not have enough neighbors. Skipping...
Chunk 8290 does not have enough neighbors. Skipping...
Chunk 8300 does not have enough neighbors. Skipping...
Chunk 8419 does not have enough neighbors. Skipping...
Chunk 8680 does not have enough neighbors. Skipping...
Chunk 8694 does not have enough neighbors. Skipping...
Chunk 8865 does not have enough neighbors. Skipping...
Chunk 8968 does not have enough neighbors. Skipping...
Chunk 8994 does not have enough neighbors. Skipping...
Chunk 9001 does not have enough neighbors. Skipping...
Chunk 9026 does not have enough neighbors. Skipping...
Chunk 9535 does not have enough neighbors. Skipping...
Chunk 9593 does not have enough neighbors. Skipping...
Chunk 9671 does not have enough neighbors. Skipping...
Chunk 9760 does not have enough neighbors. Skipping...
Chunk 9797 does not have enough neighbors. Skipping...
Chunk 9894 does not have enough neighbors. Skipping...
Chunk 9925 does not have enough neighbors. Skipping...
Chunk 10020 does not have enough neighbors. Skipping...
Chunk 10178 does not have enough neighbors. Skipping...
Chunk 10230 does not have enough neighbors. Skipping...
Chunk 10250 does not have enough neighbors. Skipping...
Chunk 10276 does not have enough neighbors. Skipping...
4_brain_ISSAAC_seq

AnnData object with n_obs × n_vars = 10361 × 13000
    obs: 'group', 'cell_type', 'batch', 'Garfield_cluster', 'silhouette_temp', 'Multigrate_cluster', 'MultiVI_cluster', 'MOFA_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'MultiVI', 'MultiVI_cluster', 'MOFA', 'MOFA_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'MultiVI_distances', 'MultiVI_connectivities', 'MOFA_distances', 'MOFA_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [25]:
import matplotlib.pyplot as plt

dataset = '4_brain_ISSAAC_seq'
res_dir = f'/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC/{dataset}'

latent_key_list = ['Garfield', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat']
for latent_key in latent_key_list:
    sc.tl.umap(adata, neighbors_key=latent_key)
    latent_key_cluster = latent_key + '_cluster'
    
    # Create a new figure for each plot with an appropriate size
    plt.figure(figsize=(12, 6))  # Adjust the figsize as needed
    sc.pl.umap(adata, color=['cell_type', latent_key_cluster], wspace=0.5, hspace=0.5, show=False, ncols=2)
    # Save the figure
    plt.savefig(res_dir + f"/{latent_key}_UMAP_clusters.png", bbox_inches='tight')  # Use bbox_inches to ensure full legend display
    plt.close()

In [26]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '4_brain_ISSAAC_seq'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.355023,0.511901,0.530824,0.967721,0.478869,Garfield,4_brain_ISSAAC_seq
1,0.350469,0.513112,0.540713,0.954077,0.498653,Multigrate,4_brain_ISSAAC_seq
2,0.408146,0.521162,0.549681,0.971718,0.483725,MultiVI,4_brain_ISSAAC_seq
3,0.322902,0.500459,0.491447,0.959406,0.487024,MOFA,4_brain_ISSAAC_seq
4,0.403492,0.518850,0.580678,0.983473,0.401643,Seurat,4_brain_ISSAAC_seq

#### 探索一下用最佳分辨率

In [6]:
# calculate the metrics based on the best resolution
adata = count_metrics_for_best_resolution('4_brain_ISSAAC_seq')
adata

WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.4679116587409615
resolution: 0.2, nmi: 0.46953868634534324
resolution: 0.3, nmi: 0.5073591774085828
resolution: 0.4, nmi: 0.5274331706107964
resolution: 0.5, nmi: 0.5290364941284094
resolution: 0.6, nmi: 0.5241942609308612
resolution: 0.7, nmi: 0.5356521258957119
resolution: 0.8, nmi: 0.5308954787785267
resolution: 0.9, nmi: 0.5256782772555346
resolution: 1.0, nmi: 0.5233423755749724
resolution: 1.1, nmi: 0.5127526275980276
resolution: 1.2, nmi: 0.5161950286110775
resolution: 1.3, nmi: 0.5227922374428045
resolution: 1.4, nmi: 0.517237063847293
resolution: 1.5, nmi: 0.5138358942781424
resolution: 1.6, nmi: 0.509028087937334
resolution: 1.7, nmi: 0.5211717453501659
resolution: 1.8, nmi: 0.5152012781627139
resolution: 1.9, nmi: 0.5131925501842107
resolution: 2.0, nmi: 0.5141684337350988
optimised clustering against cell_type
optimal cluster resolution: 0.7
optimal score: 0.5356521258957119
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.37370868028359755
resolution: 0.2, nmi: 0.465502679436731
resolution: 0.3, nmi: 0.5071532357848952
resolution: 0.4, nmi: 0.5359732299942658
resolution: 0.5, nmi: 0.544594358924929
resolution: 0.6, nmi: 0.5537145452675335
resolution: 0.7, nmi: 0.5589559948603018
resolution: 0.8, nmi: 0.5387231374140987
resolution: 0.9, nmi: 0.5456731115616729
resolution: 1.0, nmi: 0.5361316119865691
resolution: 1.1, nmi: 0.5350689188617066
resolution: 1.2, nmi: 0.5370450874516408
resolution: 1.3, nmi: 0.52580606822938
resolution: 1.4, nmi: 0.5196151402441725
resolution: 1.5, nmi: 0.5277401926219928
resolution: 1.6, nmi: 0.5215515767046538
resolution: 1.7, nmi: 0.5294000635541234
resolution: 1.8, nmi: 0.523684590891932
resolution: 1.9, nmi: 0.5184810079330396
resolution: 2.0, nmi: 0.5230993604971708
optimised clustering against cell_type
optimal cluster resolution: 0.7
optimal score: 0.5589559948603018
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.47701878383940144
resolution: 0.2, nmi: 0.553182354878818
resolution: 0.3, nmi: 0.5526734741451422
resolution: 0.4, nmi: 0.5492701974176315
resolution: 0.5, nmi: 0.5574635764173334
resolution: 0.6, nmi: 0.5635832726034524
resolution: 0.7, nmi: 0.5472473767818719
resolution: 0.8, nmi: 0.540731160938655
resolution: 0.9, nmi: 0.5478523680333444
resolution: 1.0, nmi: 0.5493555503590283
resolution: 1.1, nmi: 0.5385981658358358
resolution: 1.2, nmi: 0.5357457637746076
resolution: 1.3, nmi: 0.5346008110134608
resolution: 1.4, nmi: 0.538502110279857
resolution: 1.5, nmi: 0.5340470192671916
resolution: 1.6, nmi: 0.532848687211124
resolution: 1.7, nmi: 0.5308497383357345
resolution: 1.8, nmi: 0.5273008448595324
resolution: 1.9, nmi: 0.5204299029660981
resolution: 2.0, nmi: 0.5228058109135216
optimised clustering against cell_type
optimal cluster resolution: 0.6
optimal score: 0.5635832726034524
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.43767449031218836
resolution: 0.2, nmi: 0.44806968139704956
resolution: 0.3, nmi: 0.47874789726741124
resolution: 0.4, nmi: 0.48413577439257316
resolution: 0.5, nmi: 0.4973058338335551
resolution: 0.6, nmi: 0.47924640313426126
resolution: 0.7, nmi: 0.49365208291296586
resolution: 0.8, nmi: 0.48385217228387756
resolution: 0.9, nmi: 0.4886456761926068
resolution: 1.0, nmi: 0.49327178285121775
resolution: 1.1, nmi: 0.48987233152050447
resolution: 1.2, nmi: 0.4907757880648215
resolution: 1.3, nmi: 0.4792948881138286
resolution: 1.4, nmi: 0.49034681350493875
resolution: 1.5, nmi: 0.48535440197930146
resolution: 1.6, nmi: 0.4757624695893923
resolution: 1.7, nmi: 0.47894012549367654
resolution: 1.8, nmi: 0.4895263511940095
resolution: 1.9, nmi: 0.4743667364251531
resolution: 2.0, nmi: 0.48492250612502313
optimised clustering against cell_type
optimal cluster resolution: 0.5
optimal score: 0.4973058338335551
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.5834351120265934
resolution: 0.2, nmi: 0.5677640806161899
resolution: 0.3, nmi: 0.5609727856461183
resolution: 0.4, nmi: 0.5567014144087016
resolution: 0.5, nmi: 0.5424817515369303
resolution: 0.6, nmi: 0.5322667218796986
resolution: 0.7, nmi: 0.5357007544351101
resolution: 0.8, nmi: 0.5331169693382797
resolution: 0.9, nmi: 0.5338203481707945
resolution: 1.0, nmi: 0.5344482729439439
resolution: 1.1, nmi: 0.529017882542629
resolution: 1.2, nmi: 0.5303925721749525
resolution: 1.3, nmi: 0.5272248054529015
resolution: 1.4, nmi: 0.525909788163337
resolution: 1.5, nmi: 0.5219183238383946
resolution: 1.6, nmi: 0.5199916779529828
resolution: 1.7, nmi: 0.5214892396396237
resolution: 1.8, nmi: 0.5192816029084636
resolution: 1.9, nmi: 0.5176580285469435
resolution: 2.0, nmi: 0.5128610544001599
optimised clustering against cell_type
optimal cluster resolution: 0.1
optimal score: 0.5834351120265934
Chunk 766 does not have enough neighbors. Skipping...
Chunk 1157 does not have enough neighbors. Skipping...
Chunk 1459 does not have enough neighbors. Skipping...
Chunk 2504 does not have enough neighbors. Skipping...
Chunk 3266 does not have enough neighbors. Skipping...
Chunk 3631 does not have enough neighbors. Skipping...
Chunk 3643 does not have enough neighbors. Skipping...
Chunk 4018 does not have enough neighbors. Skipping...
Chunk 4731 does not have enough neighbors. Skipping...
Chunk 4849 does not have enough neighbors. Skipping...
Chunk 4916 does not have enough neighbors. Skipping...
Chunk 5120 does not have enough neighbors. Skipping...
Chunk 5129 does not have enough neighbors. Skipping...
Chunk 5560 does not have enough neighbors. Skipping...
Chunk 5614 does not have enough neighbors. Skipping...
Chunk 5857 does not have enough neighbors. Skipping...
Chunk 5949 does not have enough neighbors. Skipping...
Chunk 6371 does not have enough neighbors. Skipping...
Chunk 6393 does not have enough neighbors. Skipping...
Chunk 6444 does not have enough neighbors. Skipping...
Chunk 6527 does not have enough neighbors. Skipping...
Chunk 6548 does not have enough neighbors. Skipping...
Chunk 6583 does not have enough neighbors. Skipping...
Chunk 6627 does not have enough neighbors. Skipping...
Chunk 6735 does not have enough neighbors. Skipping...
Chunk 6781 does not have enough neighbors. Skipping...
Chunk 6845 does not have enough neighbors. Skipping...
Chunk 6996 does not have enough neighbors. Skipping...
Chunk 7026 does not have enough neighbors. Skipping...
Chunk 7104 does not have enough neighbors. Skipping...
Chunk 7107 does not have enough neighbors. Skipping...
Chunk 7134 does not have enough neighbors. Skipping...
Chunk 7440 does not have enough neighbors. Skipping...
Chunk 8009 does not have enough neighbors. Skipping...
Chunk 8060 does not have enough neighbors. Skipping...
Chunk 8267 does not have enough neighbors. Skipping...
Chunk 8290 does not have enough neighbors. Skipping...
Chunk 8300 does not have enough neighbors. Skipping...
Chunk 8419 does not have enough neighbors. Skipping...
Chunk 8680 does not have enough neighbors. Skipping...
Chunk 8694 does not have enough neighbors. Skipping...
Chunk 8865 does not have enough neighbors. Skipping...
Chunk 8968 does not have enough neighbors. Skipping...
Chunk 8994 does not have enough neighbors. Skipping...
Chunk 9001 does not have enough neighbors. Skipping...
Chunk 9026 does not have enough neighbors. Skipping...
Chunk 9535 does not have enough neighbors. Skipping...
Chunk 9593 does not have enough neighbors. Skipping...
Chunk 9671 does not have enough neighbors. Skipping...
Chunk 9760 does not have enough neighbors. Skipping...
Chunk 9797 does not have enough neighbors. Skipping...
Chunk 9894 does not have enough neighbors. Skipping...
Chunk 9925 does not have enough neighbors. Skipping...
Chunk 10020 does not have enough neighbors. Skipping...
Chunk 10178 does not have enough neighbors. Skipping...
Chunk 10230 does not have enough neighbors. Skipping...
Chunk 10250 does not have enough neighbors. Skipping...
Chunk 10276 does not have enough neighbors. Skipping...
4_brain_ISSAAC_seq

AnnData object with n_obs × n_vars = 10361 × 13000
    obs: 'group', 'cell_type', 'batch', 'silhouette_temp', 'cluster'
    var: 'modality'
    uns: 'modality_lengths', 'neighbors', 'umap', 'cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'distances', 'connectivities'

In [7]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '4_brain_ISSAAC_seq'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result_best_reso.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.383082,0.511901,0.535652,0.967721,0.478869,Garfield,4_brain_ISSAAC_seq
1,0.482315,0.513112,0.558956,0.954077,0.498653,Multigrate,4_brain_ISSAAC_seq
2,0.478640,0.521162,0.563583,0.971718,0.483725,MultiVI,4_brain_ISSAAC_seq
3,0.374167,0.500459,0.497306,0.959406,0.487024,MOFA,4_brain_ISSAAC_seq
4,0.429688,0.518850,0.583435,0.983473,0.401643,Seurat,4_brain_ISSAAC_seq

#### 利用最佳分辨率计算指标(Garfield);

In [22]:
## 记录resolution
reso_dict = {
    '4_brain_ISSAAC_seq': {
        'Garfield': 0.7, # 0.8800000000000003,
        'Multigrate': 1.2400000000000007,
        'MultiVI': 0.8300000000000003,
        'MOFA': 0.9200000000000004,
        'Seurat': 0.11438396227480506, #0.11438396227480506
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('4_brain_ISSAAC_seq', reso_dict=reso_dict, 
                                     start=0.5, end=0.75, increment=0.05)
adata

the length of cell type: 20
method_reso is not None, using the 0.7 as resolution for Garfield...
Number of clusters: 18
the length of cell type: 20
method_reso is not None, using the 1.2400000000000007 as resolution for Multigrate...
Number of clusters: 20
the length of cell type: 20
method_reso is not None, using the 0.8300000000000003 as resolution for MultiVI...
Number of clusters: 20
the length of cell type: 20
method_reso is not None, using the 0.9200000000000004 as resolution for MOFA...
Number of clusters: 20
the length of cell type: 20
method_reso is not None, using the 0.11438396227480506 as resolution for Seurat...
Number of clusters: 20
Chunk 766 does not have enough neighbors. Skipping...
Chunk 1157 does not have enough neighbors. Skipping...
Chunk 1459 does not have enough neighbors. Skipping...
Chunk 2504 does not have enough neighbors. Skipping...
Chunk 3266 does not have enough neighbors. Skipping...
Chunk 3631 does not have enough neighbors. Skipping...
Chunk 3643 does not have enough neighbors. Skipping...
Chunk 4018 does not have enough neighbors. Skipping...
Chunk 4731 does not have enough neighbors. Skipping...
Chunk 4849 does not have enough neighbors. Skipping...
Chunk 4916 does not have enough neighbors. Skipping...
Chunk 5120 does not have enough neighbors. Skipping...
Chunk 5129 does not have enough neighbors. Skipping...
Chunk 5560 does not have enough neighbors. Skipping...
Chunk 5614 does not have enough neighbors. Skipping...
Chunk 5857 does not have enough neighbors. Skipping...
Chunk 5949 does not have enough neighbors. Skipping...
Chunk 6371 does not have enough neighbors. Skipping...
Chunk 6393 does not have enough neighbors. Skipping...
Chunk 6444 does not have enough neighbors. Skipping...
Chunk 6527 does not have enough neighbors. Skipping...
Chunk 6548 does not have enough neighbors. Skipping...
Chunk 6583 does not have enough neighbors. Skipping...
Chunk 6627 does not have enough neighbors. Skipping...
Chunk 6735 does not have enough neighbors. Skipping...
Chunk 6781 does not have enough neighbors. Skipping...
Chunk 6845 does not have enough neighbors. Skipping...
Chunk 6996 does not have enough neighbors. Skipping...
Chunk 7026 does not have enough neighbors. Skipping...
Chunk 7104 does not have enough neighbors. Skipping...
Chunk 7107 does not have enough neighbors. Skipping...
Chunk 7134 does not have enough neighbors. Skipping...
Chunk 7440 does not have enough neighbors. Skipping...
Chunk 8009 does not have enough neighbors. Skipping...
Chunk 8060 does not have enough neighbors. Skipping...
Chunk 8267 does not have enough neighbors. Skipping...
Chunk 8290 does not have enough neighbors. Skipping...
Chunk 8300 does not have enough neighbors. Skipping...
Chunk 8419 does not have enough neighbors. Skipping...
Chunk 8680 does not have enough neighbors. Skipping...
Chunk 8694 does not have enough neighbors. Skipping...
Chunk 8865 does not have enough neighbors. Skipping...
Chunk 8968 does not have enough neighbors. Skipping...
Chunk 8994 does not have enough neighbors. Skipping...
Chunk 9001 does not have enough neighbors. Skipping...
Chunk 9026 does not have enough neighbors. Skipping...
Chunk 9535 does not have enough neighbors. Skipping...
Chunk 9593 does not have enough neighbors. Skipping...
Chunk 9671 does not have enough neighbors. Skipping...
Chunk 9760 does not have enough neighbors. Skipping...
Chunk 9797 does not have enough neighbors. Skipping...
Chunk 9894 does not have enough neighbors. Skipping...
Chunk 9925 does not have enough neighbors. Skipping...
Chunk 10020 does not have enough neighbors. Skipping...
Chunk 10178 does not have enough neighbors. Skipping...
Chunk 10230 does not have enough neighbors. Skipping...
Chunk 10250 does not have enough neighbors. Skipping...
Chunk 10276 does not have enough neighbors. Skipping...
4_brain_ISSAAC_seq

AnnData object with n_obs × n_vars = 10361 × 13000
    obs: 'group', 'cell_type', 'batch', 'Garfield_cluster', 'silhouette_temp', 'Multigrate_cluster', 'MultiVI_cluster', 'MOFA_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'MultiVI', 'MultiVI_cluster', 'MOFA', 'MOFA_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'MultiVI_distances', 'MultiVI_connectivities', 'MOFA_distances', 'MOFA_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [23]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '4_brain_ISSAAC_seq'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.383082,0.511901,0.535652,0.967721,0.478869,Garfield,4_brain_ISSAAC_seq
1,0.350469,0.513112,0.540713,0.954077,0.498653,Multigrate,4_brain_ISSAAC_seq
2,0.408146,0.521162,0.549681,0.971718,0.483725,MultiVI,4_brain_ISSAAC_seq
3,0.322902,0.500459,0.491447,0.959406,0.487024,MOFA,4_brain_ISSAAC_seq
4,0.403492,0.518850,0.580678,0.983473,0.401643,Seurat,4_brain_ISSAAC_seq

### 数据集 3_brain_SNARE

In [16]:
## 记录resolution
reso_dict = {
    '3_brain_SNARE': {
        'Garfield': 0.6500000000000001,
        'Multigrate': 1.4500000000000008,
        'MultiVI': 0.2952450000000001,
        'MOFA': 0.5,
        'Seurat': 0.10294556604732455,
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('3_brain_SNARE', reso_dict=reso_dict)
adata

the length of cell type: 13
method_reso is not None, using the 0.6500000000000001 as resolution for Garfield...
Number of clusters: 13
the length of cell type: 13
method_reso is not None, using the 1.4500000000000008 as resolution for Multigrate...
Number of clusters: 13
the length of cell type: 13
method_reso is not None, using the 0.2952450000000001 as resolution for MultiVI...
Number of clusters: 13
the length of cell type: 13
method_reso is not None, using the 0.5 as resolution for MOFA...
Number of clusters: 13
the length of cell type: 13
Searching resolution for Seurat...
Searching resolution...
resolution=1.9500000000000013, cluster number=68
resolution=1.9000000000000012, cluster number=65
resolution=1.8500000000000012, cluster number=63
resolution=1.8000000000000012, cluster number=62
resolution=1.750000000000001, cluster number=61
resolution=1.700000000000001, cluster number=61
resolution=1.650000000000001, cluster number=60
resolution=1.600000000000001, cluster number=60
resolution=1.550000000000001, cluster number=59
resolution=1.5000000000000009, cluster number=57
resolution=1.4500000000000008, cluster number=56
resolution=1.4000000000000008, cluster number=54
resolution=1.3500000000000008, cluster number=52
resolution=1.3000000000000007, cluster number=50
resolution=1.2500000000000007, cluster number=46
resolution=1.2000000000000006, cluster number=47
resolution=1.1500000000000006, cluster number=49
resolution=1.1000000000000005, cluster number=48
resolution=1.0500000000000005, cluster number=42
resolution=1.0000000000000004, cluster number=43
resolution=0.9500000000000004, cluster number=44
resolution=0.9000000000000004, cluster number=43
resolution=0.8500000000000003, cluster number=42
resolution=0.8000000000000003, cluster number=39
resolution=0.7500000000000002, cluster number=40
resolution=0.7000000000000002, cluster number=38
resolution=0.6500000000000001, cluster number=35
resolution=0.6000000000000001, cluster number=35
resolution=0.55, cluster number=33
resolution=0.5, cluster number=32
Expanding search range: new range (0.45, 0.7875)
resolution=0.75, cluster number=40
resolution=0.7, cluster number=38
resolution=0.6499999999999999, cluster number=35
resolution=0.6, cluster number=35
resolution=0.55, cluster number=33
resolution=0.5, cluster number=32
resolution=0.45, cluster number=29
Expanding search range: new range (0.405, 0.70875)
resolution=0.705, cluster number=38
resolution=0.655, cluster number=35
resolution=0.605, cluster number=35
resolution=0.5549999999999999, cluster number=35
resolution=0.505, cluster number=32
resolution=0.455, cluster number=29
resolution=0.405, cluster number=28
Expanding search range: new range (0.36450000000000005, 0.6378750000000001)
resolution=0.6145, cluster number=36
resolution=0.5645, cluster number=35
resolution=0.5145, cluster number=34
resolution=0.4645, cluster number=31
resolution=0.41450000000000004, cluster number=28
resolution=0.36450000000000005, cluster number=24
Expanding search range: new range (0.32805000000000006, 0.5740875000000001)
resolution=0.52805, cluster number=34
resolution=0.47805000000000003, cluster number=32
resolution=0.42805000000000004, cluster number=27
resolution=0.37805000000000005, cluster number=27
resolution=0.32805000000000006, cluster number=24
Expanding search range: new range (0.2952450000000001, 0.5166787500000002)
resolution=0.49524500000000005, cluster number=32
resolution=0.44524500000000006, cluster number=28
resolution=0.39524500000000007, cluster number=26
resolution=0.3452450000000001, cluster number=25
resolution=0.2952450000000001, cluster number=23
Expanding search range: new range (0.2657205000000001, 0.46501087500000016)
resolution=0.41572050000000005, cluster number=28
resolution=0.36572050000000006, cluster number=24
resolution=0.31572050000000007, cluster number=22
resolution=0.2657205000000001, cluster number=23
Expanding search range: new range (0.23914845000000007, 0.4185097875000001)
resolution=0.38914845000000003, cluster number=26
resolution=0.33914845000000005, cluster number=25
resolution=0.28914845000000006, cluster number=23
resolution=0.23914845000000007, cluster number=22
Expanding search range: new range (0.21523360500000008, 0.37665880875000013)
resolution=0.3652336050000001, cluster number=24
resolution=0.3152336050000001, cluster number=22
resolution=0.2652336050000001, cluster number=23
resolution=0.21523360500000008, cluster number=20
Expanding search range: new range (0.19371024450000007, 0.3389929278750001)
resolution=0.29371024450000005, cluster number=23
resolution=0.24371024450000006, cluster number=22
resolution=0.19371024450000007, cluster number=20
Expanding search range: new range (0.17433922005000008, 0.30509363508750015)
resolution=0.27433922005000005, cluster number=22
resolution=0.22433922005000007, cluster number=21
resolution=0.17433922005000008, cluster number=20
Expanding search range: new range (0.15690529804500009, 0.27458427157875015)
resolution=0.25690529804500006, cluster number=22
resolution=0.20690529804500007, cluster number=20
resolution=0.15690529804500009, cluster number=16
Expanding search range: new range (0.14121476824050008, 0.24712584442087515)
resolution=0.24121476824050012, cluster number=22
resolution=0.1912147682405001, cluster number=20
resolution=0.14121476824050008, cluster number=16
Expanding search range: new range (0.12709329141645007, 0.2224132599787876)
resolution=0.17709329141645008, cluster number=18
resolution=0.12709329141645007, cluster number=14
Expanding search range: new range (0.11438396227480506, 0.20017193398090885)
resolution=0.16438396227480506, cluster number=17
resolution=0.11438396227480506, cluster number=14
Expanding search range: new range (0.10294556604732455, 0.18015474058281797)
resolution=0.15294556604732457, cluster number=16
resolution=0.10294556604732455, cluster number=13
Number of clusters: 13
3_brain_SNARE

AnnData object with n_obs × n_vars = 8055 × 13000
    obs: 'group', 'cell_type', 'batch', 'Garfield_cluster', 'silhouette_temp', 'Multigrate_cluster', 'MultiVI_cluster', 'MOFA_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'MultiVI', 'MultiVI_cluster', 'MOFA', 'MOFA_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'MultiVI_distances', 'MultiVI_connectivities', 'MOFA_distances', 'MOFA_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [17]:
import matplotlib.pyplot as plt

dataset = '3_brain_SNARE'
res_dir = f'/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC/{dataset}'

latent_key_list = ['Garfield', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat']
for latent_key in latent_key_list:
    sc.tl.umap(adata, neighbors_key=latent_key)
    latent_key_cluster = latent_key + '_cluster'
    
    # Create a new figure for each plot with an appropriate size
    plt.figure(figsize=(12, 6))  # Adjust the figsize as needed
    sc.pl.umap(adata, color=['cell_type', latent_key_cluster], wspace=0.5, hspace=0.5, show=False, ncols=2)
    # Save the figure
    plt.savefig(res_dir + f"/{latent_key}_UMAP_clusters.png", bbox_inches='tight')  # Use bbox_inches to ensure full legend display
    plt.close()

In [19]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '3_brain_SNARE'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.568369,0.616415,0.721559,0.993765,0.606543,Garfield,3_brain_SNARE
1,0.388010,0.540925,0.582473,0.962407,0.535359,Multigrate,3_brain_SNARE
2,0.387346,0.604648,0.587641,0.989677,0.548244,MultiVI,3_brain_SNARE
3,0.416283,0.525512,0.616441,0.988326,0.562822,MOFA,3_brain_SNARE
4,0.578907,0.786710,0.745991,0.998353,0.707169,Seurat,3_brain_SNARE

#### 探索一下用最佳分辨率

In [8]:
# calculate the metrics based on the best resolution
adata = count_metrics_for_best_resolution('3_brain_SNARE')
adata

WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.6792656140943156
resolution: 0.2, nmi: 0.7108192605432453
resolution: 0.3, nmi: 0.7265615194043833
resolution: 0.4, nmi: 0.7394168432821027
resolution: 0.5, nmi: 0.7232830381888907
resolution: 0.6, nmi: 0.7320908320188952
resolution: 0.7, nmi: 0.7018328715018829
resolution: 0.8, nmi: 0.6845877370400282
resolution: 0.9, nmi: 0.683113660570257
resolution: 1.0, nmi: 0.6794504956749007
resolution: 1.1, nmi: 0.6770522886299539
resolution: 1.2, nmi: 0.6607830254277536
resolution: 1.3, nmi: 0.6607373415349395
resolution: 1.4, nmi: 0.6482328063061619
resolution: 1.5, nmi: 0.652008213753001
resolution: 1.6, nmi: 0.6484879455354954
resolution: 1.7, nmi: 0.6421130323509258
resolution: 1.8, nmi: 0.624447532980517
resolution: 1.9, nmi: 0.6166676990694565
resolution: 2.0, nmi: 0.6112489270687637
optimised clustering against cell_type
optimal cluster resolution: 0.4
optimal score: 0.7394168432821027
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.5065707027914722
resolution: 0.2, nmi: 0.6453234949416238
resolution: 0.3, nmi: 0.6409904818250401
resolution: 0.4, nmi: 0.6628930413934003
resolution: 0.5, nmi: 0.672762327899007
resolution: 0.6, nmi: 0.645841172651987
resolution: 0.7, nmi: 0.636631544209751
resolution: 0.8, nmi: 0.6427885129113883
resolution: 0.9, nmi: 0.6162047812269031
resolution: 1.0, nmi: 0.5916826237899859
resolution: 1.1, nmi: 0.5836911679832867
resolution: 1.2, nmi: 0.5908120151877616
resolution: 1.3, nmi: 0.5802794959556027
resolution: 1.4, nmi: 0.5773142540730809
resolution: 1.5, nmi: 0.5749941669176093
resolution: 1.6, nmi: 0.5729739094659355
resolution: 1.7, nmi: 0.5762847347700446
resolution: 1.8, nmi: 0.5827869385842014
resolution: 1.9, nmi: 0.5769166818977082
resolution: 2.0, nmi: 0.5760964067252832
optimised clustering against cell_type
optimal cluster resolution: 0.5
optimal score: 0.672762327899007
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.6179645707203033
resolution: 0.2, nmi: 0.583669751464662
resolution: 0.3, nmi: 0.5873632012617731
resolution: 0.4, nmi: 0.5572651756983964
resolution: 0.5, nmi: 0.5614829652018039
resolution: 0.6, nmi: 0.5610639051415723
resolution: 0.7, nmi: 0.5421677931837622
resolution: 0.8, nmi: 0.5389715655134216
resolution: 0.9, nmi: 0.5428071129205049
resolution: 1.0, nmi: 0.5383635057971642
resolution: 1.1, nmi: 0.5349183966157329
resolution: 1.2, nmi: 0.5320510162278641
resolution: 1.3, nmi: 0.5318069293590904
resolution: 1.4, nmi: 0.5324369236674831
resolution: 1.5, nmi: 0.5260003265304665
resolution: 1.6, nmi: 0.527392324880937
resolution: 1.7, nmi: 0.5154702647153219
resolution: 1.8, nmi: 0.5172877155084554
resolution: 1.9, nmi: 0.5096960776401459
resolution: 2.0, nmi: 0.5152315611100144
optimised clustering against cell_type
optimal cluster resolution: 0.1
optimal score: 0.6179645707203033
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.668106244197417
resolution: 0.2, nmi: 0.6864576903119333
resolution: 0.3, nmi: 0.6330742206322433
resolution: 0.4, nmi: 0.6326995636302537
resolution: 0.5, nmi: 0.6164409190821815
resolution: 0.6, nmi: 0.6044481258974372
resolution: 0.7, nmi: 0.5950376430777224
resolution: 0.8, nmi: 0.5821376700679612
resolution: 0.9, nmi: 0.5751497349862158
resolution: 1.0, nmi: 0.580772659862213
resolution: 1.1, nmi: 0.5671804784048212
resolution: 1.2, nmi: 0.5611012828446875
resolution: 1.3, nmi: 0.5654573510864261
resolution: 1.4, nmi: 0.5513125337592809
resolution: 1.5, nmi: 0.5513741571603903
resolution: 1.6, nmi: 0.5473586500608519
resolution: 1.7, nmi: 0.5388765705928656
resolution: 1.8, nmi: 0.5346602385447006
resolution: 1.9, nmi: 0.5242305336065878
resolution: 2.0, nmi: 0.538072359145924
optimised clustering against cell_type
optimal cluster resolution: 0.2
optimal score: 0.6864576903119333
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.7459913867046017
resolution: 0.2, nmi: 0.6994750595570758
resolution: 0.3, nmi: 0.6765484114276329
resolution: 0.4, nmi: 0.6468647592667398
resolution: 0.5, nmi: 0.6310986120939635
resolution: 0.6, nmi: 0.6243779871008804
resolution: 0.7, nmi: 0.6147650637754078
resolution: 0.8, nmi: 0.6124499681089879
resolution: 0.9, nmi: 0.6020301419422373
resolution: 1.0, nmi: 0.6021977486705915
resolution: 1.1, nmi: 0.5908018551082744
resolution: 1.2, nmi: 0.5936860823610401
resolution: 1.3, nmi: 0.58884382815437
resolution: 1.4, nmi: 0.581602455481446
resolution: 1.5, nmi: 0.5756838584284241
resolution: 1.6, nmi: 0.5734334606967515
resolution: 1.7, nmi: 0.5715172068587515
resolution: 1.8, nmi: 0.5702229564394317
resolution: 1.9, nmi: 0.5660483355121385
resolution: 2.0, nmi: 0.5616648743654604
optimised clustering against cell_type
optimal cluster resolution: 0.1
optimal score: 0.7459913867046017
3_brain_SNARE

AnnData object with n_obs × n_vars = 8055 × 13000
    obs: 'group', 'cell_type', 'batch', 'silhouette_temp', 'cluster'
    var: 'modality'
    uns: 'modality_lengths', 'neighbors', 'umap', 'cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'distances', 'connectivities'

In [9]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '3_brain_SNARE'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result_best_reso.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.678792,0.616415,0.739417,0.993765,0.606543,Garfield,3_brain_SNARE
1,0.582377,0.540925,0.672762,0.962407,0.535359,Multigrate,3_brain_SNARE
2,0.544277,0.604648,0.617965,0.989677,0.548244,MultiVI,3_brain_SNARE
3,0.600631,0.525512,0.686458,0.988326,0.562822,MOFA,3_brain_SNARE
4,0.578907,0.786710,0.745991,0.998353,0.707169,Seurat,3_brain_SNARE

#### 利用最佳分辨率计算指标(Garfield);

In [24]:
## 记录resolution
reso_dict = {
    '3_brain_SNARE': {
        'Garfield': 0.4, # 0.6500000000000001,
        'Multigrate': 1.4500000000000008,
        'MultiVI': 0.2952450000000001,
        'MOFA': 0.5,
        'Seurat': 0.10294556604732455,
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('3_brain_SNARE', reso_dict=reso_dict)
adata

the length of cell type: 13
method_reso is not None, using the 0.4 as resolution for Garfield...
Number of clusters: 11
the length of cell type: 13
method_reso is not None, using the 1.4500000000000008 as resolution for Multigrate...
Number of clusters: 13
the length of cell type: 13
method_reso is not None, using the 0.2952450000000001 as resolution for MultiVI...
Number of clusters: 13
the length of cell type: 13
method_reso is not None, using the 0.5 as resolution for MOFA...
Number of clusters: 13
the length of cell type: 13
method_reso is not None, using the 0.10294556604732455 as resolution for Seurat...
Number of clusters: 13
3_brain_SNARE

AnnData object with n_obs × n_vars = 8055 × 13000
    obs: 'group', 'cell_type', 'batch', 'Garfield_cluster', 'silhouette_temp', 'Multigrate_cluster', 'MultiVI_cluster', 'MOFA_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'MultiVI', 'MultiVI_cluster', 'MOFA', 'MOFA_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'MultiVI_distances', 'MultiVI_connectivities', 'MOFA_distances', 'MOFA_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [25]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '3_brain_SNARE'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.678792,0.616415,0.739417,0.993765,0.606543,Garfield,3_brain_SNARE
1,0.388010,0.540925,0.582473,0.962407,0.535359,Multigrate,3_brain_SNARE
2,0.387346,0.604648,0.587641,0.989677,0.548244,MultiVI,3_brain_SNARE
3,0.416283,0.525512,0.616441,0.988326,0.562822,MOFA,3_brain_SNARE
4,0.578907,0.786710,0.745991,0.998353,0.707169,Seurat,3_brain_SNARE

### 数据集 2_brain_ShareSeq

In [ ]:
# resolution: 'Garfield', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
# resolution=0.8000000000000003, cluster number=13
# resolution=1.600000000000001, cluster number=13
# resolution=0.39524500000000007, cluster number=13
# resolution=0.6000000000000001, cluster number=13
# resolution for Seurat: 0.44999999999999996

reso_dict = {
    '2_brain_ShareSeq': {
        'Garfield': 0.8000000000000003,
        'Multigrate': 1.600000000000001,
        'MultiVI': 0.39524500000000007,
        'MOFA': 0.6000000000000001,
        'Seurat': 0.44999999999999996
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('2_brain_ShareSeq', reso_dict=None)
adata

In [21]:
## 重复结果
reso_dict = {
    '2_brain_ShareSeq': {
        'Garfield': 0.8000000000000003,
        'Multigrate': 1.600000000000001,
        'MultiVI': 0.39524500000000007,
        'MOFA': 0.6000000000000001,
        'Seurat': 0.10294556604732455
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('2_brain_ShareSeq', reso_dict)
adata

the length of cell type: 13
method_reso is not None, using the 0.8000000000000003 as resolution for Garfield...
Number of clusters: 13
the length of cell type: 13
method_reso is not None, using the 1.600000000000001 as resolution for Multigrate...
Number of clusters: 13
the length of cell type: 13
method_reso is not None, using the 0.39524500000000007 as resolution for MultiVI...
Number of clusters: 13
the length of cell type: 13
method_reso is not None, using the 0.6000000000000001 as resolution for MOFA...
Number of clusters: 13
Chunk 8 does not have enough neighbors. Skipping...
Chunk 14 does not have enough neighbors. Skipping...
Chunk 157 does not have enough neighbors. Skipping...
Chunk 165 does not have enough neighbors. Skipping...
Chunk 206 does not have enough neighbors. Skipping...
Chunk 237 does not have enough neighbors. Skipping...
Chunk 251 does not have enough neighbors. Skipping...
Chunk 310 does not have enough neighbors. Skipping...
Chunk 396 does not have enough neighbors. Skipping...
Chunk 417 does not have enough neighbors. Skipping...
Chunk 464 does not have enough neighbors. Skipping...
Chunk 479 does not have enough neighbors. Skipping...
Chunk 485 does not have enough neighbors. Skipping...
Chunk 491 does not have enough neighbors. Skipping...
Chunk 498 does not have enough neighbors. Skipping...
Chunk 555 does not have enough neighbors. Skipping...
Chunk 649 does not have enough neighbors. Skipping...
Chunk 656 does not have enough neighbors. Skipping...
Chunk 663 does not have enough neighbors. Skipping...
Chunk 726 does not have enough neighbors. Skipping...
Chunk 749 does not have enough neighbors. Skipping...
Chunk 781 does not have enough neighbors. Skipping...
Chunk 795 does not have enough neighbors. Skipping...
Chunk 850 does not have enough neighbors. Skipping...
Chunk 852 does not have enough neighbors. Skipping...
Chunk 889 does not have enough neighbors. Skipping...
Chunk 936 does not have enough neighbors. Skipping...
Chunk 995 does not have enough neighbors. Skipping...
Chunk 1163 does not have enough neighbors. Skipping...
Chunk 1173 does not have enough neighbors. Skipping...
Chunk 1274 does not have enough neighbors. Skipping...
Chunk 1387 does not have enough neighbors. Skipping...
Chunk 1405 does not have enough neighbors. Skipping...
Chunk 1458 does not have enough neighbors. Skipping...
Chunk 1503 does not have enough neighbors. Skipping...
Chunk 1508 does not have enough neighbors. Skipping...
Chunk 1566 does not have enough neighbors. Skipping...
Chunk 1570 does not have enough neighbors. Skipping...
Chunk 1618 does not have enough neighbors. Skipping...
Chunk 1640 does not have enough neighbors. Skipping...
Chunk 1682 does not have enough neighbors. Skipping...
Chunk 1696 does not have enough neighbors. Skipping...
Chunk 1720 does not have enough neighbors. Skipping...
Chunk 1733 does not have enough neighbors. Skipping...
Chunk 1816 does not have enough neighbors. Skipping...
Chunk 1880 does not have enough neighbors. Skipping...
Chunk 1883 does not have enough neighbors. Skipping...
Chunk 1884 does not have enough neighbors. Skipping...
Chunk 1915 does not have enough neighbors. Skipping...
Chunk 1929 does not have enough neighbors. Skipping...
Chunk 1948 does not have enough neighbors. Skipping...
Chunk 2078 does not have enough neighbors. Skipping...
Chunk 2088 does not have enough neighbors. Skipping...
Chunk 2107 does not have enough neighbors. Skipping...
Chunk 2257 does not have enough neighbors. Skipping...
Chunk 2270 does not have enough neighbors. Skipping...
Chunk 2302 does not have enough neighbors. Skipping...
Chunk 2331 does not have enough neighbors. Skipping...
Chunk 2333 does not have enough neighbors. Skipping...
Chunk 2338 does not have enough neighbors. Skipping...
the length of cell type: 13
Searching resolution for Seurat...
Searching resolution...
resolution=1.9500000000000013, cluster number=44
resolution=1.9000000000000012, cluster number=41
resolution=1.8500000000000012, cluster number=42
resolution=1.8000000000000012, cluster number=42
resolution=1.750000000000001, cluster number=41
resolution=1.700000000000001, cluster number=41
resolution=1.650000000000001, cluster number=40
resolution=1.600000000000001, cluster number=40
resolution=1.550000000000001, cluster number=41
resolution=1.5000000000000009, cluster number=39
resolution=1.4500000000000008, cluster number=37
resolution=1.4000000000000008, cluster number=37
resolution=1.3500000000000008, cluster number=39
resolution=1.3000000000000007, cluster number=39
resolution=1.2500000000000007, cluster number=36
resolution=1.2000000000000006, cluster number=34
resolution=1.1500000000000006, cluster number=35
resolution=1.1000000000000005, cluster number=34
resolution=1.0500000000000005, cluster number=34
resolution=1.0000000000000004, cluster number=33
resolution=0.9500000000000004, cluster number=32
resolution=0.9000000000000004, cluster number=31
resolution=0.8500000000000003, cluster number=30
resolution=0.8000000000000003, cluster number=30
resolution=0.7500000000000002, cluster number=29
resolution=0.7000000000000002, cluster number=27
resolution=0.6500000000000001, cluster number=25
resolution=0.6000000000000001, cluster number=23
resolution=0.55, cluster number=21
resolution=0.5, cluster number=21
Expanding search range: new range (0.45, 0.7875)
resolution=0.75, cluster number=29
resolution=0.7, cluster number=27
resolution=0.6499999999999999, cluster number=25
resolution=0.6, cluster number=23
resolution=0.55, cluster number=21
resolution=0.5, cluster number=21
resolution=0.45, cluster number=20
Expanding search range: new range (0.405, 0.70875)
resolution=0.705, cluster number=27
resolution=0.655, cluster number=25
resolution=0.605, cluster number=24
resolution=0.5549999999999999, cluster number=21
resolution=0.505, cluster number=21
resolution=0.455, cluster number=21
resolution=0.405, cluster number=20
Expanding search range: new range (0.36450000000000005, 0.6378750000000001)
resolution=0.6145, cluster number=24
resolution=0.5645, cluster number=21
resolution=0.5145, cluster number=21
resolution=0.4645, cluster number=21
resolution=0.41450000000000004, cluster number=20
resolution=0.36450000000000005, cluster number=19
Expanding search range: new range (0.32805000000000006, 0.5740875000000001)
resolution=0.52805, cluster number=21
resolution=0.47805000000000003, cluster number=21
resolution=0.42805000000000004, cluster number=20
resolution=0.37805000000000005, cluster number=20
resolution=0.32805000000000006, cluster number=19
Expanding search range: new range (0.2952450000000001, 0.5166787500000002)
resolution=0.49524500000000005, cluster number=21
resolution=0.44524500000000006, cluster number=20
resolution=0.39524500000000007, cluster number=20
resolution=0.3452450000000001, cluster number=19
resolution=0.2952450000000001, cluster number=18
Expanding search range: new range (0.2657205000000001, 0.46501087500000016)
resolution=0.41572050000000005, cluster number=20
resolution=0.36572050000000006, cluster number=19
resolution=0.31572050000000007, cluster number=19
resolution=0.2657205000000001, cluster number=16
Expanding search range: new range (0.23914845000000007, 0.4185097875000001)
resolution=0.38914845000000003, cluster number=20
resolution=0.33914845000000005, cluster number=19
resolution=0.28914845000000006, cluster number=18
resolution=0.23914845000000007, cluster number=17
Expanding search range: new range (0.21523360500000008, 0.37665880875000013)
resolution=0.3652336050000001, cluster number=19
resolution=0.3152336050000001, cluster number=19
resolution=0.2652336050000001, cluster number=16
resolution=0.21523360500000008, cluster number=16
Expanding search range: new range (0.19371024450000007, 0.3389929278750001)
resolution=0.29371024450000005, cluster number=18
resolution=0.24371024450000006, cluster number=17
resolution=0.19371024450000007, cluster number=16
Expanding search range: new range (0.17433922005000008, 0.30509363508750015)
resolution=0.27433922005000005, cluster number=17
resolution=0.22433922005000007, cluster number=15
resolution=0.17433922005000008, cluster number=16
Expanding search range: new range (0.15690529804500009, 0.27458427157875015)
resolution=0.25690529804500006, cluster number=17
resolution=0.20690529804500007, cluster number=16
resolution=0.15690529804500009, cluster number=14
Expanding search range: new range (0.14121476824050008, 0.24712584442087515)
resolution=0.24121476824050012, cluster number=17
resolution=0.1912147682405001, cluster number=16
resolution=0.14121476824050008, cluster number=14
Expanding search range: new range (0.12709329141645007, 0.2224132599787876)
resolution=0.17709329141645008, cluster number=16
resolution=0.12709329141645007, cluster number=14
Expanding search range: new range (0.11438396227480506, 0.20017193398090885)
resolution=0.16438396227480506, cluster number=16
resolution=0.11438396227480506, cluster number=15
Expanding search range: new range (0.10294556604732455, 0.18015474058281797)
resolution=0.15294556604732457, cluster number=14
resolution=0.10294556604732455, cluster number=13
Number of clusters: 13
Chunk 8 does not have enough neighbors. Skipping...
Chunk 14 does not have enough neighbors. Skipping...
Chunk 157 does not have enough neighbors. Skipping...
Chunk 165 does not have enough neighbors. Skipping...
Chunk 206 does not have enough neighbors. Skipping...
Chunk 237 does not have enough neighbors. Skipping...
Chunk 251 does not have enough neighbors. Skipping...
Chunk 310 does not have enough neighbors. Skipping...
Chunk 396 does not have enough neighbors. Skipping...
Chunk 417 does not have enough neighbors. Skipping...
Chunk 464 does not have enough neighbors. Skipping...
Chunk 479 does not have enough neighbors. Skipping...
Chunk 485 does not have enough neighbors. Skipping...
Chunk 491 does not have enough neighbors. Skipping...
Chunk 498 does not have enough neighbors. Skipping...
Chunk 555 does not have enough neighbors. Skipping...
Chunk 649 does not have enough neighbors. Skipping...
Chunk 656 does not have enough neighbors. Skipping...
Chunk 663 does not have enough neighbors. Skipping...
Chunk 726 does not have enough neighbors. Skipping...
Chunk 749 does not have enough neighbors. Skipping...
Chunk 781 does not have enough neighbors. Skipping...
Chunk 795 does not have enough neighbors. Skipping...
Chunk 850 does not have enough neighbors. Skipping...
Chunk 852 does not have enough neighbors. Skipping...
Chunk 889 does not have enough neighbors. Skipping...
Chunk 936 does not have enough neighbors. Skipping...
Chunk 995 does not have enough neighbors. Skipping...
Chunk 1163 does not have enough neighbors. Skipping...
Chunk 1173 does not have enough neighbors. Skipping...
Chunk 1274 does not have enough neighbors. Skipping...
Chunk 1387 does not have enough neighbors. Skipping...
Chunk 1405 does not have enough neighbors. Skipping...
Chunk 1458 does not have enough neighbors. Skipping...
Chunk 1503 does not have enough neighbors. Skipping...
Chunk 1508 does not have enough neighbors. Skipping...
Chunk 1566 does not have enough neighbors. Skipping...
Chunk 1570 does not have enough neighbors. Skipping...
Chunk 1618 does not have enough neighbors. Skipping...
Chunk 1640 does not have enough neighbors. Skipping...
Chunk 1682 does not have enough neighbors. Skipping...
Chunk 1696 does not have enough neighbors. Skipping...
Chunk 1720 does not have enough neighbors. Skipping...
Chunk 1733 does not have enough neighbors. Skipping...
Chunk 1816 does not have enough neighbors. Skipping...
Chunk 1880 does not have enough neighbors. Skipping...
Chunk 1883 does not have enough neighbors. Skipping...
Chunk 1884 does not have enough neighbors. Skipping...
Chunk 1915 does not have enough neighbors. Skipping...
Chunk 1929 does not have enough neighbors. Skipping...
Chunk 1948 does not have enough neighbors. Skipping...
Chunk 2078 does not have enough neighbors. Skipping...
Chunk 2088 does not have enough neighbors. Skipping...
Chunk 2107 does not have enough neighbors. Skipping...
Chunk 2257 does not have enough neighbors. Skipping...
Chunk 2270 does not have enough neighbors. Skipping...
Chunk 2302 does not have enough neighbors. Skipping...
Chunk 2331 does not have enough neighbors. Skipping...
Chunk 2333 does not have enough neighbors. Skipping...
Chunk 2338 does not have enough neighbors. Skipping...
2_brain_ShareSeq

AnnData object with n_obs × n_vars = 2344 × 13000
    obs: 'group', 'cell_type', 'batch', 'Garfield_cluster', 'silhouette_temp', 'Multigrate_cluster', 'MultiVI_cluster', 'MOFA_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'MultiVI', 'MultiVI_cluster', 'MOFA', 'MOFA_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'MultiVI_distances', 'MultiVI_connectivities', 'MOFA_distances', 'MOFA_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [22]:
import matplotlib.pyplot as plt

dataset = '2_brain_ShareSeq'
res_dir = f'/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC/{dataset}'

latent_key_list = ['Garfield', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat']
for latent_key in latent_key_list:
    sc.tl.umap(adata, neighbors_key=latent_key)
    latent_key_cluster = latent_key + '_cluster'
    
    # Create a new figure for each plot with an appropriate size
    plt.figure(figsize=(12, 6))  # Adjust the figsize as needed
    sc.pl.umap(adata, color=['cell_type', latent_key_cluster], wspace=0.5, hspace=0.5, show=False, ncols=2)
    # Save the figure
    plt.savefig(res_dir + f"/{latent_key}_UMAP_clusters.png", bbox_inches='tight')  # Use bbox_inches to ensure full legend display
    plt.close()

In [23]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '2_brain_ShareSeq'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.400663,0.514628,0.589198,0.922453,0.495120,Garfield,2_brain_ShareSeq
1,0.174423,0.480161,0.378802,0.836010,0.474992,Multigrate,2_brain_ShareSeq
2,0.458934,0.643207,0.638186,0.970894,0.600148,MultiVI,2_brain_ShareSeq
3,0.451449,0.583920,0.639585,0.957829,0.560575,MOFA,2_brain_ShareSeq
4,0.465474,0.667899,0.647241,0.994003,0.604726,Seurat,2_brain_ShareSeq

#### 探索一下用最佳分辨率

In [10]:
# calculate the metrics based on the best resolution
adata = count_metrics_for_best_resolution('2_brain_ShareSeq')
adata

WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.42485459441957824
resolution: 0.2, nmi: 0.44297030507512464
resolution: 0.3, nmi: 0.5597662822684231
resolution: 0.4, nmi: 0.5045705935527509
resolution: 0.5, nmi: 0.5385360959021275
resolution: 0.6, nmi: 0.5597239391408851
resolution: 0.7, nmi: 0.5904612922311091
resolution: 0.8, nmi: 0.5891979594702375
resolution: 0.9, nmi: 0.5756272687504639
resolution: 1.0, nmi: 0.5848581661835602
resolution: 1.1, nmi: 0.5783837858075326
resolution: 1.2, nmi: 0.578370715418351
resolution: 1.3, nmi: 0.5814864955208765
resolution: 1.4, nmi: 0.5794902345302025
resolution: 1.5, nmi: 0.575751826768275
resolution: 1.6, nmi: 0.570890264579799
resolution: 1.7, nmi: 0.5694330542582511
resolution: 1.8, nmi: 0.577560478424967
resolution: 1.9, nmi: 0.5741297546744633
resolution: 2.0, nmi: 0.5678927011343805
optimised clustering against cell_type
optimal cluster resolution: 0.7
optimal score: 0.5904612922311091
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.3584263741322073
resolution: 0.2, nmi: 0.38818515145940385
resolution: 0.3, nmi: 0.4395569305220948
resolution: 0.4, nmi: 0.43921777517575483
resolution: 0.5, nmi: 0.4376979983746913
resolution: 0.6, nmi: 0.436210325870387
resolution: 0.7, nmi: 0.43835519086512825
resolution: 0.8, nmi: 0.4387223485402633
resolution: 0.9, nmi: 0.4383521994482284
resolution: 1.0, nmi: 0.4276865101140983
resolution: 1.1, nmi: 0.42532946186764287
resolution: 1.2, nmi: 0.41232534816105
resolution: 1.3, nmi: 0.4000574038992067
resolution: 1.4, nmi: 0.3984229578923373
resolution: 1.5, nmi: 0.3952214970339856
resolution: 1.6, nmi: 0.37880192568366466
resolution: 1.7, nmi: 0.3786171655551858
resolution: 1.8, nmi: 0.3704919659119545
resolution: 1.9, nmi: 0.3585610861515528
resolution: 2.0, nmi: 0.3591690861868545
optimised clustering against cell_type
optimal cluster resolution: 0.3
optimal score: 0.4395569305220948
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.49693574949368835
resolution: 0.2, nmi: 0.6062061876352401
resolution: 0.3, nmi: 0.6333132217890712
resolution: 0.4, nmi: 0.6449699553311549
resolution: 0.5, nmi: 0.6446547544711093
resolution: 0.6, nmi: 0.6398827066517031
resolution: 0.7, nmi: 0.6493604279128486
resolution: 0.8, nmi: 0.637883716022644
resolution: 0.9, nmi: 0.6290151627883025
resolution: 1.0, nmi: 0.6349216039749459
resolution: 1.1, nmi: 0.6220624792603321
resolution: 1.2, nmi: 0.624518608315444
resolution: 1.3, nmi: 0.6260419520061102
resolution: 1.4, nmi: 0.6201793490317763
resolution: 1.5, nmi: 0.6137405059514521
resolution: 1.6, nmi: 0.6183772077650235
resolution: 1.7, nmi: 0.6212605380043421
resolution: 1.8, nmi: 0.6151318222077853
resolution: 1.9, nmi: 0.6178884727694253
resolution: 2.0, nmi: 0.6186207000152165
optimised clustering against cell_type
optimal cluster resolution: 0.7
optimal score: 0.6493604279128486
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.6141521253339032
resolution: 0.2, nmi: 0.6673309851655341
resolution: 0.3, nmi: 0.6430191806659793
resolution: 0.4, nmi: 0.6604825018642899
resolution: 0.5, nmi: 0.6429792202964685
resolution: 0.6, nmi: 0.639584975756614
resolution: 0.7, nmi: 0.646034870945759
resolution: 0.8, nmi: 0.6404577643197641
resolution: 0.9, nmi: 0.6481018116998728
resolution: 1.0, nmi: 0.6438990840805829
resolution: 1.1, nmi: 0.6372828382264321
resolution: 1.2, nmi: 0.6287814443625062
resolution: 1.3, nmi: 0.6317051855601574
resolution: 1.4, nmi: 0.6213212078417149
resolution: 1.5, nmi: 0.6170033215090709
resolution: 1.6, nmi: 0.6097625805090425
resolution: 1.7, nmi: 0.6085767248196621
resolution: 1.8, nmi: 0.5922661017349927
resolution: 1.9, nmi: 0.5989845265684591
resolution: 2.0, nmi: 0.5927780373712488
optimised clustering against cell_type
optimal cluster resolution: 0.2
optimal score: 0.6673309851655341
Chunk 8 does not have enough neighbors. Skipping...
Chunk 14 does not have enough neighbors. Skipping...
Chunk 157 does not have enough neighbors. Skipping...
Chunk 165 does not have enough neighbors. Skipping...
Chunk 206 does not have enough neighbors. Skipping...
Chunk 237 does not have enough neighbors. Skipping...
Chunk 251 does not have enough neighbors. Skipping...
Chunk 310 does not have enough neighbors. Skipping...
Chunk 396 does not have enough neighbors. Skipping...
Chunk 417 does not have enough neighbors. Skipping...
Chunk 464 does not have enough neighbors. Skipping...
Chunk 479 does not have enough neighbors. Skipping...
Chunk 485 does not have enough neighbors. Skipping...
Chunk 491 does not have enough neighbors. Skipping...
Chunk 498 does not have enough neighbors. Skipping...
Chunk 555 does not have enough neighbors. Skipping...
Chunk 649 does not have enough neighbors. Skipping...
Chunk 656 does not have enough neighbors. Skipping...
Chunk 663 does not have enough neighbors. Skipping...
Chunk 726 does not have enough neighbors. Skipping...
Chunk 749 does not have enough neighbors. Skipping...
Chunk 781 does not have enough neighbors. Skipping...
Chunk 795 does not have enough neighbors. Skipping...
Chunk 850 does not have enough neighbors. Skipping...
Chunk 852 does not have enough neighbors. Skipping...
Chunk 889 does not have enough neighbors. Skipping...
Chunk 936 does not have enough neighbors. Skipping...
Chunk 995 does not have enough neighbors. Skipping...
Chunk 1163 does not have enough neighbors. Skipping...
Chunk 1173 does not have enough neighbors. Skipping...
Chunk 1274 does not have enough neighbors. Skipping...
Chunk 1387 does not have enough neighbors. Skipping...
Chunk 1405 does not have enough neighbors. Skipping...
Chunk 1458 does not have enough neighbors. Skipping...
Chunk 1503 does not have enough neighbors. Skipping...
Chunk 1508 does not have enough neighbors. Skipping...
Chunk 1566 does not have enough neighbors. Skipping...
Chunk 1570 does not have enough neighbors. Skipping...
Chunk 1618 does not have enough neighbors. Skipping...
Chunk 1640 does not have enough neighbors. Skipping...
Chunk 1682 does not have enough neighbors. Skipping...
Chunk 1696 does not have enough neighbors. Skipping...
Chunk 1720 does not have enough neighbors. Skipping...
Chunk 1733 does not have enough neighbors. Skipping...
Chunk 1816 does not have enough neighbors. Skipping...
Chunk 1880 does not have enough neighbors. Skipping...
Chunk 1883 does not have enough neighbors. Skipping...
Chunk 1884 does not have enough neighbors. Skipping...
Chunk 1915 does not have enough neighbors. Skipping...
Chunk 1929 does not have enough neighbors. Skipping...
Chunk 1948 does not have enough neighbors. Skipping...
Chunk 2078 does not have enough neighbors. Skipping...
Chunk 2088 does not have enough neighbors. Skipping...
Chunk 2107 does not have enough neighbors. Skipping...
Chunk 2257 does not have enough neighbors. Skipping...
Chunk 2270 does not have enough neighbors. Skipping...
Chunk 2302 does not have enough neighbors. Skipping...
Chunk 2331 does not have enough neighbors. Skipping...
Chunk 2333 does not have enough neighbors. Skipping...
Chunk 2338 does not have enough neighbors. Skipping...
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.6472405412049738
resolution: 0.2, nmi: 0.6740105802803464
resolution: 0.3, nmi: 0.6892851726464199
resolution: 0.4, nmi: 0.6811933361123297
resolution: 0.5, nmi: 0.6685800837878436
resolution: 0.6, nmi: 0.6607823345266358
resolution: 0.7, nmi: 0.6599684796593545
resolution: 0.8, nmi: 0.6448372559705244
resolution: 0.9, nmi: 0.6398646652133331
resolution: 1.0, nmi: 0.6455505225941341
resolution: 1.1, nmi: 0.6410296494524071
resolution: 1.2, nmi: 0.6430268937715322
resolution: 1.3, nmi: 0.6309719715764144
resolution: 1.4, nmi: 0.6336918529934479
resolution: 1.5, nmi: 0.631303924847936
resolution: 1.6, nmi: 0.6289956690095403
resolution: 1.7, nmi: 0.6268888081815186
resolution: 1.8, nmi: 0.6203894068919155
resolution: 1.9, nmi: 0.6278320837775256
resolution: 2.0, nmi: 0.6186047374323663
optimised clustering against cell_type
optimal cluster resolution: 0.3
optimal score: 0.6892851726464199
Chunk 8 does not have enough neighbors. Skipping...
Chunk 14 does not have enough neighbors. Skipping...
Chunk 157 does not have enough neighbors. Skipping...
Chunk 165 does not have enough neighbors. Skipping...
Chunk 206 does not have enough neighbors. Skipping...
Chunk 237 does not have enough neighbors. Skipping...
Chunk 251 does not have enough neighbors. Skipping...
Chunk 310 does not have enough neighbors. Skipping...
Chunk 396 does not have enough neighbors. Skipping...
Chunk 417 does not have enough neighbors. Skipping...
Chunk 464 does not have enough neighbors. Skipping...
Chunk 479 does not have enough neighbors. Skipping...
Chunk 485 does not have enough neighbors. Skipping...
Chunk 491 does not have enough neighbors. Skipping...
Chunk 498 does not have enough neighbors. Skipping...
Chunk 555 does not have enough neighbors. Skipping...
Chunk 649 does not have enough neighbors. Skipping...
Chunk 656 does not have enough neighbors. Skipping...
Chunk 663 does not have enough neighbors. Skipping...
Chunk 726 does not have enough neighbors. Skipping...
Chunk 749 does not have enough neighbors. Skipping...
Chunk 781 does not have enough neighbors. Skipping...
Chunk 795 does not have enough neighbors. Skipping...
Chunk 850 does not have enough neighbors. Skipping...
Chunk 852 does not have enough neighbors. Skipping...
Chunk 889 does not have enough neighbors. Skipping...
Chunk 936 does not have enough neighbors. Skipping...
Chunk 995 does not have enough neighbors. Skipping...
Chunk 1163 does not have enough neighbors. Skipping...
Chunk 1173 does not have enough neighbors. Skipping...
Chunk 1274 does not have enough neighbors. Skipping...
Chunk 1387 does not have enough neighbors. Skipping...
Chunk 1405 does not have enough neighbors. Skipping...
Chunk 1458 does not have enough neighbors. Skipping...
Chunk 1503 does not have enough neighbors. Skipping...
Chunk 1508 does not have enough neighbors. Skipping...
Chunk 1566 does not have enough neighbors. Skipping...
Chunk 1570 does not have enough neighbors. Skipping...
Chunk 1618 does not have enough neighbors. Skipping...
Chunk 1640 does not have enough neighbors. Skipping...
Chunk 1682 does not have enough neighbors. Skipping...
Chunk 1696 does not have enough neighbors. Skipping...
Chunk 1720 does not have enough neighbors. Skipping...
Chunk 1733 does not have enough neighbors. Skipping...
Chunk 1816 does not have enough neighbors. Skipping...
Chunk 1880 does not have enough neighbors. Skipping...
Chunk 1883 does not have enough neighbors. Skipping...
Chunk 1884 does not have enough neighbors. Skipping...
Chunk 1915 does not have enough neighbors. Skipping...
Chunk 1929 does not have enough neighbors. Skipping...
Chunk 1948 does not have enough neighbors. Skipping...
Chunk 2078 does not have enough neighbors. Skipping...
Chunk 2088 does not have enough neighbors. Skipping...
Chunk 2107 does not have enough neighbors. Skipping...
Chunk 2257 does not have enough neighbors. Skipping...
Chunk 2270 does not have enough neighbors. Skipping...
Chunk 2302 does not have enough neighbors. Skipping...
Chunk 2331 does not have enough neighbors. Skipping...
Chunk 2333 does not have enough neighbors. Skipping...
Chunk 2338 does not have enough neighbors. Skipping...
2_brain_ShareSeq

AnnData object with n_obs × n_vars = 2344 × 13000
    obs: 'group', 'cell_type', 'batch', 'silhouette_temp', 'cluster'
    var: 'modality'
    uns: 'modality_lengths', 'neighbors', 'umap', 'cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'distances', 'connectivities'

In [11]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '2_brain_ShareSeq'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result_best_reso.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.420283,0.514628,0.590461,0.922453,0.495120,Garfield,2_brain_ShareSeq
1,0.303512,0.480161,0.439557,0.836010,0.474992,Multigrate,2_brain_ShareSeq
2,0.506942,0.643207,0.649360,0.970894,0.600148,MultiVI,2_brain_ShareSeq
3,0.511619,0.583920,0.667331,0.957829,0.560575,MOFA,2_brain_ShareSeq
4,0.521676,0.667899,0.689285,0.994003,0.604726,Seurat,2_brain_ShareSeq

#### 利用最佳分辨率计算指标(Garfield);

In [26]:
## 重复结果
reso_dict = {
    '2_brain_ShareSeq': {
        'Garfield': 0.7, # 0.8000000000000003,
        'Multigrate': 1.600000000000001,
        'MultiVI': 0.39524500000000007,
        'MOFA': 0.6000000000000001,
        'Seurat': 0.10294556604732455
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('2_brain_ShareSeq', reso_dict)
adata

the length of cell type: 13
method_reso is not None, using the 0.7 as resolution for Garfield...
Number of clusters: 12
the length of cell type: 13
method_reso is not None, using the 1.600000000000001 as resolution for Multigrate...
Number of clusters: 13
the length of cell type: 13
method_reso is not None, using the 0.39524500000000007 as resolution for MultiVI...
Number of clusters: 13
the length of cell type: 13
method_reso is not None, using the 0.6000000000000001 as resolution for MOFA...
Number of clusters: 13
Chunk 8 does not have enough neighbors. Skipping...
Chunk 14 does not have enough neighbors. Skipping...
Chunk 157 does not have enough neighbors. Skipping...
Chunk 165 does not have enough neighbors. Skipping...
Chunk 206 does not have enough neighbors. Skipping...
Chunk 237 does not have enough neighbors. Skipping...
Chunk 251 does not have enough neighbors. Skipping...
Chunk 310 does not have enough neighbors. Skipping...
Chunk 396 does not have enough neighbors. Skipping...
Chunk 417 does not have enough neighbors. Skipping...
Chunk 464 does not have enough neighbors. Skipping...
Chunk 479 does not have enough neighbors. Skipping...
Chunk 485 does not have enough neighbors. Skipping...
Chunk 491 does not have enough neighbors. Skipping...
Chunk 498 does not have enough neighbors. Skipping...
Chunk 555 does not have enough neighbors. Skipping...
Chunk 649 does not have enough neighbors. Skipping...
Chunk 656 does not have enough neighbors. Skipping...
Chunk 663 does not have enough neighbors. Skipping...
Chunk 726 does not have enough neighbors. Skipping...
Chunk 749 does not have enough neighbors. Skipping...
Chunk 781 does not have enough neighbors. Skipping...
Chunk 795 does not have enough neighbors. Skipping...
Chunk 850 does not have enough neighbors. Skipping...
Chunk 852 does not have enough neighbors. Skipping...
Chunk 889 does not have enough neighbors. Skipping...
Chunk 936 does not have enough neighbors. Skipping...
Chunk 995 does not have enough neighbors. Skipping...
Chunk 1163 does not have enough neighbors. Skipping...
Chunk 1173 does not have enough neighbors. Skipping...
Chunk 1274 does not have enough neighbors. Skipping...
Chunk 1387 does not have enough neighbors. Skipping...
Chunk 1405 does not have enough neighbors. Skipping...
Chunk 1458 does not have enough neighbors. Skipping...
Chunk 1503 does not have enough neighbors. Skipping...
Chunk 1508 does not have enough neighbors. Skipping...
Chunk 1566 does not have enough neighbors. Skipping...
Chunk 1570 does not have enough neighbors. Skipping...
Chunk 1618 does not have enough neighbors. Skipping...
Chunk 1640 does not have enough neighbors. Skipping...
Chunk 1682 does not have enough neighbors. Skipping...
Chunk 1696 does not have enough neighbors. Skipping...
Chunk 1720 does not have enough neighbors. Skipping...
Chunk 1733 does not have enough neighbors. Skipping...
Chunk 1816 does not have enough neighbors. Skipping...
Chunk 1880 does not have enough neighbors. Skipping...
Chunk 1883 does not have enough neighbors. Skipping...
Chunk 1884 does not have enough neighbors. Skipping...
Chunk 1915 does not have enough neighbors. Skipping...
Chunk 1929 does not have enough neighbors. Skipping...
Chunk 1948 does not have enough neighbors. Skipping...
Chunk 2078 does not have enough neighbors. Skipping...
Chunk 2088 does not have enough neighbors. Skipping...
Chunk 2107 does not have enough neighbors. Skipping...
Chunk 2257 does not have enough neighbors. Skipping...
Chunk 2270 does not have enough neighbors. Skipping...
Chunk 2302 does not have enough neighbors. Skipping...
Chunk 2331 does not have enough neighbors. Skipping...
Chunk 2333 does not have enough neighbors. Skipping...
Chunk 2338 does not have enough neighbors. Skipping...
the length of cell type: 13
method_reso is not None, using the 0.10294556604732455 as resolution for Seurat...
Number of clusters: 13
Chunk 8 does not have enough neighbors. Skipping...
Chunk 14 does not have enough neighbors. Skipping...
Chunk 157 does not have enough neighbors. Skipping...
Chunk 165 does not have enough neighbors. Skipping...
Chunk 206 does not have enough neighbors. Skipping...
Chunk 237 does not have enough neighbors. Skipping...
Chunk 251 does not have enough neighbors. Skipping...
Chunk 310 does not have enough neighbors. Skipping...
Chunk 396 does not have enough neighbors. Skipping...
Chunk 417 does not have enough neighbors. Skipping...
Chunk 464 does not have enough neighbors. Skipping...
Chunk 479 does not have enough neighbors. Skipping...
Chunk 485 does not have enough neighbors. Skipping...
Chunk 491 does not have enough neighbors. Skipping...
Chunk 498 does not have enough neighbors. Skipping...
Chunk 555 does not have enough neighbors. Skipping...
Chunk 649 does not have enough neighbors. Skipping...
Chunk 656 does not have enough neighbors. Skipping...
Chunk 663 does not have enough neighbors. Skipping...
Chunk 726 does not have enough neighbors. Skipping...
Chunk 749 does not have enough neighbors. Skipping...
Chunk 781 does not have enough neighbors. Skipping...
Chunk 795 does not have enough neighbors. Skipping...
Chunk 850 does not have enough neighbors. Skipping...
Chunk 852 does not have enough neighbors. Skipping...
Chunk 889 does not have enough neighbors. Skipping...
Chunk 936 does not have enough neighbors. Skipping...
Chunk 995 does not have enough neighbors. Skipping...
Chunk 1163 does not have enough neighbors. Skipping...
Chunk 1173 does not have enough neighbors. Skipping...
Chunk 1274 does not have enough neighbors. Skipping...
Chunk 1387 does not have enough neighbors. Skipping...
Chunk 1405 does not have enough neighbors. Skipping...
Chunk 1458 does not have enough neighbors. Skipping...
Chunk 1503 does not have enough neighbors. Skipping...
Chunk 1508 does not have enough neighbors. Skipping...
Chunk 1566 does not have enough neighbors. Skipping...
Chunk 1570 does not have enough neighbors. Skipping...
Chunk 1618 does not have enough neighbors. Skipping...
Chunk 1640 does not have enough neighbors. Skipping...
Chunk 1682 does not have enough neighbors. Skipping...
Chunk 1696 does not have enough neighbors. Skipping...
Chunk 1720 does not have enough neighbors. Skipping...
Chunk 1733 does not have enough neighbors. Skipping...
Chunk 1816 does not have enough neighbors. Skipping...
Chunk 1880 does not have enough neighbors. Skipping...
Chunk 1883 does not have enough neighbors. Skipping...
Chunk 1884 does not have enough neighbors. Skipping...
Chunk 1915 does not have enough neighbors. Skipping...
Chunk 1929 does not have enough neighbors. Skipping...
Chunk 1948 does not have enough neighbors. Skipping...
Chunk 2078 does not have enough neighbors. Skipping...
Chunk 2088 does not have enough neighbors. Skipping...
Chunk 2107 does not have enough neighbors. Skipping...
Chunk 2257 does not have enough neighbors. Skipping...
Chunk 2270 does not have enough neighbors. Skipping...
Chunk 2302 does not have enough neighbors. Skipping...
Chunk 2331 does not have enough neighbors. Skipping...
Chunk 2333 does not have enough neighbors. Skipping...
Chunk 2338 does not have enough neighbors. Skipping...
2_brain_ShareSeq

AnnData object with n_obs × n_vars = 2344 × 13000
    obs: 'group', 'cell_type', 'batch', 'Garfield_cluster', 'silhouette_temp', 'Multigrate_cluster', 'MultiVI_cluster', 'MOFA_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'MultiVI', 'MultiVI_cluster', 'MOFA', 'MOFA_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'MultiVI_distances', 'MultiVI_connectivities', 'MOFA_distances', 'MOFA_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [27]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '2_brain_ShareSeq'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.420283,0.514628,0.590461,0.922453,0.495120,Garfield,2_brain_ShareSeq
1,0.174423,0.480161,0.378802,0.836010,0.474992,Multigrate,2_brain_ShareSeq
2,0.458934,0.643207,0.638186,0.970894,0.600148,MultiVI,2_brain_ShareSeq
3,0.451449,0.583920,0.639585,0.957829,0.560575,MOFA,2_brain_ShareSeq
4,0.465474,0.667899,0.647241,0.994003,0.604726,Seurat,2_brain_ShareSeq

### 数据集 1_ShareSeq_Skin

In [12]:
reso_dict = {
    '1_ShareSeq_Skin': {
        'Garfield': 1.02,
        'Multigrate': 1.9500000000000013,
        'MultiVI': 0.36450000000000005,
        'MOFA': 1.075,
        'Seurat': 0.095
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('1_ShareSeq_Skin', reso_dict=reso_dict)
adata

the length of cell type: 23
method_reso is not None, using the 1.02 as resolution for Garfield...
Number of clusters: 23
the length of cell type: 23
method_reso is not None, using the 1.9500000000000013 as resolution for Multigrate...
Number of clusters: 23
the length of cell type: 23
method_reso is not None, using the 0.36450000000000005 as resolution for MultiVI...
Number of clusters: 23
the length of cell type: 23
method_reso is not None, using the 1.075 as resolution for MOFA...
Number of clusters: 23
the length of cell type: 23
method_reso is not None, using the 0.095 as resolution for Seurat...
Number of clusters: 23
1_ShareSeq_Skin

AnnData object with n_obs × n_vars = 34774 × 13000
    obs: 'group', 'cell_type', 'batch', 'Garfield_cluster', 'silhouette_temp', 'Multigrate_cluster', 'MultiVI_cluster', 'MOFA_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'MultiVI', 'MultiVI_cluster', 'MOFA', 'MOFA_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'MultiVI_distances', 'MultiVI_connectivities', 'MOFA_distances', 'MOFA_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [15]:
import matplotlib.pyplot as plt

dataset = '1_ShareSeq_Skin'
res_dir = f'/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC/{dataset}'

latent_key_list = ['Garfield', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat']
for latent_key in latent_key_list:
    sc.tl.umap(adata, neighbors_key=latent_key)
    latent_key_cluster = latent_key + '_cluster'
    
    # Create a new figure for each plot with an appropriate size
    plt.figure(figsize=(12, 6))  # Adjust the figsize as needed
    sc.pl.umap(adata, color=['cell_type', latent_key_cluster], wspace=0.5, hspace=0.5, show=False, ncols=2)
    # Save the figure
    plt.savefig(res_dir + f"/{latent_key}_UMAP_clusters.png", bbox_inches='tight')  # Use bbox_inches to ensure full legend display
    plt.close()

In [14]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '1_ShareSeq_Skin'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.376443,0.549971,0.598558,0.980681,0.538438,Garfield,1_ShareSeq_Skin
1,0.395601,0.537026,0.573400,0.956081,0.516575,Multigrate,1_ShareSeq_Skin
2,0.334506,0.587817,0.599579,0.986347,0.556281,MultiVI,1_ShareSeq_Skin
3,0.312498,0.513707,0.532514,0.963540,0.523137,MOFA,1_ShareSeq_Skin
4,0.411604,0.615279,0.629103,0.984065,0.566668,Seurat,1_ShareSeq_Skin

#### 探索一下用最佳分辨率

In [6]:
# calculate the metrics based on the best resolution
adata = count_metrics_for_best_resolution('1_ShareSeq_Skin')
adata

WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.5353436267963937
resolution: 0.2, nmi: 0.5723102416540203
resolution: 0.3, nmi: 0.6031911869546472
resolution: 0.4, nmi: 0.6165769100045531
resolution: 0.5, nmi: 0.6248911567658882
resolution: 0.6, nmi: 0.623292641896834
resolution: 0.7, nmi: 0.6153468786706748
resolution: 0.8, nmi: 0.615155745396997
resolution: 0.9, nmi: 0.605526028804271
resolution: 1.0, nmi: 0.6035508796503326
resolution: 1.1, nmi: 0.6080362857638141
resolution: 1.2, nmi: 0.5877809469580292
resolution: 1.3, nmi: 0.5912423207636393
resolution: 1.4, nmi: 0.5902486125061525
resolution: 1.5, nmi: 0.5861233158384564
resolution: 1.6, nmi: 0.5845231058141975
resolution: 1.7, nmi: 0.5807327071753347
resolution: 1.8, nmi: 0.5763597794648074
resolution: 1.9, nmi: 0.5763388392068862
resolution: 2.0, nmi: 0.5739639597898369
optimised clustering against cell_type
optimal cluster resolution: 0.5
optimal score: 0.6248911567658882
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.19967273312491704
resolution: 0.2, nmi: 0.4982040134528918
resolution: 0.3, nmi: 0.524058867679582
resolution: 0.4, nmi: 0.5585664162224251
resolution: 0.5, nmi: 0.5448224444375673
resolution: 0.6, nmi: 0.5367061490750742
resolution: 0.7, nmi: 0.5653274726346504
resolution: 0.8, nmi: 0.5611752725892591
resolution: 0.9, nmi: 0.5709760962153608
resolution: 1.0, nmi: 0.5787167278777844
resolution: 1.1, nmi: 0.5863571407913564
resolution: 1.2, nmi: 0.5836926076877922
resolution: 1.3, nmi: 0.5788661638945053
resolution: 1.4, nmi: 0.5816727863603048
resolution: 1.5, nmi: 0.5884540528686085
resolution: 1.6, nmi: 0.5795824321541277
resolution: 1.7, nmi: 0.58224415957304
resolution: 1.8, nmi: 0.5843414483999994
resolution: 1.9, nmi: 0.5714366555961212
resolution: 2.0, nmi: 0.5526533014168822
optimised clustering against cell_type
optimal cluster resolution: 1.5
optimal score: 0.5884540528686085
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.5856226103458375
resolution: 0.2, nmi: 0.5962654176510832
resolution: 0.3, nmi: 0.6131507259755405
resolution: 0.4, nmi: 0.5998505000860533
resolution: 0.5, nmi: 0.5926723445158587
resolution: 0.6, nmi: 0.5959482192534702
resolution: 0.7, nmi: 0.5862490204665486
resolution: 0.8, nmi: 0.5874083667559474
resolution: 0.9, nmi: 0.5876494911165824
resolution: 1.0, nmi: 0.5833555804868958
resolution: 1.1, nmi: 0.5795378281070455
resolution: 1.2, nmi: 0.5783205782699067
resolution: 1.3, nmi: 0.5668623456297192
resolution: 1.4, nmi: 0.5679658594981324
resolution: 1.5, nmi: 0.5631319851497716
resolution: 1.6, nmi: 0.5659285009581966
resolution: 1.7, nmi: 0.5611031640925513
resolution: 1.8, nmi: 0.5618251866702242
resolution: 1.9, nmi: 0.5559310719600643
resolution: 2.0, nmi: 0.5530958453152981
optimised clustering against cell_type
optimal cluster resolution: 0.3
optimal score: 0.6131507259755405
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.5056364179721329
resolution: 0.2, nmi: 0.5200121817932122
resolution: 0.3, nmi: 0.5600729990461993
resolution: 0.4, nmi: 0.5463886010098394
resolution: 0.5, nmi: 0.5442438240341878
resolution: 0.6, nmi: 0.5436862762455414
resolution: 0.7, nmi: 0.5335071469704971
resolution: 0.8, nmi: 0.5238265971714271
resolution: 0.9, nmi: 0.5241790243849844
resolution: 1.0, nmi: 0.5374989616245948
resolution: 1.1, nmi: 0.5293606858096456
resolution: 1.2, nmi: 0.5303722792775438
resolution: 1.3, nmi: 0.5309720433047393
resolution: 1.4, nmi: 0.5279582793132594
resolution: 1.5, nmi: 0.5119512789387209
resolution: 1.6, nmi: 0.5166829440625056
resolution: 1.7, nmi: 0.5159063495688907
resolution: 1.8, nmi: 0.5143040119730535
resolution: 1.9, nmi: 0.5123694738698306
resolution: 2.0, nmi: 0.5119621557915052
optimised clustering against cell_type
optimal cluster resolution: 0.3
optimal score: 0.5600729990461993
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.6133033353709892
resolution: 0.2, nmi: 0.6082429278930997
resolution: 0.3, nmi: 0.5937351276763414
resolution: 0.4, nmi: 0.573817438637336
resolution: 0.5, nmi: 0.5731297466001628
resolution: 0.6, nmi: 0.5636502789217842
resolution: 0.7, nmi: 0.5599655998730967
resolution: 0.8, nmi: 0.5589336560303847
resolution: 0.9, nmi: 0.5563044275422866
resolution: 1.0, nmi: 0.552151630502516
resolution: 1.1, nmi: 0.5459736983181539
resolution: 1.2, nmi: 0.5430248908949473
resolution: 1.3, nmi: 0.5398590770015467
resolution: 1.4, nmi: 0.53873322878231
resolution: 1.5, nmi: 0.5338042677264379
resolution: 1.6, nmi: 0.5304503543228473
resolution: 1.7, nmi: 0.5311360326662435
resolution: 1.8, nmi: 0.5267341886833279
resolution: 1.9, nmi: 0.5262561267260245
resolution: 2.0, nmi: 0.5248243517840867
optimised clustering against cell_type
optimal cluster resolution: 0.1
optimal score: 0.6133033353709892
1_ShareSeq_Skin

AnnData object with n_obs × n_vars = 34774 × 13000
    obs: 'group', 'cell_type', 'batch', 'silhouette_temp', 'cluster'
    var: 'modality'
    uns: 'modality_lengths', 'neighbors', 'umap', 'cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'distances', 'connectivities'

In [7]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '1_ShareSeq_Skin'

df = pd. read_csv(f'{save_path}/{dataset}_metrics_result_best_reso.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.459732,0.549971,0.624891,0.980681,0.538438,Garfield,1_ShareSeq_Skin
1,0.425820,0.537026,0.588454,0.956081,0.516575,Multigrate,1_ShareSeq_Skin
2,0.386366,0.587817,0.613151,0.986347,0.556281,MultiVI,1_ShareSeq_Skin
3,0.435989,0.513707,0.560073,0.963540,0.523137,MOFA,1_ShareSeq_Skin
4,0.374092,0.615279,0.613303,0.984065,0.566668,Seurat,1_ShareSeq_Skin

#### 利用最佳分辨率计算指标(Garfield);

In [28]:
reso_dict = {
    '1_ShareSeq_Skin': {
        'Garfield': 0.5, # 1.02,
        'Multigrate': 1.9500000000000013,
        'MultiVI': 0.36450000000000005,
        'MOFA': 1.075,
        'Seurat': 0.095
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('1_ShareSeq_Skin', reso_dict=reso_dict)
adata

the length of cell type: 23
method_reso is not None, using the 0.5 as resolution for Garfield...
Number of clusters: 15
the length of cell type: 23
method_reso is not None, using the 1.9500000000000013 as resolution for Multigrate...
Number of clusters: 23
the length of cell type: 23
method_reso is not None, using the 0.36450000000000005 as resolution for MultiVI...
Number of clusters: 23
the length of cell type: 23
method_reso is not None, using the 1.075 as resolution for MOFA...
Number of clusters: 23
the length of cell type: 23
method_reso is not None, using the 0.095 as resolution for Seurat...
Number of clusters: 23
1_ShareSeq_Skin

AnnData object with n_obs × n_vars = 34774 × 13000
    obs: 'group', 'cell_type', 'batch', 'Garfield_cluster', 'silhouette_temp', 'Multigrate_cluster', 'MultiVI_cluster', 'MOFA_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'MultiVI', 'MultiVI_cluster', 'MOFA', 'MOFA_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'MultiVI', 'MOFA', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'MultiVI_distances', 'MultiVI_connectivities', 'MOFA_distances', 'MOFA_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [29]:
method_list = ['Garfield', 'Multigrate','MultiVI','MOFA','Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_ATAC'
dataset = '1_ShareSeq_Skin'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df

,ARI,Isolated_Labels_ASW,NMI,cLISI_Graph,Silhouette,method,Dataset
0,0.459732,0.549971,0.624891,0.980681,0.538438,Garfield,1_ShareSeq_Skin
1,0.395601,0.537026,0.573400,0.956081,0.516575,Multigrate,1_ShareSeq_Skin
2,0.334506,0.587817,0.599579,0.986347,0.556281,MultiVI,1_ShareSeq_Skin
3,0.312498,0.513707,0.532514,0.963540,0.523137,MOFA,1_ShareSeq_Skin
4,0.411604,0.615279,0.629103,0.984065,0.566668,Seurat,1_ShareSeq_Skin