In [1]:
import anndata as ad
import pandas as pd
import numpy as np
from scipy.io import mmread, mmwrite
from scipy.sparse import csr_matrix
import muon
import scarches as sca
from multigrate.data import organize_multiome_anndatas
import scanpy as sc
import scib_metrics
from typing import Optional
import os, sys
from scipy.sparse import csr_matrix, coo_matrix
import scipy
from scipy import sparse
import importlib
import matplotlib.pyplot as plt
import seaborn as sns
import scib
import scib_metrics
from scib_metrics.benchmark import Benchmarker
from typing import Any, Callable, Optional, Union
from plottable import ColumnDefinition, Table
from plottable.cmap import normed_cmap
from plottable.plots import bar

import warnings
warnings.filterwarnings("ignore")

/home/zhouweige/anaconda3/envs/scib/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
WARNING:root:In order to use the mouse gastrulation seqFISH datsets, please install squidpy (see https://github.com/scverse/squidpy).
WARNING:root:In order to use sagenet models, please install pytorch geometric (see https://pytorch-geometric.readthedocs.io) and
 captum (see https://github.com/pytorch/captum).
WARNING:root:mvTCR is not installed. To use mvTCR models, please install it first using "pip install mvtcr"
WARNING:root:multigrate is not installed. To use multigrate models, please install it first using "pip install multigrate".

In [2]:
def read_RNA_ADT(RNA_path,ADT_path):
    # gene expression
    cell_names = pd.read_csv(RNA_path+'/barcodes.tsv', sep = '\t', header=None, index_col=None)
    cell_names.columns =  ['cell_ids'] 
    cell_names['cell_ids'] = cell_names['cell_ids'].str.replace('.','-')
    X = csr_matrix(mmread(RNA_path+'/matrix.mtx').T)
    gene_names = pd.read_csv(RNA_path+'/features.tsv', sep = '\t',  header=None, index_col=None) 
    gene_names.columns =  ['gene_ids'] 
    adata_RNA = ad.AnnData(X, obs=pd.DataFrame(index=cell_names.cell_ids), var=pd.DataFrame(index = gene_names.gene_ids))
    adata_RNA.var_names_make_unique()
    # ADT information
    adata_ADT = pd.read_csv(f'{ADT_path}/ADT.csv', index_col=0)
    adata_ADT.columns = adata_ADT.columns.str.replace('.', '-')
    # adata_ADT.index = adata_ADT.index.str.replace('.', '_')
    # adata_ADT.index = adata_ADT.index.str.replace('-', '_')
    adata_ADT = ad.AnnData(adata_ADT.T)
    adata_ADT.X = adata_ADT.X.astype(np.float64)
    # numpy 转为 sparse matrix
    adata_ADT.X = csr_matrix(adata_ADT.X)
    
    return adata_RNA, adata_ADT

In [3]:
import os
import numpy as np
import scanpy as sc
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

def pca(adata, use_reps=None, n_comps=10):

    """Dimension reduction with PCA algorithm"""

    from sklearn.decomposition import PCA
    from scipy.sparse.csc import csc_matrix
    from scipy.sparse.csr import csr_matrix
    pca = PCA(n_components=n_comps)
    if use_reps is not None:
       feat_pca = pca.fit_transform(adata.obsm[use_reps])
    else:
       if isinstance(adata.X, csc_matrix) or isinstance(adata.X, csr_matrix):
          feat_pca = pca.fit_transform(adata.X.toarray())
       else:
          feat_pca = pca.fit_transform(adata.X)

    return feat_pca

def supervised_clustering(adata, n_clusters=7, key='Garfield', add_key='Garfield_cluster', cluster_method='leiden',
               start=0.5, end=2.0, increment=0.05, use_pca=False, n_comps=20):
    if use_pca:
       adata.obsm[key + '_pca'] = pca(adata, use_reps=key, n_comps=n_comps)

    method_cluster = add_key
    method = key
    
    if cluster_method == 'leiden':
       if use_pca:
          res = search_res(adata, n_clusters, use_rep=key + '_pca', cluster_method=cluster_method, 
                           start=start, end=end, increment=increment)
       else:
          res = search_res(adata, n_clusters, use_rep=method, cluster_method=cluster_method, 
                           start=start, end=end, increment=increment)
       sc.tl.leiden(adata, random_state=0, key_added=method_cluster, resolution=res, neighbors_key=method)
    elif cluster_method == 'louvain':
       if use_pca:
          res = search_res(adata, n_clusters, use_rep=key + '_pca', cluster_method=cluster_method, 
                           start=start, end=end, increment=increment)
       else:
          res = search_res(adata, n_clusters, use_rep=method, cluster_method=cluster_method, 
                           start=start, end=end, increment=increment)
       sc.tl.louvain(adata, random_state=0, key_added=method_cluster, resolution=res, neighbors_key=method)

def search_res(adata, n_clusters, use_rep='Garfield', cluster_method='leiden', start=0.5, end=2.0,
               increment=0.05, expansion_factor=1.75, max_iter=50):
    '''\
    Searching corresponding resolution according to given cluster number

    Parameters
    ----------
    adata : anndata
        AnnData object of spatial data.
    n_clusters : int
        Target number of clusters.
    method : string
        Tool for clustering. Supported tools include 'leiden' and 'louvain'. The default is 'leiden'.
    use_rep : string
        The indicated representation for clustering.
    start : float
        The start value for searching.
    end : float
        The end value for searching.
    increment : float
        The step size to increase.
    expansion_factor : float
        Factor to expand the search range if no resolution is found in the initial range.
    max_iter : int
        Maximum number of iterations to prevent infinite loops.

    Returns
    -------
    res : float
        Resolution.

    '''
    print('Searching resolution...')
    label = 0
    method = use_rep
    method_cluster = method + '_cluster'
    
    current_start, current_end = start, end
    best_res = None
    best_diff = float('inf')  # Track the best resolution so far
    best_count = 0
    iteration = 0  # Track number of iterations
    
    # 构图
    sc.pp.neighbors(adata, use_rep=use_rep, key_added=method)

    while label == 0 and iteration < max_iter:
        iteration += 1
        for res in sorted(list(np.arange(current_start, current_end, increment)), reverse=True):
            if cluster_method == 'leiden':
                sc.tl.leiden(adata, random_state=0, key_added=method_cluster,
                             resolution=res, neighbors_key=method)
                count_unique = adata.obs[method_cluster].nunique()
            elif cluster_method == 'louvain':
                sc.tl.louvain(adata,  random_state=0, key_added=method_cluster, 
                             resolution=method_reso, neighbors_key=method)
                count_unique = adata.obs[method_cluster].nunique()

            print(f'resolution={res}, cluster number={count_unique}')

            # Update the best resolution if it's closer to the target
            diff = abs(count_unique - n_clusters)
            if diff < best_diff:
                best_diff = diff
                best_res = res
                best_count = count_unique

            if count_unique == n_clusters:
                label = 1
                break

        if label == 0:
            if best_res is not None:
                # Instead of starting from scratch, continue from the closest found resolution
                if best_count > n_clusters:
                    current_start = min(best_res, current_start * 0.9)  # Avoid too small a search range
                    current_end = min(current_start * expansion_factor, end * 2)  # Limit max range
                    print(f"Expanding search range: new range ({current_start}, {current_end})")
                else:
                    current_start = max(best_res, current_start * 1.2)  # Avoid too small a search range
                    current_end = min(current_start * expansion_factor, end * 2)  # Limit max range
                    print(f"Expanding search range: new range ({current_start}, {current_end})")
            else:
                print("Warning: No valid resolution found yet, expanding the search range.")
                current_start *= expansion_factor
                current_end *= expansion_factor

    if iteration >= max_iter:
        print("Warning: Reached maximum iteration limit.")

    return best_res if label == 1 else None

In [4]:
def count_metrics_for_resolution(dataset, reso_dict=None, start=0.5, end=2.0, increment=0.05):
    rna_dir = f'/data2/zhouwg_data/project/Garfield_benchmark/datasets/MultiomicsBenchmark/Raw_data/RNA_Protein/{dataset}/RNA'
    adt_dir = f'/data2/zhouwg_data/project/Garfield_benchmark/datasets/MultiomicsBenchmark/Raw_data/RNA_Protein/{dataset}'
    metadata_file = f'/data2/zhouwg_data/project/Garfield_benchmark/datasets/MultiomicsBenchmark/Raw_data/RNA_Protein/{dataset}/metadata.csv'
    res_dir = f'/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_Protein/{dataset}'

    # 读取 RNA 和 ATAC 数据
    adata_RNA, adata_ADT = read_RNA_ADT(rna_dir, adt_dir)

    # 处理 RNA 数据
    adata_RNA.layers["counts"] = adata_RNA.X.copy()
    sc.pp.normalize_total(adata_RNA)
    sc.pp.log1p(adata_RNA)
    sc.pp.highly_variable_genes(adata_RNA, flavor="seurat_v3", n_top_genes=3000, subset=False)
    adata_RNA = adata_RNA[:, adata_RNA.var.highly_variable].copy()

    # 处理 ADT 数据
    adata_ADT.layers['counts'] = adata_ADT.X.copy()
    muon.prot.pp.clr(adata_ADT)
    adata_ADT.layers['clr'] = adata_ADT.X.copy()

    # 合并 RNA 和 ADT 数据
    adata = organize_multiome_anndatas(
        adatas=[[adata_RNA], [adata_ADT]],    # RNA-seq 始终在第一位
        layers=[['counts'], ['clr']]      # 使用 .layers 中的数据
    )

    # 读取元数据
    metadata = pd.read_csv(metadata_file, index_col=0)
    metadata.index = adata.obs_names  # 修正元数据的索引
    if dataset == '2_GSE128639':
        adata.obs['cell_type'] = metadata['celltype.l2'].astype('category')
    elif dataset == '7_zenodo6368128/LUNG':
        adata.obs['cell_type'] = metadata['celltype'].astype('category')
    elif dataset == '7_zenodo6368128/PBMC':
        adata.obs['cell_type'] = metadata['celltype'].astype('category')
    elif dataset == '12_GSE193181/P5':
        adata.obs['cell_type'] = metadata['ct_highres'].astype('category')
    elif dataset == '12_GSE193181/P8':
        adata.obs['cell_type'] = metadata['cell.type'].astype('category')

    # 处理缺失的 cell_type
    if adata.obs["cell_type"].isna().sum() != 0:
        adata.obs["cell_type"] = adata.obs["cell_type"].cat.add_categories(['NaN'])
        adata.obs.loc[adata.obs["cell_type"].isna(), "cell_type"] = 'NaN'

    result = pd.DataFrame()
    metrics_list = []
    method_list = ['Garfield', 'Multigrate', 'TotalVI', 'scArches', 'Seurat']

    # 计算不同方法的指标
    for method in method_list:
        method_file = f'{res_dir}/{method}.csv'
        if os.path.exists(method_file):
            latent = pd.read_csv(method_file, header=None)
            latent.index = adata.obs_names
            adata.obsm[method] = latent
            print('the length of cell type:', adata.obs['cell_type'].nunique())
            method_cluster = method+'_cluster'
            if reso_dict is not None and dataset in reso_dict.keys():
                data_reso_dict = reso_dict[dataset]
                method_reso = data_reso_dict[method]
                sc.pp.neighbors(adata, use_rep=method, key_added=method)
                if method_reso is not None:
                    print(f'method_reso is not None, using the {method_reso} as resolution for {method}...')
                    sc.tl.leiden(adata,  random_state=0, key_added=method_cluster, 
                                 resolution=method_reso, neighbors_key=method)
                    sc.tl.umap(adata, neighbors_key=method)
                    print('Number of clusters:', adata.obs[method_cluster].nunique())
                else:
                    print('Searching resolution for {}...'.format(method))
                    supervised_clustering(adata, n_clusters=adata.obs['cell_type'].nunique(),
                                          key=method, add_key=method_cluster, cluster_method='leiden',
                                          start=start, end=end, increment=increment)
                    sc.tl.umap(adata, neighbors_key=method)
                    print('Number of clusters:', adata.obs[method_cluster].nunique())
            else:
                print('Searching resolution for {}...'.format(method))
                supervised_clustering(adata, n_clusters=adata.obs['cell_type'].nunique(),
                                      key=method, add_key=method_cluster, cluster_method='leiden',
                                      start=start, end=end, increment=increment)
                sc.tl.umap(adata, neighbors_key=method)
                print('Number of clusters:', adata.obs[method_cluster].nunique())
            # 计算指标
            # scib.metrics.cluster_optimal_resolution(adata, cluster_key="cluster", label_key="cell_type")
            ari = scib.metrics.ari(adata, cluster_key=method_cluster, label_key="cell_type")
            # iso_asw = scib.metrics.isolated_labels_asw(adata, label_key="cell_type", batch_key='batch', embed=method, verbose=False)
            nmi = scib.metrics.nmi(adata, cluster_key=method_cluster, label_key="cell_type")
            clisi = scib.metrics.clisi_graph(adata, label_key="cell_type", use_rep=method, type_='embed')
            sht = scib.metrics.silhouette(adata, label_key="cell_type", embed=method, scale=True) #  metric='euclidean',

            metrics_list.append([ari, nmi, clisi, sht, method])

    # 处理 Seurat 的结果 通过 graph 的方式
    if method == 'Seurat_graph':
        method = 'Seurat'
        con = mmread(f'{res_dir}/{method}_connectivities.mtx')
        dis = mmread(f'{res_dir}/{method}_distance.mtx')
        
        # uns['neighbors'] 的信息
        adata.uns['neighbors'] = {
            'connectivities_key': 'connectivities', 'distances_key': 'distances',
            'params': {'n_neighbors': 20, 'method': 'umap', 'random_state': 0, 'metric': 'euclidean'}
        }
        adata.uns['neighbors']['distances'] = csr_matrix(dis)
        adata.uns['neighbors']['connectivities'] = csr_matrix(con)
        adata.obsp['distances'] = csr_matrix(dis)
        adata.obsp['connectivities'] = csr_matrix(con)
        # Seurat 的信息   
        adata.uns['Seurat'] = {
            'connectivities_key': 'Seurat_connectivities', 'distances_key': 'Seurat_distances',
            'params': {'n_neighbors': 20, 'method': 'umap', 'random_state': 0, 'metric': 'euclidean', 'use_rep': 'Seurat'}
        }
        adata.uns['Seurat']['Seurat_distances'] = csr_matrix(dis)
        adata.uns['Seurat']['Seurat_connectivities'] = csr_matrix(con)
        adata.obsp['Seurat_distances'] = csr_matrix(dis)
        adata.obsp['Seurat_connectivities'] = csr_matrix(con)
        
        sc.tl.umap(adata) # , neighbors_key=method
        adata.obsm['Seurat'] = adata.obsm['X_umap'][:, :2]  # 确保只取二维的 UMAP 结果
        method_cluster = method+'_cluster'
        if reso_dict is not None and dataset in reso_dict.keys():
            data_reso_dict = reso_dict[dataset]
            method_reso = data_reso_dict[method]
            if method_reso is not None:
                print(f'method_reso is not None, using the {method_reso} as resolution for {method}...')
                sc.tl.leiden(adata,  random_state=0, key_added=method_cluster, 
                             resolution=method_reso, neighbors_key=method)
                print('Number of clusters:', adata.obs[method_cluster].nunique())
            else:
                print('Searching resolution for Seurat...')
                start = 0.3
                end = 1.5
                increment = 0.05
                for res in sorted(list(np.arange(start, end, increment)), reverse=True):
                   sc.tl.leiden(adata, random_state=0, resolution=res, neighbors_key='Seurat')
                   count_unique = adata.obs['leiden'].nunique()
                   print('resolution={}, cluster number={}'.format(res, count_unique))
                   if count_unique == adata.obs['cell_type'].nunique():
                        break
                print('resolution for Seurat:', res)
                sc.tl.leiden(adata, random_state=0, resolution=res, neighbors_key='Seurat')
                print('Number of clusters:', adata.obs['leiden'].nunique())
                adata.obs[method_cluster] = adata.obs['leiden']
        else:
            print('Searching resolution for Seurat...')
            start = 0.3
            end = 1.5
            increment = 0.05
            for res in sorted(list(np.arange(start, end, increment)), reverse=True):
               sc.tl.leiden(adata, random_state=0, resolution=res, neighbors_key='Seurat')
               count_unique = adata.obs['leiden'].nunique()
               print('resolution={}, cluster number={}'.format(res, count_unique))
               if count_unique == adata.obs['cell_type'].nunique():
                    break
            print('resolution for Seurat:', res)
            sc.tl.leiden(adata, random_state=0, resolution=res, neighbors_key='Seurat')
            print('Number of clusters:', adata.obs['leiden'].nunique())
            adata.obs[method_cluster] = adata.obs['leiden']
    
        # 计算 Seurat 的指标
        # scib.metrics.cluster_optimal_resolution(adata, cluster_key="cluster", label_key="cell_type")
        ari = scib.metrics.ari(adata, cluster_key=method_cluster, label_key="cell_type")
        # iso_asw = scib.metrics.isolated_labels_asw(adata, label_key="cell_type", batch_key='batch', embed=method, verbose=False)
        nmi = scib.metrics.nmi(adata, cluster_key=method_cluster, label_key="cell_type")
        clisi = scib.metrics.clisi_graph(adata, label_key="cell_type", use_rep=method, type_='embed')
        sht = scib.metrics.silhouette(adata, label_key="cell_type", embed=method, scale=True) # metric='euclidean',
        metrics_list.append([ari, nmi, clisi, sht, 'Seurat'])

    # 保存结果
    df = pd.DataFrame(metrics_list, columns=['ARI', 'NMI', 'cLISI', 'cASW', 'model'])
    result = pd.concat([result, df], ignore_index=True)
    result['dataset'] = dataset
    if dataset == "7_zenodo6368128/LUNG" or dataset == "7_zenodo6368128/PBMC" or \
            dataset == "12_GSE193181/P5" or "12_GSE193181/P7":
        result.to_csv(f'{res_dir}/../../{dataset}_metrics_result.csv', index=False)
    else:
        result.to_csv(f'{res_dir}/../{dataset}_metrics_result.csv', index=False)
    print(dataset)

    return adata

In [5]:
def count_metrics_for_best_resolution(dataset):
    rna_dir = f'/data2/zhouwg_data/project/Garfield_benchmark/datasets/MultiomicsBenchmark/Raw_data/RNA_Protein/{dataset}/RNA'
    adt_dir = f'/data2/zhouwg_data/project/Garfield_benchmark/datasets/MultiomicsBenchmark/Raw_data/RNA_Protein/{dataset}'
    metadata_file = f'/data2/zhouwg_data/project/Garfield_benchmark/datasets/MultiomicsBenchmark/Raw_data/RNA_Protein/{dataset}/metadata.csv'
    res_dir = f'/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_Protein/{dataset}'

    # 读取 RNA 和 ATAC 数据
    adata_RNA, adata_ADT = read_RNA_ADT(rna_dir, adt_dir)

    # 处理 RNA 数据
    adata_RNA.layers["counts"] = adata_RNA.X.copy()
    sc.pp.normalize_total(adata_RNA)
    sc.pp.log1p(adata_RNA)
    sc.pp.highly_variable_genes(adata_RNA, flavor="seurat_v3", n_top_genes=3000, subset=False)
    adata_RNA = adata_RNA[:, adata_RNA.var.highly_variable].copy()

    # 处理 ADT 数据
    adata_ADT.layers['counts'] = adata_ADT.X.copy()
    muon.prot.pp.clr(adata_ADT)
    adata_ADT.layers['clr'] = adata_ADT.X.copy()

    # 合并 RNA 和 ADT 数据
    adata = organize_multiome_anndatas(
        adatas=[[adata_RNA], [adata_ADT]],    # RNA-seq 始终在第一位
        layers=[['counts'], ['clr']]      # 使用 .layers 中的数据
    )

    # 读取元数据
    metadata = pd.read_csv(metadata_file, index_col=0)
    metadata.index = adata.obs_names  # 修正元数据的索引
    if dataset == '2_GSE128639':
        adata.obs['cell_type'] = metadata['celltype.l2'].astype('category')
    elif dataset == '7_zenodo6368128/LUNG':
        adata.obs['cell_type'] = metadata['celltype'].astype('category')
    elif dataset == '7_zenodo6368128/PBMC':
        adata.obs['cell_type'] = metadata['celltype'].astype('category')
    elif dataset == '12_GSE193181/P5':
        adata.obs['cell_type'] = metadata['ct_highres'].astype('category')
    elif dataset == '12_GSE193181/P8':
        adata.obs['cell_type'] = metadata['cell.type'].astype('category')

    # 处理缺失的 cell_type
    if adata.obs["cell_type"].isna().sum() != 0:
        adata.obs["cell_type"] = adata.obs["cell_type"].cat.add_categories(['NaN'])
        adata.obs.loc[adata.obs["cell_type"].isna(), "cell_type"] = 'NaN'

    adata.obs['batch'] = ['batch1'] * adata.shape[0]

    result = pd.DataFrame()
    metrics_list = []
    method_list = ['Garfield', 'Multigrate', 'TotalVI', 'scArches', 'Seurat']
    for method in method_list:
        method_file = f'{res_dir}/{method}.csv'
        if os.path.exists(method_file):
            latent = pd.read_csv(method_file, header=None)
            latent.index = adata.obs_names
            adata.obsm[method] = latent
            sc.pp.neighbors(adata, use_rep=method)
            sc.tl.umap(adata)
            # sc.tl.leiden(adata, key_added="cluster")
            scib.metrics.cluster_optimal_resolution(adata, cluster_key="cluster", label_key="cell_type")
            ari = scib.metrics.ari(adata, cluster_key="cluster", label_key="cell_type")
            # iso_asw = scib.metrics.isolated_labels_asw(adata, label_key="cell_type", batch_key='batch', embed=method,  verbose = False)
            nmi = scib.metrics.nmi(adata, cluster_key="cluster", label_key="cell_type")
            clisi = scib.metrics.clisi_graph(adata, label_key="cell_type",use_rep=method, type_='embed')
            sht = scib.metrics.silhouette(adata, label_key="cell_type", embed=method, metric='euclidean', scale=True)
            metrics_list.append([ari, nmi, clisi, sht, method])

    # 保存结果
    df = pd.DataFrame(metrics_list, columns=['ARI', 'NMI', 'cLISI', 'cASW', 'model'])
    result = pd.concat([result, df], ignore_index=True)
    result['dataset'] = dataset
    if dataset == "7_zenodo6368128/LUNG" or dataset == "7_zenodo6368128/PBMC" or \
            dataset == "12_GSE193181/P5" or "12_GSE193181/P7":
        result.to_csv(f'{res_dir}/../../{dataset}_metrics_result_best_reso.csv', index=False)
    else:
        result.to_csv(f'{res_dir}/../{dataset}_metrics_result_best_reso.csv', index=False)
        
    print(dataset)
    
    return adata

### 数据集 2_GSE128639

In [21]:
## 记录resolution
reso_dict = {
    '2_GSE128639': {
        'Garfield': 1.10,
        'Multigrate': 1.9000000000000012,
        'TotalVI': 1.8000000000000012,
        'scArches': 1.33,
        'Seurat': 0.15690529804500009, 
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('2_GSE128639', reso_dict=reso_dict)
adata

the length of cell type: 27
method_reso is not None, using the 1.1 as resolution for Garfield...
Number of clusters: 27
the length of cell type: 27
method_reso is not None, using the 1.9000000000000012 as resolution for Multigrate...
Number of clusters: 27
the length of cell type: 27
method_reso is not None, using the 1.8000000000000012 as resolution for TotalVI...
Number of clusters: 27
the length of cell type: 27
method_reso is not None, using the 1.33 as resolution for scArches...
Number of clusters: 27
the length of cell type: 27
method_reso is not None, using the 0.15690529804500009 as resolution for Seurat...
Number of clusters: 27
Chunk 501 does not have enough neighbors. Skipping...
Chunk 1885 does not have enough neighbors. Skipping...
Chunk 2996 does not have enough neighbors. Skipping...
Chunk 5648 does not have enough neighbors. Skipping...
Chunk 6042 does not have enough neighbors. Skipping...
Chunk 11226 does not have enough neighbors. Skipping...
Chunk 11366 does not have enough neighbors. Skipping...
Chunk 12149 does not have enough neighbors. Skipping...
Chunk 13361 does not have enough neighbors. Skipping...
Chunk 13833 does not have enough neighbors. Skipping...
Chunk 15590 does not have enough neighbors. Skipping...
Chunk 15899 does not have enough neighbors. Skipping...
Chunk 16889 does not have enough neighbors. Skipping...
Chunk 17195 does not have enough neighbors. Skipping...
Chunk 18498 does not have enough neighbors. Skipping...
Chunk 19251 does not have enough neighbors. Skipping...
Chunk 19608 does not have enough neighbors. Skipping...
Chunk 22113 does not have enough neighbors. Skipping...
Chunk 22518 does not have enough neighbors. Skipping...
Chunk 25777 does not have enough neighbors. Skipping...
Chunk 27447 does not have enough neighbors. Skipping...
Chunk 28892 does not have enough neighbors. Skipping...
Chunk 29712 does not have enough neighbors. Skipping...
Chunk 30448 does not have enough neighbors. Skipping...
2_GSE128639

AnnData object with n_obs × n_vars = 30672 × 3025
    obs: 'group', 'cell_type', 'Garfield_cluster', 'Multigrate_cluster', 'TotalVI_cluster', 'scArches_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'TotalVI', 'TotalVI_cluster', 'scArches', 'scArches_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'TotalVI', 'scArches', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'TotalVI_distances', 'TotalVI_connectivities', 'scArches_distances', 'scArches_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [22]:
import matplotlib.pyplot as plt

dataset = '2_GSE128639'
res_dir = f'/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_Protein/{dataset}'

latent_key_list = ['Garfield', 'Multigrate', 'TotalVI', 'scArches', 'Seurat']
for latent_key in latent_key_list:
    sc.tl.umap(adata, neighbors_key=latent_key)
    latent_key_cluster = latent_key + '_cluster'
    
    # Create a new figure for each plot with an appropriate size
    plt.figure(figsize=(12, 6))  # Adjust the figsize as needed
    sc.pl.umap(adata, color=['cell_type', latent_key_cluster], wspace=0.5, hspace=0.5, show=False, ncols=2)
    # Save the figure
    plt.savefig(res_dir + f"/{latent_key}_UMAP_clusters.png", bbox_inches='tight')  # Use bbox_inches to ensure full legend display
    plt.close()

In [23]:
method_list = ['Garfield', 'Multigrate', 'TotalVI', 'scArches', 'Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_Protein'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

        ARI       NMI     cLISI      cASW       model      dataset
0  0.526840  0.782347  0.999245  0.675484    Garfield  2_GSE128639
1  0.488701  0.754594  0.995517  0.566655  Multigrate  2_GSE128639
2  0.588347  0.798205  0.998372  0.568177     TotalVI  2_GSE128639
3  0.568930  0.793671  0.999415  0.598213    scArches  2_GSE128639
4  0.514337  0.800190  0.999907  0.721279      Seurat  2_GSE128639

#### 探索一下用最佳分辨率

In [25]:
# calculate the metrics based on the best resolution
adata = count_metrics_for_best_resolution('2_GSE128639')
adata

resolution: 0.1, nmi: 0.8131184302239349
resolution: 0.2, nmi: 0.830460857130264
resolution: 0.3, nmi: 0.838938190188206
resolution: 0.4, nmi: 0.8609854022739019
resolution: 0.5, nmi: 0.8586232186212486
resolution: 0.6, nmi: 0.8408418206226269
resolution: 0.7, nmi: 0.8271416651336927
resolution: 0.8, nmi: 0.8138258028726302
resolution: 0.9, nmi: 0.7975184568962541
resolution: 1.0, nmi: 0.7994883442088038
resolution: 1.1, nmi: 0.7823473534830022
resolution: 1.2, nmi: 0.7870565047520184
resolution: 1.3, nmi: 0.7843099839005839
resolution: 1.4, nmi: 0.7771924177688436
resolution: 1.5, nmi: 0.7729157460809087
resolution: 1.6, nmi: 0.7762982872088157
resolution: 1.7, nmi: 0.7639290705720517
resolution: 1.8, nmi: 0.7488556205069352
resolution: 1.9, nmi: 0.7649305868181284
resolution: 2.0, nmi: 0.7496005105249844
optimised clustering against cell_type
optimal cluster resolution: 0.4
optimal score: 0.8609854022739019
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.7565831644467642
resolution: 0.2, nmi: 0.8066359426283376
resolution: 0.3, nmi: 0.8073857696854038
resolution: 0.4, nmi: 0.8208004201737895
resolution: 0.5, nmi: 0.8371566260727631
resolution: 0.6, nmi: 0.841850396428986
resolution: 0.7, nmi: 0.8386935803063503
resolution: 0.8, nmi: 0.8387413427155569
resolution: 0.9, nmi: 0.8262657091277472
resolution: 1.0, nmi: 0.8280480886592023
resolution: 1.1, nmi: 0.8183827497708595
resolution: 1.2, nmi: 0.796582818307018
resolution: 1.3, nmi: 0.7889482357634915
resolution: 1.4, nmi: 0.784709478440466
resolution: 1.5, nmi: 0.7859787889403022
resolution: 1.6, nmi: 0.774251888258084
resolution: 1.7, nmi: 0.7705782920457184
resolution: 1.8, nmi: 0.7574390834366018
resolution: 1.9, nmi: 0.7545940901141029
resolution: 2.0, nmi: 0.7510019262967107
optimised clustering against cell_type
optimal cluster resolution: 0.6
optimal score: 0.841850396428986
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.801008471240912
resolution: 0.2, nmi: 0.8330112717479771
resolution: 0.3, nmi: 0.8639910511848444
resolution: 0.4, nmi: 0.8709449385317559
resolution: 0.5, nmi: 0.8703565926306425
resolution: 0.6, nmi: 0.8726644124523361
resolution: 0.7, nmi: 0.835202653640223
resolution: 0.8, nmi: 0.8277563830889471
resolution: 0.9, nmi: 0.826306924476954
resolution: 1.0, nmi: 0.8216004067250815
resolution: 1.1, nmi: 0.8289295081781094
resolution: 1.2, nmi: 0.8224394513149867
resolution: 1.3, nmi: 0.8081926785591482
resolution: 1.4, nmi: 0.7979502271133859
resolution: 1.5, nmi: 0.7979105539916121
resolution: 1.6, nmi: 0.7980232971137269
resolution: 1.7, nmi: 0.7986220491632684
resolution: 1.8, nmi: 0.7982047565945296
resolution: 1.9, nmi: 0.7850167293249909
resolution: 2.0, nmi: 0.7771265260201035
optimised clustering against cell_type
optimal cluster resolution: 0.6
optimal score: 0.8726644124523361
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.7966253067736909
resolution: 0.2, nmi: 0.8474457005564818
resolution: 0.3, nmi: 0.8659692876518197
resolution: 0.4, nmi: 0.8541389810951453
resolution: 0.5, nmi: 0.8407565700821494
resolution: 0.6, nmi: 0.8434860725337804
resolution: 0.7, nmi: 0.8240459203564506
resolution: 0.8, nmi: 0.8187872838438979
resolution: 0.9, nmi: 0.813551870249349
resolution: 1.0, nmi: 0.8076538103273851
resolution: 1.1, nmi: 0.8041866578844123
resolution: 1.2, nmi: 0.7984276263314063
resolution: 1.3, nmi: 0.7933600446523874
resolution: 1.4, nmi: 0.7913223524568115
resolution: 1.5, nmi: 0.7907656408645211
resolution: 1.6, nmi: 0.7753396626035151
resolution: 1.7, nmi: 0.777488048453457
resolution: 1.8, nmi: 0.7781347797556779
resolution: 1.9, nmi: 0.7702511129346812
resolution: 2.0, nmi: 0.7703572460952195
optimised clustering against cell_type
optimal cluster resolution: 0.3
optimal score: 0.8659692876518197
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.8266113299557121
resolution: 0.2, nmi: 0.7802291282614437
resolution: 0.3, nmi: 0.7630760600830063
resolution: 0.4, nmi: 0.7367828398669893
resolution: 0.5, nmi: 0.7257640871654203
resolution: 0.6, nmi: 0.7211868055663742
resolution: 0.7, nmi: 0.7142355094670149
resolution: 0.8, nmi: 0.7116871450994312
resolution: 0.9, nmi: 0.705824001273948
resolution: 1.0, nmi: 0.6978268897595349
resolution: 1.1, nmi: 0.6930862449596924
resolution: 1.2, nmi: 0.6875475484858578
resolution: 1.3, nmi: 0.6850940714092771
resolution: 1.4, nmi: 0.6782597374716893
resolution: 1.5, nmi: 0.6762846387467124
resolution: 1.6, nmi: 0.6741285244366454
resolution: 1.7, nmi: 0.6730009492932715
resolution: 1.8, nmi: 0.6677107634345888
resolution: 1.9, nmi: 0.6674952891588307
resolution: 2.0, nmi: 0.6626245129808146
optimised clustering against cell_type
optimal cluster resolution: 0.1
optimal score: 0.8266113299557121
Chunk 501 does not have enough neighbors. Skipping...
Chunk 1885 does not have enough neighbors. Skipping...
Chunk 2996 does not have enough neighbors. Skipping...
Chunk 5648 does not have enough neighbors. Skipping...
Chunk 6042 does not have enough neighbors. Skipping...
Chunk 11226 does not have enough neighbors. Skipping...
Chunk 11366 does not have enough neighbors. Skipping...
Chunk 12149 does not have enough neighbors. Skipping...
Chunk 13361 does not have enough neighbors. Skipping...
Chunk 13833 does not have enough neighbors. Skipping...
Chunk 15590 does not have enough neighbors. Skipping...
Chunk 15899 does not have enough neighbors. Skipping...
Chunk 16889 does not have enough neighbors. Skipping...
Chunk 17195 does not have enough neighbors. Skipping...
Chunk 18498 does not have enough neighbors. Skipping...
Chunk 19251 does not have enough neighbors. Skipping...
Chunk 19608 does not have enough neighbors. Skipping...
Chunk 22113 does not have enough neighbors. Skipping...
Chunk 22518 does not have enough neighbors. Skipping...
Chunk 25777 does not have enough neighbors. Skipping...
Chunk 27447 does not have enough neighbors. Skipping...
Chunk 28892 does not have enough neighbors. Skipping...
Chunk 29712 does not have enough neighbors. Skipping...
Chunk 30448 does not have enough neighbors. Skipping...
2_GSE128639

AnnData object with n_obs × n_vars = 30672 × 3025
    obs: 'group', 'cell_type', 'batch', 'cluster'
    var: 'modality'
    uns: 'modality_lengths', 'neighbors', 'umap', 'cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'TotalVI', 'scArches', 'Seurat'
    layers: 'counts'
    obsp: 'distances', 'connectivities'

In [8]:
method_list = ['Garfield', 'Multigrate', 'TotalVI', 'scArches', 'Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_Protein'
dataset = '2_GSE128639'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result_best_reso.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

        ARI       NMI     cLISI      cASW       model      dataset
0  0.884222  0.860985  0.999245  0.675484    Garfield  2_GSE128639
1  0.835660  0.841850  0.995517  0.566655  Multigrate  2_GSE128639
2  0.877770  0.872664  0.998372  0.568177     TotalVI  2_GSE128639
3  0.872770  0.865969  0.999415  0.598213    scArches  2_GSE128639
4  0.663252  0.826611  0.999907  0.721279      Seurat  2_GSE128639

#### 利用最佳分辨率计算指标(Garfield);

In [6]:
## 记录resolution
reso_dict = {
    '2_GSE128639': {
        'Garfield': 0.4, # 1.10,
        'Multigrate': 1.9000000000000012,
        'TotalVI': 1.8000000000000012,
        'scArches': 1.33,
        'Seurat': 0.15690529804500009, 
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('2_GSE128639', reso_dict=reso_dict)
adata

the length of cell type: 27
method_reso is not None, using the 0.4 as resolution for Garfield...
Number of clusters: 17
the length of cell type: 27
method_reso is not None, using the 1.9000000000000012 as resolution for Multigrate...
Number of clusters: 27
the length of cell type: 27
method_reso is not None, using the 1.8000000000000012 as resolution for TotalVI...
Number of clusters: 27
the length of cell type: 27
method_reso is not None, using the 1.33 as resolution for scArches...
Number of clusters: 27
the length of cell type: 27
method_reso is not None, using the 0.15690529804500009 as resolution for Seurat...
Number of clusters: 27
Chunk 501 does not have enough neighbors. Skipping...
Chunk 1885 does not have enough neighbors. Skipping...
Chunk 2996 does not have enough neighbors. Skipping...
Chunk 5648 does not have enough neighbors. Skipping...
Chunk 6042 does not have enough neighbors. Skipping...
Chunk 11226 does not have enough neighbors. Skipping...
Chunk 11366 does not have enough neighbors. Skipping...
Chunk 12149 does not have enough neighbors. Skipping...
Chunk 13361 does not have enough neighbors. Skipping...
Chunk 13833 does not have enough neighbors. Skipping...
Chunk 15590 does not have enough neighbors. Skipping...
Chunk 15899 does not have enough neighbors. Skipping...
Chunk 16889 does not have enough neighbors. Skipping...
Chunk 17195 does not have enough neighbors. Skipping...
Chunk 18498 does not have enough neighbors. Skipping...
Chunk 19251 does not have enough neighbors. Skipping...
Chunk 19608 does not have enough neighbors. Skipping...
Chunk 22113 does not have enough neighbors. Skipping...
Chunk 22518 does not have enough neighbors. Skipping...
Chunk 25777 does not have enough neighbors. Skipping...
Chunk 27447 does not have enough neighbors. Skipping...
Chunk 28892 does not have enough neighbors. Skipping...
Chunk 29712 does not have enough neighbors. Skipping...
Chunk 30448 does not have enough neighbors. Skipping...
2_GSE128639

AnnData object with n_obs × n_vars = 30672 × 3025
    obs: 'group', 'cell_type', 'Garfield_cluster', 'Multigrate_cluster', 'TotalVI_cluster', 'scArches_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'TotalVI', 'TotalVI_cluster', 'scArches', 'scArches_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'TotalVI', 'scArches', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'TotalVI_distances', 'TotalVI_connectivities', 'scArches_distances', 'scArches_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [9]:
method_list = ['Garfield', 'Multigrate', 'TotalVI', 'scArches', 'Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_Protein'
dataset = '2_GSE128639'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

        ARI       NMI     cLISI      cASW       model      dataset
0  0.884222  0.860985  0.999245  0.675484    Garfield  2_GSE128639
1  0.488701  0.754594  0.995517  0.566655  Multigrate  2_GSE128639
2  0.588347  0.798205  0.998372  0.568177     TotalVI  2_GSE128639
3  0.568930  0.793671  0.999415  0.598213    scArches  2_GSE128639
4  0.514337  0.800190  0.999907  0.721279      Seurat  2_GSE128639

### 数据集 7_zenodo6368128/LUNG

In [17]:
## 记录resolution
reso_dict = {
    '7_zenodo6368128/LUNG': {
        'Garfield': 0.63,
        'Multigrate': 1.3000000000000007,
        'TotalVI': 0.8500000000000003,
        'scArches': 0.8000000000000003,
        'Seurat': 0.14121476824050008, 
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('7_zenodo6368128/LUNG', reso_dict=reso_dict)
adata

the length of cell type: 14
method_reso is not None, using the 0.63 as resolution for Garfield...
Number of clusters: 14
the length of cell type: 14
method_reso is not None, using the 1.3000000000000007 as resolution for Multigrate...
Number of clusters: 14
the length of cell type: 14
method_reso is not None, using the 0.8500000000000003 as resolution for TotalVI...
Number of clusters: 14
the length of cell type: 14
method_reso is not None, using the 0.8000000000000003 as resolution for scArches...
Number of clusters: 14
the length of cell type: 14
method_reso is not None, using the 0.14121476824050008 as resolution for Seurat...
Number of clusters: 14
Chunk 112 does not have enough neighbors. Skipping...
Chunk 125 does not have enough neighbors. Skipping...
Chunk 264 does not have enough neighbors. Skipping...
Chunk 265 does not have enough neighbors. Skipping...
Chunk 304 does not have enough neighbors. Skipping...
Chunk 357 does not have enough neighbors. Skipping...
Chunk 387 does not have enough neighbors. Skipping...
Chunk 557 does not have enough neighbors. Skipping...
Chunk 595 does not have enough neighbors. Skipping...
Chunk 795 does not have enough neighbors. Skipping...
Chunk 1125 does not have enough neighbors. Skipping...
Chunk 1163 does not have enough neighbors. Skipping...
Chunk 1462 does not have enough neighbors. Skipping...
Chunk 1479 does not have enough neighbors. Skipping...
Chunk 1502 does not have enough neighbors. Skipping...
Chunk 1580 does not have enough neighbors. Skipping...
Chunk 1802 does not have enough neighbors. Skipping...
Chunk 1810 does not have enough neighbors. Skipping...
Chunk 2019 does not have enough neighbors. Skipping...
Chunk 2032 does not have enough neighbors. Skipping...
Chunk 2120 does not have enough neighbors. Skipping...
Chunk 2261 does not have enough neighbors. Skipping...
Chunk 2367 does not have enough neighbors. Skipping...
Chunk 2369 does not have enough neighbors. Skipping...
Chunk 2451 does not have enough neighbors. Skipping...
Chunk 2562 does not have enough neighbors. Skipping...
Chunk 2756 does not have enough neighbors. Skipping...
Chunk 2788 does not have enough neighbors. Skipping...
Chunk 2821 does not have enough neighbors. Skipping...
Chunk 3092 does not have enough neighbors. Skipping...
Chunk 3107 does not have enough neighbors. Skipping...
Chunk 3125 does not have enough neighbors. Skipping...
7_zenodo6368128/LUNG

AnnData object with n_obs × n_vars = 3362 × 3052
    obs: 'group', 'cell_type', 'Garfield_cluster', 'Multigrate_cluster', 'TotalVI_cluster', 'scArches_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'TotalVI', 'TotalVI_cluster', 'scArches', 'scArches_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'TotalVI', 'scArches', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'TotalVI_distances', 'TotalVI_connectivities', 'scArches_distances', 'scArches_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [18]:
import matplotlib.pyplot as plt

dataset = '7_zenodo6368128/LUNG'
res_dir = f'/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_Protein/{dataset}'

latent_key_list = ['Garfield', 'Multigrate', 'TotalVI', 'scArches', 'Seurat']
for latent_key in latent_key_list:
    sc.tl.umap(adata, neighbors_key=latent_key)
    latent_key_cluster = latent_key + '_cluster'
    
    # Create a new figure for each plot with an appropriate size
    plt.figure(figsize=(12, 6))  # Adjust the figsize as needed
    sc.pl.umap(adata, color=['cell_type', latent_key_cluster], wspace=0.5, hspace=0.5, show=False, ncols=2)
    # Save the figure
    plt.savefig(res_dir + f"/{latent_key}_UMAP_clusters.png", bbox_inches='tight')  # Use bbox_inches to ensure full legend display
    plt.close()

In [19]:
method_list = ['Garfield', 'Multigrate', 'TotalVI', 'scArches', 'Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_Protein'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

        ARI       NMI     cLISI      cASW       model               dataset
0  0.502827  0.657247  0.968007  0.587787    Garfield  7_zenodo6368128/LUNG
1  0.493512  0.655153  0.970092  0.576290  Multigrate  7_zenodo6368128/LUNG
2  0.543276  0.683371  0.960239  0.518085     TotalVI  7_zenodo6368128/LUNG
3  0.508653  0.653584  0.964376  0.549389    scArches  7_zenodo6368128/LUNG
4  0.503213  0.720922  0.988793  0.609620      Seurat  7_zenodo6368128/LUNG

#### 探索一下用最佳分辨率

In [20]:
# calculate the metrics based on the best resolution
adata = count_metrics_for_best_resolution('7_zenodo6368128/LUNG')
adata

resolution: 0.1, nmi: 0.6644695558697086
resolution: 0.2, nmi: 0.6814641468342751
resolution: 0.3, nmi: 0.681337585476829
resolution: 0.4, nmi: 0.6644673781401533
resolution: 0.5, nmi: 0.6564463148555076
resolution: 0.6, nmi: 0.6569589951078442
resolution: 0.7, nmi: 0.6486060000767506
resolution: 0.8, nmi: 0.638851076551211
resolution: 0.9, nmi: 0.6218751666499897
resolution: 1.0, nmi: 0.6199829310491367
resolution: 1.1, nmi: 0.6156395521040775
resolution: 1.2, nmi: 0.6031407467464517
resolution: 1.3, nmi: 0.6082796233390295
resolution: 1.4, nmi: 0.6071980881203342
resolution: 1.5, nmi: 0.600558774148804
resolution: 1.6, nmi: 0.596173986506624
resolution: 1.7, nmi: 0.5893560842811468
resolution: 1.8, nmi: 0.5886770668823079
resolution: 1.9, nmi: 0.589861313142517
resolution: 2.0, nmi: 0.5868339028666859
optimised clustering against cell_type
optimal cluster resolution: 0.2
optimal score: 0.6814641468342751
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.6499171479619003
resolution: 0.2, nmi: 0.7046109378604766
resolution: 0.3, nmi: 0.708284851623997
resolution: 0.4, nmi: 0.7033515072873255
resolution: 0.5, nmi: 0.6797655669497223
resolution: 0.6, nmi: 0.679636669126061
resolution: 0.7, nmi: 0.6808370546040274
resolution: 0.8, nmi: 0.6861887906749498
resolution: 0.9, nmi: 0.6818666431192302
resolution: 1.0, nmi: 0.6794004280994754
resolution: 1.1, nmi: 0.6815420997195157
resolution: 1.2, nmi: 0.6654762959062844
resolution: 1.3, nmi: 0.6551527145505674
resolution: 1.4, nmi: 0.6504863074125432
resolution: 1.5, nmi: 0.6472010113848097
resolution: 1.6, nmi: 0.6401499945479618
resolution: 1.7, nmi: 0.6408834086786425
resolution: 1.8, nmi: 0.637601930555222
resolution: 1.9, nmi: 0.6336476906780141
resolution: 2.0, nmi: 0.6358137769126305
optimised clustering against cell_type
optimal cluster resolution: 0.3
optimal score: 0.708284851623997
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.6261341275729744
resolution: 0.2, nmi: 0.7038985590248034
resolution: 0.3, nmi: 0.7310338616255035
resolution: 0.4, nmi: 0.7275719186000597
resolution: 0.5, nmi: 0.7045433738991679
resolution: 0.6, nmi: 0.6888211236365185
resolution: 0.7, nmi: 0.6802603465055467
resolution: 0.8, nmi: 0.6807236813957364
resolution: 0.9, nmi: 0.6798494385285444
resolution: 1.0, nmi: 0.6749401936239358
resolution: 1.1, nmi: 0.6765025510066335
resolution: 1.2, nmi: 0.6463648901030926
resolution: 1.3, nmi: 0.6479982404232947
resolution: 1.4, nmi: 0.6504140605932798
resolution: 1.5, nmi: 0.6474456063913286
resolution: 1.6, nmi: 0.6463333133446381
resolution: 1.7, nmi: 0.6398326148883803
resolution: 1.8, nmi: 0.6434116427925395
resolution: 1.9, nmi: 0.6326400471982323
resolution: 2.0, nmi: 0.6297431645106507
optimised clustering against cell_type
optimal cluster resolution: 0.3
optimal score: 0.7310338616255035
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.6205026523315478
resolution: 0.2, nmi: 0.6786397709137376
resolution: 0.3, nmi: 0.6887649721869009
resolution: 0.4, nmi: 0.6897739577224152
resolution: 0.5, nmi: 0.6699829339536073
resolution: 0.6, nmi: 0.6596852159950439
resolution: 0.7, nmi: 0.6547153533015452
resolution: 0.8, nmi: 0.6535842619776928
resolution: 0.9, nmi: 0.6500896520983754
resolution: 1.0, nmi: 0.6541972836193661
resolution: 1.1, nmi: 0.6451799851003376
resolution: 1.2, nmi: 0.6474709972635138
resolution: 1.3, nmi: 0.6433943309171604
resolution: 1.4, nmi: 0.636801729394318
resolution: 1.5, nmi: 0.6197746449941834
resolution: 1.6, nmi: 0.6231925035978504
resolution: 1.7, nmi: 0.6190183359647892
resolution: 1.8, nmi: 0.6196358996218321
resolution: 1.9, nmi: 0.6088247990414523
resolution: 2.0, nmi: 0.5961943937771279
optimised clustering against cell_type
optimal cluster resolution: 0.4
optimal score: 0.6897739577224152
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.7358524144544281
resolution: 0.2, nmi: 0.6902771232511157
resolution: 0.3, nmi: 0.6902771232511157
resolution: 0.4, nmi: 0.6762939970909391
resolution: 0.5, nmi: 0.6587636327869812
resolution: 0.6, nmi: 0.6461454209949096
resolution: 0.7, nmi: 0.6412067422491016
resolution: 0.8, nmi: 0.6382199235404108
resolution: 0.9, nmi: 0.6290232867351713
resolution: 1.0, nmi: 0.6235101311512226
resolution: 1.1, nmi: 0.6206248070870969
resolution: 1.2, nmi: 0.6206584897235248
resolution: 1.3, nmi: 0.6073671073567806
resolution: 1.4, nmi: 0.6059583652295504
resolution: 1.5, nmi: 0.6015095167555999
resolution: 1.6, nmi: 0.6025923337333736
resolution: 1.7, nmi: 0.6009394652038821
resolution: 1.8, nmi: 0.5964466842573569
resolution: 1.9, nmi: 0.5900328239763594
resolution: 2.0, nmi: 0.5843458462560313
optimised clustering against cell_type
optimal cluster resolution: 0.1
optimal score: 0.7358524144544281
Chunk 112 does not have enough neighbors. Skipping...
Chunk 125 does not have enough neighbors. Skipping...
Chunk 264 does not have enough neighbors. Skipping...
Chunk 265 does not have enough neighbors. Skipping...
Chunk 304 does not have enough neighbors. Skipping...
Chunk 357 does not have enough neighbors. Skipping...
Chunk 387 does not have enough neighbors. Skipping...
Chunk 557 does not have enough neighbors. Skipping...
Chunk 595 does not have enough neighbors. Skipping...
Chunk 795 does not have enough neighbors. Skipping...
Chunk 1125 does not have enough neighbors. Skipping...
Chunk 1163 does not have enough neighbors. Skipping...
Chunk 1462 does not have enough neighbors. Skipping...
Chunk 1479 does not have enough neighbors. Skipping...
Chunk 1502 does not have enough neighbors. Skipping...
Chunk 1580 does not have enough neighbors. Skipping...
Chunk 1802 does not have enough neighbors. Skipping...
Chunk 1810 does not have enough neighbors. Skipping...
Chunk 2019 does not have enough neighbors. Skipping...
Chunk 2032 does not have enough neighbors. Skipping...
Chunk 2120 does not have enough neighbors. Skipping...
Chunk 2261 does not have enough neighbors. Skipping...
Chunk 2367 does not have enough neighbors. Skipping...
Chunk 2369 does not have enough neighbors. Skipping...
Chunk 2451 does not have enough neighbors. Skipping...
Chunk 2562 does not have enough neighbors. Skipping...
Chunk 2756 does not have enough neighbors. Skipping...
Chunk 2788 does not have enough neighbors. Skipping...
Chunk 2821 does not have enough neighbors. Skipping...
Chunk 3092 does not have enough neighbors. Skipping...
Chunk 3107 does not have enough neighbors. Skipping...
Chunk 3125 does not have enough neighbors. Skipping...
7_zenodo6368128/LUNG

AnnData object with n_obs × n_vars = 3362 × 3052
    obs: 'group', 'cell_type', 'batch', 'cluster'
    var: 'modality'
    uns: 'modality_lengths', 'neighbors', 'umap', 'cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'TotalVI', 'scArches', 'Seurat'
    layers: 'counts'
    obsp: 'distances', 'connectivities'

In [21]:
method_list = ['Garfield', 'Multigrate', 'TotalVI', 'scArches', 'Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_Protein'
dataset = '7_zenodo6368128/LUNG'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result_best_reso.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

        ARI       NMI     cLISI      cASW       model               dataset
0  0.565790  0.681464  0.968007  0.587787    Garfield  7_zenodo6368128/LUNG
1  0.638010  0.708285  0.970092  0.576290  Multigrate  7_zenodo6368128/LUNG
2  0.629156  0.731034  0.960239  0.518085     TotalVI  7_zenodo6368128/LUNG
3  0.587091  0.689774  0.964376  0.549389    scArches  7_zenodo6368128/LUNG
4  0.565291  0.735852  0.988793  0.609620      Seurat  7_zenodo6368128/LUNG

#### 利用最佳分辨率计算指标(Garfield);

In [22]:
## 记录resolution
reso_dict = {
    '7_zenodo6368128/LUNG': {
        'Garfield': 0.2,
        'Multigrate': 1.3000000000000007,
        'TotalVI': 0.8500000000000003,
        'scArches': 0.8000000000000003,
        'Seurat': 0.14121476824050008, 
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('7_zenodo6368128/LUNG', reso_dict=reso_dict)
adata

the length of cell type: 14
method_reso is not None, using the 0.2 as resolution for Garfield...
Number of clusters: 8
the length of cell type: 14
method_reso is not None, using the 1.3000000000000007 as resolution for Multigrate...
Number of clusters: 14
the length of cell type: 14
method_reso is not None, using the 0.8500000000000003 as resolution for TotalVI...
Number of clusters: 14
the length of cell type: 14
method_reso is not None, using the 0.8000000000000003 as resolution for scArches...
Number of clusters: 14
the length of cell type: 14
method_reso is not None, using the 0.14121476824050008 as resolution for Seurat...
Number of clusters: 14
Chunk 112 does not have enough neighbors. Skipping...
Chunk 125 does not have enough neighbors. Skipping...
Chunk 264 does not have enough neighbors. Skipping...
Chunk 265 does not have enough neighbors. Skipping...
Chunk 304 does not have enough neighbors. Skipping...
Chunk 357 does not have enough neighbors. Skipping...
Chunk 387 does not have enough neighbors. Skipping...
Chunk 557 does not have enough neighbors. Skipping...
Chunk 595 does not have enough neighbors. Skipping...
Chunk 795 does not have enough neighbors. Skipping...
Chunk 1125 does not have enough neighbors. Skipping...
Chunk 1163 does not have enough neighbors. Skipping...
Chunk 1462 does not have enough neighbors. Skipping...
Chunk 1479 does not have enough neighbors. Skipping...
Chunk 1502 does not have enough neighbors. Skipping...
Chunk 1580 does not have enough neighbors. Skipping...
Chunk 1802 does not have enough neighbors. Skipping...
Chunk 1810 does not have enough neighbors. Skipping...
Chunk 2019 does not have enough neighbors. Skipping...
Chunk 2032 does not have enough neighbors. Skipping...
Chunk 2120 does not have enough neighbors. Skipping...
Chunk 2261 does not have enough neighbors. Skipping...
Chunk 2367 does not have enough neighbors. Skipping...
Chunk 2369 does not have enough neighbors. Skipping...
Chunk 2451 does not have enough neighbors. Skipping...
Chunk 2562 does not have enough neighbors. Skipping...
Chunk 2756 does not have enough neighbors. Skipping...
Chunk 2788 does not have enough neighbors. Skipping...
Chunk 2821 does not have enough neighbors. Skipping...
Chunk 3092 does not have enough neighbors. Skipping...
Chunk 3107 does not have enough neighbors. Skipping...
Chunk 3125 does not have enough neighbors. Skipping...
7_zenodo6368128/LUNG

AnnData object with n_obs × n_vars = 3362 × 3052
    obs: 'group', 'cell_type', 'Garfield_cluster', 'Multigrate_cluster', 'TotalVI_cluster', 'scArches_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'TotalVI', 'TotalVI_cluster', 'scArches', 'scArches_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'TotalVI', 'scArches', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'TotalVI_distances', 'TotalVI_connectivities', 'scArches_distances', 'scArches_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [24]:
method_list = ['Garfield', 'Multigrate', 'TotalVI', 'scArches', 'Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_Protein'
dataset = '7_zenodo6368128/LUNG'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

        ARI       NMI     cLISI      cASW       model               dataset
0  0.565790  0.681464  0.968007  0.587787    Garfield  7_zenodo6368128/LUNG
1  0.493512  0.655153  0.970092  0.576290  Multigrate  7_zenodo6368128/LUNG
2  0.543276  0.683371  0.960239  0.518085     TotalVI  7_zenodo6368128/LUNG
3  0.508653  0.653584  0.964376  0.549389    scArches  7_zenodo6368128/LUNG
4  0.503213  0.720922  0.988793  0.609620      Seurat  7_zenodo6368128/LUNG

### 数据集 7_zenodo6368128/PBMC

In [31]:
## 记录resolution
reso_dict = {
    '7_zenodo6368128/PBMC': {
        'Garfield': 0.7500000000000002,
        'Multigrate': 0.8500000000000003,
        'TotalVI': 0.84,
        'scArches': 0.5,
        'Seurat': 0.098, 
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('7_zenodo6368128/PBMC', reso_dict=reso_dict)
adata

the length of cell type: 11
method_reso is not None, using the 0.7500000000000002 as resolution for Garfield...
Number of clusters: 11
the length of cell type: 11
method_reso is not None, using the 0.8500000000000003 as resolution for Multigrate...
Number of clusters: 11
the length of cell type: 11
method_reso is not None, using the 0.84 as resolution for TotalVI...
Number of clusters: 11
the length of cell type: 11
method_reso is not None, using the 0.5 as resolution for scArches...
Number of clusters: 11
the length of cell type: 11
method_reso is not None, using the 0.098 as resolution for Seurat...
Number of clusters: 11
Chunk 178 does not have enough neighbors. Skipping...
Chunk 245 does not have enough neighbors. Skipping...
Chunk 405 does not have enough neighbors. Skipping...
Chunk 550 does not have enough neighbors. Skipping...
Chunk 563 does not have enough neighbors. Skipping...
Chunk 573 does not have enough neighbors. Skipping...
Chunk 873 does not have enough neighbors. Skipping...
Chunk 925 does not have enough neighbors. Skipping...
Chunk 966 does not have enough neighbors. Skipping...
Chunk 1047 does not have enough neighbors. Skipping...
Chunk 1164 does not have enough neighbors. Skipping...
Chunk 1173 does not have enough neighbors. Skipping...
Chunk 1182 does not have enough neighbors. Skipping...
Chunk 1230 does not have enough neighbors. Skipping...
Chunk 1296 does not have enough neighbors. Skipping...
Chunk 1359 does not have enough neighbors. Skipping...
Chunk 1405 does not have enough neighbors. Skipping...
Chunk 1562 does not have enough neighbors. Skipping...
Chunk 1586 does not have enough neighbors. Skipping...
Chunk 1605 does not have enough neighbors. Skipping...
Chunk 1684 does not have enough neighbors. Skipping...
Chunk 1704 does not have enough neighbors. Skipping...
Chunk 1762 does not have enough neighbors. Skipping...
Chunk 1843 does not have enough neighbors. Skipping...
Chunk 1980 does not have enough neighbors. Skipping...
Chunk 2105 does not have enough neighbors. Skipping...
Chunk 2112 does not have enough neighbors. Skipping...
Chunk 2190 does not have enough neighbors. Skipping...
Chunk 2281 does not have enough neighbors. Skipping...
Chunk 2325 does not have enough neighbors. Skipping...
Chunk 2370 does not have enough neighbors. Skipping...
Chunk 2432 does not have enough neighbors. Skipping...
Chunk 2461 does not have enough neighbors. Skipping...
Chunk 2927 does not have enough neighbors. Skipping...
Chunk 2963 does not have enough neighbors. Skipping...
Chunk 3004 does not have enough neighbors. Skipping...
Chunk 3162 does not have enough neighbors. Skipping...
Chunk 3244 does not have enough neighbors. Skipping...
Chunk 3466 does not have enough neighbors. Skipping...
Chunk 3479 does not have enough neighbors. Skipping...
Chunk 3481 does not have enough neighbors. Skipping...
Chunk 3647 does not have enough neighbors. Skipping...
Chunk 3661 does not have enough neighbors. Skipping...
Chunk 3693 does not have enough neighbors. Skipping...
Chunk 3808 does not have enough neighbors. Skipping...
Chunk 3988 does not have enough neighbors. Skipping...
Chunk 4146 does not have enough neighbors. Skipping...
Chunk 4181 does not have enough neighbors. Skipping...
Chunk 4201 does not have enough neighbors. Skipping...
Chunk 4262 does not have enough neighbors. Skipping...
Chunk 4324 does not have enough neighbors. Skipping...
Chunk 4521 does not have enough neighbors. Skipping...
Chunk 4680 does not have enough neighbors. Skipping...
Chunk 4687 does not have enough neighbors. Skipping...
Chunk 4807 does not have enough neighbors. Skipping...
Chunk 4954 does not have enough neighbors. Skipping...
Chunk 5274 does not have enough neighbors. Skipping...
Chunk 5347 does not have enough neighbors. Skipping...
Chunk 5375 does not have enough neighbors. Skipping...
Chunk 5429 does not have enough neighbors. Skipping...
Chunk 5449 does not have enough neighbors. Skipping...
Chunk 5606 does not have enough neighbors. Skipping...
Chunk 5800 does not have enough neighbors. Skipping...
Chunk 5891 does not have enough neighbors. Skipping...
Chunk 6063 does not have enough neighbors. Skipping...
Chunk 6207 does not have enough neighbors. Skipping...
Chunk 6336 does not have enough neighbors. Skipping...
Chunk 6419 does not have enough neighbors. Skipping...
Chunk 6465 does not have enough neighbors. Skipping...
Chunk 6500 does not have enough neighbors. Skipping...
Chunk 6509 does not have enough neighbors. Skipping...
Chunk 6564 does not have enough neighbors. Skipping...
Chunk 6700 does not have enough neighbors. Skipping...
Chunk 6750 does not have enough neighbors. Skipping...
Chunk 6866 does not have enough neighbors. Skipping...
Chunk 6893 does not have enough neighbors. Skipping...
Chunk 7058 does not have enough neighbors. Skipping...
Chunk 7080 does not have enough neighbors. Skipping...
7_zenodo6368128/PBMC

AnnData object with n_obs × n_vars = 7108 × 3052
    obs: 'group', 'cell_type', 'Garfield_cluster', 'Multigrate_cluster', 'TotalVI_cluster', 'scArches_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'TotalVI', 'TotalVI_cluster', 'scArches', 'scArches_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'TotalVI', 'scArches', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'TotalVI_distances', 'TotalVI_connectivities', 'scArches_distances', 'scArches_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [32]:
import matplotlib.pyplot as plt

dataset = '7_zenodo6368128/PBMC'
res_dir = f'/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_Protein/{dataset}'

latent_key_list = ['Garfield', 'Multigrate', 'TotalVI', 'scArches', 'Seurat']
for latent_key in latent_key_list:
    sc.tl.umap(adata, neighbors_key=latent_key)
    latent_key_cluster = latent_key + '_cluster'
    
    # Create a new figure for each plot with an appropriate size
    plt.figure(figsize=(12, 6))  # Adjust the figsize as needed
    sc.pl.umap(adata, color=['cell_type', latent_key_cluster], wspace=0.5, hspace=0.5, show=False, ncols=2)
    # Save the figure
    plt.savefig(res_dir + f"/{latent_key}_UMAP_clusters.png", bbox_inches='tight')  # Use bbox_inches to ensure full legend display
    plt.close()

In [33]:
method_list = ['Garfield', 'Multigrate', 'TotalVI', 'scArches', 'Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_Protein'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

        ARI       NMI     cLISI      cASW       model               dataset
0  0.410132  0.640581  0.972405  0.588073    Garfield  7_zenodo6368128/PBMC
1  0.415778  0.617059  0.940645  0.533962  Multigrate  7_zenodo6368128/PBMC
2  0.467543  0.668589  0.926176  0.523700     TotalVI  7_zenodo6368128/PBMC
3  0.435581  0.591365  0.944616  0.522045    scArches  7_zenodo6368128/PBMC
4  0.422766  0.667751  0.984696  0.630589      Seurat  7_zenodo6368128/PBMC

#### 探索一下用最佳分辨率

In [34]:
# calculate the metrics based on the best resolution
adata = count_metrics_for_best_resolution('7_zenodo6368128/PBMC')
adata

resolution: 0.1, nmi: 0.7045669196987505
resolution: 0.2, nmi: 0.7040936405475081
resolution: 0.3, nmi: 0.7205885851480783
resolution: 0.4, nmi: 0.7104931369492323
resolution: 0.5, nmi: 0.6709402505709019
resolution: 0.6, nmi: 0.6713295133715153
resolution: 0.7, nmi: 0.6540703032203694
resolution: 0.8, nmi: 0.6470365429842112
resolution: 0.9, nmi: 0.6420635132291619
resolution: 1.0, nmi: 0.6362029863885618
resolution: 1.1, nmi: 0.6342888505636097
resolution: 1.2, nmi: 0.6154469403548659
resolution: 1.3, nmi: 0.5982622762585442
resolution: 1.4, nmi: 0.6105697546713903
resolution: 1.5, nmi: 0.6029148420014858
resolution: 1.6, nmi: 0.6061772811323619
resolution: 1.7, nmi: 0.6005563366163184
resolution: 1.8, nmi: 0.5933744985630317
resolution: 1.9, nmi: 0.6025190440512225
resolution: 2.0, nmi: 0.5936765348885282
optimised clustering against cell_type
optimal cluster resolution: 0.3
optimal score: 0.7205885851480783
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.6509998007150417
resolution: 0.2, nmi: 0.6680341874881333
resolution: 0.3, nmi: 0.6903352440930147
resolution: 0.4, nmi: 0.6750921654730228
resolution: 0.5, nmi: 0.6656897820881211
resolution: 0.6, nmi: 0.6332018485100825
resolution: 0.7, nmi: 0.6335364774644534
resolution: 0.8, nmi: 0.6211602792786339
resolution: 0.9, nmi: 0.6278959309516254
resolution: 1.0, nmi: 0.6353512316582143
resolution: 1.1, nmi: 0.6039082585543925
resolution: 1.2, nmi: 0.6002896025989156
resolution: 1.3, nmi: 0.600382307374798
resolution: 1.4, nmi: 0.6035551188363293
resolution: 1.5, nmi: 0.5868121464365366
resolution: 1.6, nmi: 0.5877349028661761
resolution: 1.7, nmi: 0.5771692517085043
resolution: 1.8, nmi: 0.5696833053691898
resolution: 1.9, nmi: 0.5637180797381226
resolution: 2.0, nmi: 0.5538245096352187
optimised clustering against cell_type
optimal cluster resolution: 0.3
optimal score: 0.6903352440930147
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.6113007894031095
resolution: 0.2, nmi: 0.6451532623287438
resolution: 0.3, nmi: 0.7109841940431639
resolution: 0.4, nmi: 0.7187172144428811
resolution: 0.5, nmi: 0.7093670662439145
resolution: 0.6, nmi: 0.7078738396742833
resolution: 0.7, nmi: 0.7095169193980786
resolution: 0.8, nmi: 0.7076706167842152
resolution: 0.9, nmi: 0.6402773671251597
resolution: 1.0, nmi: 0.6310302138288231
resolution: 1.1, nmi: 0.6136513414688339
resolution: 1.2, nmi: 0.6042497916170314
resolution: 1.3, nmi: 0.6066114561940221
resolution: 1.4, nmi: 0.597167151086739
resolution: 1.5, nmi: 0.5929563247279287
resolution: 1.6, nmi: 0.59835556442898
resolution: 1.7, nmi: 0.5926245603416728
resolution: 1.8, nmi: 0.5846254024359707
resolution: 1.9, nmi: 0.5887190897083212
resolution: 2.0, nmi: 0.5693782101787028
optimised clustering against cell_type
optimal cluster resolution: 0.4
optimal score: 0.7187172144428811
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.6595345207739932
resolution: 0.2, nmi: 0.658367933085881
resolution: 0.3, nmi: 0.6666619423895904
resolution: 0.4, nmi: 0.6127174405796693
resolution: 0.5, nmi: 0.5913645099153103
resolution: 0.6, nmi: 0.5817588915330362
resolution: 0.7, nmi: 0.5584212417816515
resolution: 0.8, nmi: 0.5635554130154014
resolution: 0.9, nmi: 0.562494010883967
resolution: 1.0, nmi: 0.5587223932444847
resolution: 1.1, nmi: 0.5539351573790297
resolution: 1.2, nmi: 0.5553107579217383
resolution: 1.3, nmi: 0.5519084394367573
resolution: 1.4, nmi: 0.5510871999917389
resolution: 1.5, nmi: 0.5404009061471442
resolution: 1.6, nmi: 0.5351945326320834
resolution: 1.7, nmi: 0.5243340242815794
resolution: 1.8, nmi: 0.5267683838648809
resolution: 1.9, nmi: 0.5225940294485063
resolution: 2.0, nmi: 0.5234016978514117
optimised clustering against cell_type
optimal cluster resolution: 0.3
optimal score: 0.6666619423895904
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.6712509481888517
resolution: 0.2, nmi: 0.6355728067157008
resolution: 0.3, nmi: 0.6163326084709259
resolution: 0.4, nmi: 0.5998202314761332
resolution: 0.5, nmi: 0.585013918222391
resolution: 0.6, nmi: 0.5762046879785717
resolution: 0.7, nmi: 0.5639936056934722
resolution: 0.8, nmi: 0.5567538248705509
resolution: 0.9, nmi: 0.5597515803586316
resolution: 1.0, nmi: 0.5489981588663322
resolution: 1.1, nmi: 0.5467669009164263
resolution: 1.2, nmi: 0.538928350378125
resolution: 1.3, nmi: 0.5374506781392207
resolution: 1.4, nmi: 0.5331702746720304
resolution: 1.5, nmi: 0.5300268082914099
resolution: 1.6, nmi: 0.5248248227665457
resolution: 1.7, nmi: 0.5251837138170596
resolution: 1.8, nmi: 0.5210487067298321
resolution: 1.9, nmi: 0.5189910013027261
resolution: 2.0, nmi: 0.5186796105033173
optimised clustering against cell_type
optimal cluster resolution: 0.1
optimal score: 0.6712509481888517
Chunk 178 does not have enough neighbors. Skipping...
Chunk 245 does not have enough neighbors. Skipping...
Chunk 405 does not have enough neighbors. Skipping...
Chunk 550 does not have enough neighbors. Skipping...
Chunk 563 does not have enough neighbors. Skipping...
Chunk 573 does not have enough neighbors. Skipping...
Chunk 873 does not have enough neighbors. Skipping...
Chunk 925 does not have enough neighbors. Skipping...
Chunk 966 does not have enough neighbors. Skipping...
Chunk 1047 does not have enough neighbors. Skipping...
Chunk 1164 does not have enough neighbors. Skipping...
Chunk 1173 does not have enough neighbors. Skipping...
Chunk 1182 does not have enough neighbors. Skipping...
Chunk 1230 does not have enough neighbors. Skipping...
Chunk 1296 does not have enough neighbors. Skipping...
Chunk 1359 does not have enough neighbors. Skipping...
Chunk 1405 does not have enough neighbors. Skipping...
Chunk 1562 does not have enough neighbors. Skipping...
Chunk 1586 does not have enough neighbors. Skipping...
Chunk 1605 does not have enough neighbors. Skipping...
Chunk 1684 does not have enough neighbors. Skipping...
Chunk 1704 does not have enough neighbors. Skipping...
Chunk 1762 does not have enough neighbors. Skipping...
Chunk 1843 does not have enough neighbors. Skipping...
Chunk 1980 does not have enough neighbors. Skipping...
Chunk 2105 does not have enough neighbors. Skipping...
Chunk 2112 does not have enough neighbors. Skipping...
Chunk 2190 does not have enough neighbors. Skipping...
Chunk 2281 does not have enough neighbors. Skipping...
Chunk 2325 does not have enough neighbors. Skipping...
Chunk 2370 does not have enough neighbors. Skipping...
Chunk 2432 does not have enough neighbors. Skipping...
Chunk 2461 does not have enough neighbors. Skipping...
Chunk 2927 does not have enough neighbors. Skipping...
Chunk 2963 does not have enough neighbors. Skipping...
Chunk 3004 does not have enough neighbors. Skipping...
Chunk 3162 does not have enough neighbors. Skipping...
Chunk 3244 does not have enough neighbors. Skipping...
Chunk 3466 does not have enough neighbors. Skipping...
Chunk 3479 does not have enough neighbors. Skipping...
Chunk 3481 does not have enough neighbors. Skipping...
Chunk 3647 does not have enough neighbors. Skipping...
Chunk 3661 does not have enough neighbors. Skipping...
Chunk 3693 does not have enough neighbors. Skipping...
Chunk 3808 does not have enough neighbors. Skipping...
Chunk 3988 does not have enough neighbors. Skipping...
Chunk 4146 does not have enough neighbors. Skipping...
Chunk 4181 does not have enough neighbors. Skipping...
Chunk 4201 does not have enough neighbors. Skipping...
Chunk 4262 does not have enough neighbors. Skipping...
Chunk 4324 does not have enough neighbors. Skipping...
Chunk 4521 does not have enough neighbors. Skipping...
Chunk 4680 does not have enough neighbors. Skipping...
Chunk 4687 does not have enough neighbors. Skipping...
Chunk 4807 does not have enough neighbors. Skipping...
Chunk 4954 does not have enough neighbors. Skipping...
Chunk 5274 does not have enough neighbors. Skipping...
Chunk 5347 does not have enough neighbors. Skipping...
Chunk 5375 does not have enough neighbors. Skipping...
Chunk 5429 does not have enough neighbors. Skipping...
Chunk 5449 does not have enough neighbors. Skipping...
Chunk 5606 does not have enough neighbors. Skipping...
Chunk 5800 does not have enough neighbors. Skipping...
Chunk 5891 does not have enough neighbors. Skipping...
Chunk 6063 does not have enough neighbors. Skipping...
Chunk 6207 does not have enough neighbors. Skipping...
Chunk 6336 does not have enough neighbors. Skipping...
Chunk 6419 does not have enough neighbors. Skipping...
Chunk 6465 does not have enough neighbors. Skipping...
Chunk 6500 does not have enough neighbors. Skipping...
Chunk 6509 does not have enough neighbors. Skipping...
Chunk 6564 does not have enough neighbors. Skipping...
Chunk 6700 does not have enough neighbors. Skipping...
Chunk 6750 does not have enough neighbors. Skipping...
Chunk 6866 does not have enough neighbors. Skipping...
Chunk 6893 does not have enough neighbors. Skipping...
Chunk 7058 does not have enough neighbors. Skipping...
Chunk 7080 does not have enough neighbors. Skipping...
7_zenodo6368128/PBMC

AnnData object with n_obs × n_vars = 7108 × 3052
    obs: 'group', 'cell_type', 'batch', 'cluster'
    var: 'modality'
    uns: 'modality_lengths', 'neighbors', 'umap', 'cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'TotalVI', 'scArches', 'Seurat'
    layers: 'counts'
    obsp: 'distances', 'connectivities'

In [35]:
method_list = ['Garfield', 'Multigrate', 'TotalVI', 'scArches', 'Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_Protein'
dataset = '7_zenodo6368128/PBMC'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result_best_reso.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

        ARI       NMI     cLISI      cASW       model               dataset
0  0.674712  0.720589  0.972405  0.588073    Garfield  7_zenodo6368128/PBMC
1  0.562749  0.690335  0.940645  0.533962  Multigrate  7_zenodo6368128/PBMC
2  0.639528  0.718717  0.926176  0.523700     TotalVI  7_zenodo6368128/PBMC
3  0.563754  0.666662  0.944616  0.522045    scArches  7_zenodo6368128/PBMC
4  0.425793  0.671251  0.984696  0.630589      Seurat  7_zenodo6368128/PBMC

#### 利用最佳分辨率计算指标(Garfield);

In [36]:
## 记录resolution
reso_dict = {
    '7_zenodo6368128/PBMC': {
        'Garfield': 0.3, # 0.7500000000000002,
        'Multigrate': 0.8500000000000003,
        'TotalVI': 0.84,
        'scArches': 0.5,
        'Seurat': 0.098, 
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('7_zenodo6368128/PBMC', reso_dict=reso_dict)
adata

the length of cell type: 11
method_reso is not None, using the 0.3 as resolution for Garfield...
Number of clusters: 8
the length of cell type: 11
method_reso is not None, using the 0.8500000000000003 as resolution for Multigrate...
Number of clusters: 11
the length of cell type: 11
method_reso is not None, using the 0.84 as resolution for TotalVI...
Number of clusters: 11
the length of cell type: 11
method_reso is not None, using the 0.5 as resolution for scArches...
Number of clusters: 11
the length of cell type: 11
method_reso is not None, using the 0.098 as resolution for Seurat...
Number of clusters: 11
Chunk 178 does not have enough neighbors. Skipping...
Chunk 245 does not have enough neighbors. Skipping...
Chunk 405 does not have enough neighbors. Skipping...
Chunk 550 does not have enough neighbors. Skipping...
Chunk 563 does not have enough neighbors. Skipping...
Chunk 573 does not have enough neighbors. Skipping...
Chunk 873 does not have enough neighbors. Skipping...
Chunk 925 does not have enough neighbors. Skipping...
Chunk 966 does not have enough neighbors. Skipping...
Chunk 1047 does not have enough neighbors. Skipping...
Chunk 1164 does not have enough neighbors. Skipping...
Chunk 1173 does not have enough neighbors. Skipping...
Chunk 1182 does not have enough neighbors. Skipping...
Chunk 1230 does not have enough neighbors. Skipping...
Chunk 1296 does not have enough neighbors. Skipping...
Chunk 1359 does not have enough neighbors. Skipping...
Chunk 1405 does not have enough neighbors. Skipping...
Chunk 1562 does not have enough neighbors. Skipping...
Chunk 1586 does not have enough neighbors. Skipping...
Chunk 1605 does not have enough neighbors. Skipping...
Chunk 1684 does not have enough neighbors. Skipping...
Chunk 1704 does not have enough neighbors. Skipping...
Chunk 1762 does not have enough neighbors. Skipping...
Chunk 1843 does not have enough neighbors. Skipping...
Chunk 1980 does not have enough neighbors. Skipping...
Chunk 2105 does not have enough neighbors. Skipping...
Chunk 2112 does not have enough neighbors. Skipping...
Chunk 2190 does not have enough neighbors. Skipping...
Chunk 2281 does not have enough neighbors. Skipping...
Chunk 2325 does not have enough neighbors. Skipping...
Chunk 2370 does not have enough neighbors. Skipping...
Chunk 2432 does not have enough neighbors. Skipping...
Chunk 2461 does not have enough neighbors. Skipping...
Chunk 2927 does not have enough neighbors. Skipping...
Chunk 2963 does not have enough neighbors. Skipping...
Chunk 3004 does not have enough neighbors. Skipping...
Chunk 3162 does not have enough neighbors. Skipping...
Chunk 3244 does not have enough neighbors. Skipping...
Chunk 3466 does not have enough neighbors. Skipping...
Chunk 3479 does not have enough neighbors. Skipping...
Chunk 3481 does not have enough neighbors. Skipping...
Chunk 3647 does not have enough neighbors. Skipping...
Chunk 3661 does not have enough neighbors. Skipping...
Chunk 3693 does not have enough neighbors. Skipping...
Chunk 3808 does not have enough neighbors. Skipping...
Chunk 3988 does not have enough neighbors. Skipping...
Chunk 4146 does not have enough neighbors. Skipping...
Chunk 4181 does not have enough neighbors. Skipping...
Chunk 4201 does not have enough neighbors. Skipping...
Chunk 4262 does not have enough neighbors. Skipping...
Chunk 4324 does not have enough neighbors. Skipping...
Chunk 4521 does not have enough neighbors. Skipping...
Chunk 4680 does not have enough neighbors. Skipping...
Chunk 4687 does not have enough neighbors. Skipping...
Chunk 4807 does not have enough neighbors. Skipping...
Chunk 4954 does not have enough neighbors. Skipping...
Chunk 5274 does not have enough neighbors. Skipping...
Chunk 5347 does not have enough neighbors. Skipping...
Chunk 5375 does not have enough neighbors. Skipping...
Chunk 5429 does not have enough neighbors. Skipping...
Chunk 5449 does not have enough neighbors. Skipping...
Chunk 5606 does not have enough neighbors. Skipping...
Chunk 5800 does not have enough neighbors. Skipping...
Chunk 5891 does not have enough neighbors. Skipping...
Chunk 6063 does not have enough neighbors. Skipping...
Chunk 6207 does not have enough neighbors. Skipping...
Chunk 6336 does not have enough neighbors. Skipping...
Chunk 6419 does not have enough neighbors. Skipping...
Chunk 6465 does not have enough neighbors. Skipping...
Chunk 6500 does not have enough neighbors. Skipping...
Chunk 6509 does not have enough neighbors. Skipping...
Chunk 6564 does not have enough neighbors. Skipping...
Chunk 6700 does not have enough neighbors. Skipping...
Chunk 6750 does not have enough neighbors. Skipping...
Chunk 6866 does not have enough neighbors. Skipping...
Chunk 6893 does not have enough neighbors. Skipping...
Chunk 7058 does not have enough neighbors. Skipping...
Chunk 7080 does not have enough neighbors. Skipping...
7_zenodo6368128/PBMC

AnnData object with n_obs × n_vars = 7108 × 3052
    obs: 'group', 'cell_type', 'Garfield_cluster', 'Multigrate_cluster', 'TotalVI_cluster', 'scArches_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'TotalVI', 'TotalVI_cluster', 'scArches', 'scArches_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'TotalVI', 'scArches', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'TotalVI_distances', 'TotalVI_connectivities', 'scArches_distances', 'scArches_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [37]:
method_list = ['Garfield', 'Multigrate', 'TotalVI', 'scArches', 'Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_Protein'
dataset = '7_zenodo6368128/PBMC'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

        ARI       NMI     cLISI      cASW       model               dataset
0  0.674712  0.720589  0.972405  0.588073    Garfield  7_zenodo6368128/PBMC
1  0.415778  0.617059  0.940645  0.533962  Multigrate  7_zenodo6368128/PBMC
2  0.467543  0.668589  0.926176  0.523700     TotalVI  7_zenodo6368128/PBMC
3  0.435581  0.591365  0.944616  0.522045    scArches  7_zenodo6368128/PBMC
4  0.422766  0.667751  0.984696  0.630589      Seurat  7_zenodo6368128/PBMC

### 数据集 12_GSE193181/P5

In [6]:
## 记录resolution
reso_dict = {
    '12_GSE193181/P5': {
        'Garfield': 0.70,
        'Multigrate': 0.83,
        'TotalVI': 0.6,
        'scArches': 0.58,
        'Seurat': 0.07, 
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('12_GSE193181/P5', reso_dict=reso_dict)
adata

the length of cell type: 15
method_reso is not None, using the 0.7 as resolution for Garfield...
Number of clusters: 15
the length of cell type: 15
method_reso is not None, using the 0.83 as resolution for Multigrate...
Number of clusters: 15
the length of cell type: 15
method_reso is not None, using the 0.6 as resolution for TotalVI...
Number of clusters: 15
the length of cell type: 15
method_reso is not None, using the 0.58 as resolution for scArches...
Number of clusters: 15
the length of cell type: 15
method_reso is not None, using the 0.07 as resolution for Seurat...
Number of clusters: 16
12_GSE193181/P5

AnnData object with n_obs × n_vars = 78530 × 3021
    obs: 'group', 'cell_type', 'Garfield_cluster', 'Multigrate_cluster', 'TotalVI_cluster', 'scArches_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'TotalVI', 'TotalVI_cluster', 'scArches', 'scArches_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'TotalVI', 'scArches', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'TotalVI_distances', 'TotalVI_connectivities', 'scArches_distances', 'scArches_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [7]:
import matplotlib.pyplot as plt

dataset = '12_GSE193181/P5'
res_dir = f'/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_Protein/{dataset}'

latent_key_list = ['Garfield', 'Multigrate', 'TotalVI', 'scArches', 'Seurat']
for latent_key in latent_key_list:
    sc.tl.umap(adata, neighbors_key=latent_key)
    latent_key_cluster = latent_key + '_cluster'
    
    # Create a new figure for each plot with an appropriate size
    plt.figure(figsize=(12, 6))  # Adjust the figsize as needed
    sc.pl.umap(adata, color=['cell_type', latent_key_cluster], wspace=0.5, hspace=0.5, show=False, ncols=2)
    # Save the figure
    plt.savefig(res_dir + f"/{latent_key}_UMAP_clusters.png", bbox_inches='tight')  # Use bbox_inches to ensure full legend display
    plt.close()

In [9]:
method_list = ['Garfield', 'Multigrate', 'TotalVI', 'scArches', 'Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_Protein'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

        ARI       NMI     cLISI      cASW       model          dataset
0  0.283427  0.384462  0.898730  0.501129    Garfield  12_GSE193181/P5
1  0.112307  0.246496  0.838104  0.494953  Multigrate  12_GSE193181/P5
2  0.092961  0.213891  0.878303  0.505427     TotalVI  12_GSE193181/P5
3  0.117282  0.240685  0.864057  0.503540    scArches  12_GSE193181/P5
4  0.195190  0.356681  0.892815  0.458184      Seurat  12_GSE193181/P5

#### 探索一下用最佳分辨率

In [34]:
# calculate the metrics based on the best resolution
adata = count_metrics_for_best_resolution('12_GSE193181/P5')
adata

resolution: 0.1, nmi: 0.7045669196987505
resolution: 0.2, nmi: 0.7040936405475081
resolution: 0.3, nmi: 0.7205885851480783
resolution: 0.4, nmi: 0.7104931369492323
resolution: 0.5, nmi: 0.6709402505709019
resolution: 0.6, nmi: 0.6713295133715153
resolution: 0.7, nmi: 0.6540703032203694
resolution: 0.8, nmi: 0.6470365429842112
resolution: 0.9, nmi: 0.6420635132291619
resolution: 1.0, nmi: 0.6362029863885618
resolution: 1.1, nmi: 0.6342888505636097
resolution: 1.2, nmi: 0.6154469403548659
resolution: 1.3, nmi: 0.5982622762585442
resolution: 1.4, nmi: 0.6105697546713903
resolution: 1.5, nmi: 0.6029148420014858
resolution: 1.6, nmi: 0.6061772811323619
resolution: 1.7, nmi: 0.6005563366163184
resolution: 1.8, nmi: 0.5933744985630317
resolution: 1.9, nmi: 0.6025190440512225
resolution: 2.0, nmi: 0.5936765348885282
optimised clustering against cell_type
optimal cluster resolution: 0.3
optimal score: 0.7205885851480783
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.6509998007150417
resolution: 0.2, nmi: 0.6680341874881333
resolution: 0.3, nmi: 0.6903352440930147
resolution: 0.4, nmi: 0.6750921654730228
resolution: 0.5, nmi: 0.6656897820881211
resolution: 0.6, nmi: 0.6332018485100825
resolution: 0.7, nmi: 0.6335364774644534
resolution: 0.8, nmi: 0.6211602792786339
resolution: 0.9, nmi: 0.6278959309516254
resolution: 1.0, nmi: 0.6353512316582143
resolution: 1.1, nmi: 0.6039082585543925
resolution: 1.2, nmi: 0.6002896025989156
resolution: 1.3, nmi: 0.600382307374798
resolution: 1.4, nmi: 0.6035551188363293
resolution: 1.5, nmi: 0.5868121464365366
resolution: 1.6, nmi: 0.5877349028661761
resolution: 1.7, nmi: 0.5771692517085043
resolution: 1.8, nmi: 0.5696833053691898
resolution: 1.9, nmi: 0.5637180797381226
resolution: 2.0, nmi: 0.5538245096352187
optimised clustering against cell_type
optimal cluster resolution: 0.3
optimal score: 0.6903352440930147
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.6113007894031095
resolution: 0.2, nmi: 0.6451532623287438
resolution: 0.3, nmi: 0.7109841940431639
resolution: 0.4, nmi: 0.7187172144428811
resolution: 0.5, nmi: 0.7093670662439145
resolution: 0.6, nmi: 0.7078738396742833
resolution: 0.7, nmi: 0.7095169193980786
resolution: 0.8, nmi: 0.7076706167842152
resolution: 0.9, nmi: 0.6402773671251597
resolution: 1.0, nmi: 0.6310302138288231
resolution: 1.1, nmi: 0.6136513414688339
resolution: 1.2, nmi: 0.6042497916170314
resolution: 1.3, nmi: 0.6066114561940221
resolution: 1.4, nmi: 0.597167151086739
resolution: 1.5, nmi: 0.5929563247279287
resolution: 1.6, nmi: 0.59835556442898
resolution: 1.7, nmi: 0.5926245603416728
resolution: 1.8, nmi: 0.5846254024359707
resolution: 1.9, nmi: 0.5887190897083212
resolution: 2.0, nmi: 0.5693782101787028
optimised clustering against cell_type
optimal cluster resolution: 0.4
optimal score: 0.7187172144428811
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.6595345207739932
resolution: 0.2, nmi: 0.658367933085881
resolution: 0.3, nmi: 0.6666619423895904
resolution: 0.4, nmi: 0.6127174405796693
resolution: 0.5, nmi: 0.5913645099153103
resolution: 0.6, nmi: 0.5817588915330362
resolution: 0.7, nmi: 0.5584212417816515
resolution: 0.8, nmi: 0.5635554130154014
resolution: 0.9, nmi: 0.562494010883967
resolution: 1.0, nmi: 0.5587223932444847
resolution: 1.1, nmi: 0.5539351573790297
resolution: 1.2, nmi: 0.5553107579217383
resolution: 1.3, nmi: 0.5519084394367573
resolution: 1.4, nmi: 0.5510871999917389
resolution: 1.5, nmi: 0.5404009061471442
resolution: 1.6, nmi: 0.5351945326320834
resolution: 1.7, nmi: 0.5243340242815794
resolution: 1.8, nmi: 0.5267683838648809
resolution: 1.9, nmi: 0.5225940294485063
resolution: 2.0, nmi: 0.5234016978514117
optimised clustering against cell_type
optimal cluster resolution: 0.3
optimal score: 0.6666619423895904
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.6712509481888517
resolution: 0.2, nmi: 0.6355728067157008
resolution: 0.3, nmi: 0.6163326084709259
resolution: 0.4, nmi: 0.5998202314761332
resolution: 0.5, nmi: 0.585013918222391
resolution: 0.6, nmi: 0.5762046879785717
resolution: 0.7, nmi: 0.5639936056934722
resolution: 0.8, nmi: 0.5567538248705509
resolution: 0.9, nmi: 0.5597515803586316
resolution: 1.0, nmi: 0.5489981588663322
resolution: 1.1, nmi: 0.5467669009164263
resolution: 1.2, nmi: 0.538928350378125
resolution: 1.3, nmi: 0.5374506781392207
resolution: 1.4, nmi: 0.5331702746720304
resolution: 1.5, nmi: 0.5300268082914099
resolution: 1.6, nmi: 0.5248248227665457
resolution: 1.7, nmi: 0.5251837138170596
resolution: 1.8, nmi: 0.5210487067298321
resolution: 1.9, nmi: 0.5189910013027261
resolution: 2.0, nmi: 0.5186796105033173
optimised clustering against cell_type
optimal cluster resolution: 0.1
optimal score: 0.6712509481888517
Chunk 178 does not have enough neighbors. Skipping...
Chunk 245 does not have enough neighbors. Skipping...
Chunk 405 does not have enough neighbors. Skipping...
Chunk 550 does not have enough neighbors. Skipping...
Chunk 563 does not have enough neighbors. Skipping...
Chunk 573 does not have enough neighbors. Skipping...
Chunk 873 does not have enough neighbors. Skipping...
Chunk 925 does not have enough neighbors. Skipping...
Chunk 966 does not have enough neighbors. Skipping...
Chunk 1047 does not have enough neighbors. Skipping...
Chunk 1164 does not have enough neighbors. Skipping...
Chunk 1173 does not have enough neighbors. Skipping...
Chunk 1182 does not have enough neighbors. Skipping...
Chunk 1230 does not have enough neighbors. Skipping...
Chunk 1296 does not have enough neighbors. Skipping...
Chunk 1359 does not have enough neighbors. Skipping...
Chunk 1405 does not have enough neighbors. Skipping...
Chunk 1562 does not have enough neighbors. Skipping...
Chunk 1586 does not have enough neighbors. Skipping...
Chunk 1605 does not have enough neighbors. Skipping...
Chunk 1684 does not have enough neighbors. Skipping...
Chunk 1704 does not have enough neighbors. Skipping...
Chunk 1762 does not have enough neighbors. Skipping...
Chunk 1843 does not have enough neighbors. Skipping...
Chunk 1980 does not have enough neighbors. Skipping...
Chunk 2105 does not have enough neighbors. Skipping...
Chunk 2112 does not have enough neighbors. Skipping...
Chunk 2190 does not have enough neighbors. Skipping...
Chunk 2281 does not have enough neighbors. Skipping...
Chunk 2325 does not have enough neighbors. Skipping...
Chunk 2370 does not have enough neighbors. Skipping...
Chunk 2432 does not have enough neighbors. Skipping...
Chunk 2461 does not have enough neighbors. Skipping...
Chunk 2927 does not have enough neighbors. Skipping...
Chunk 2963 does not have enough neighbors. Skipping...
Chunk 3004 does not have enough neighbors. Skipping...
Chunk 3162 does not have enough neighbors. Skipping...
Chunk 3244 does not have enough neighbors. Skipping...
Chunk 3466 does not have enough neighbors. Skipping...
Chunk 3479 does not have enough neighbors. Skipping...
Chunk 3481 does not have enough neighbors. Skipping...
Chunk 3647 does not have enough neighbors. Skipping...
Chunk 3661 does not have enough neighbors. Skipping...
Chunk 3693 does not have enough neighbors. Skipping...
Chunk 3808 does not have enough neighbors. Skipping...
Chunk 3988 does not have enough neighbors. Skipping...
Chunk 4146 does not have enough neighbors. Skipping...
Chunk 4181 does not have enough neighbors. Skipping...
Chunk 4201 does not have enough neighbors. Skipping...
Chunk 4262 does not have enough neighbors. Skipping...
Chunk 4324 does not have enough neighbors. Skipping...
Chunk 4521 does not have enough neighbors. Skipping...
Chunk 4680 does not have enough neighbors. Skipping...
Chunk 4687 does not have enough neighbors. Skipping...
Chunk 4807 does not have enough neighbors. Skipping...
Chunk 4954 does not have enough neighbors. Skipping...
Chunk 5274 does not have enough neighbors. Skipping...
Chunk 5347 does not have enough neighbors. Skipping...
Chunk 5375 does not have enough neighbors. Skipping...
Chunk 5429 does not have enough neighbors. Skipping...
Chunk 5449 does not have enough neighbors. Skipping...
Chunk 5606 does not have enough neighbors. Skipping...
Chunk 5800 does not have enough neighbors. Skipping...
Chunk 5891 does not have enough neighbors. Skipping...
Chunk 6063 does not have enough neighbors. Skipping...
Chunk 6207 does not have enough neighbors. Skipping...
Chunk 6336 does not have enough neighbors. Skipping...
Chunk 6419 does not have enough neighbors. Skipping...
Chunk 6465 does not have enough neighbors. Skipping...
Chunk 6500 does not have enough neighbors. Skipping...
Chunk 6509 does not have enough neighbors. Skipping...
Chunk 6564 does not have enough neighbors. Skipping...
Chunk 6700 does not have enough neighbors. Skipping...
Chunk 6750 does not have enough neighbors. Skipping...
Chunk 6866 does not have enough neighbors. Skipping...
Chunk 6893 does not have enough neighbors. Skipping...
Chunk 7058 does not have enough neighbors. Skipping...
Chunk 7080 does not have enough neighbors. Skipping...
7_zenodo6368128/PBMC

AnnData object with n_obs × n_vars = 7108 × 3052
    obs: 'group', 'cell_type', 'batch', 'cluster'
    var: 'modality'
    uns: 'modality_lengths', 'neighbors', 'umap', 'cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'TotalVI', 'scArches', 'Seurat'
    layers: 'counts'
    obsp: 'distances', 'connectivities'

In [10]:
method_list = ['Garfield', 'Multigrate', 'TotalVI', 'scArches', 'Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_Protein'
dataset = '12_GSE193181/P5'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result_best_reso.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

FileNotFoundError: [Errno 2] No such file or directory: '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_Protein/12_GSE193181/P5_metrics_result_best_reso.csv'

#### 利用最佳分辨率计算指标(Garfield);

In [36]:
## 记录resolution
reso_dict = {
    '12_GSE193181/P5': {
        'Garfield': 0.70,
        'Multigrate': 0.83,
        'TotalVI': 0.6,
        'scArches': 0.58,
        'Seurat': 0.065, 
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('12_GSE193181/P5', reso_dict=reso_dict)
adata

the length of cell type: 11
method_reso is not None, using the 0.3 as resolution for Garfield...
Number of clusters: 8
the length of cell type: 11
method_reso is not None, using the 0.8500000000000003 as resolution for Multigrate...
Number of clusters: 11
the length of cell type: 11
method_reso is not None, using the 0.84 as resolution for TotalVI...
Number of clusters: 11
the length of cell type: 11
method_reso is not None, using the 0.5 as resolution for scArches...
Number of clusters: 11
the length of cell type: 11
method_reso is not None, using the 0.098 as resolution for Seurat...
Number of clusters: 11
Chunk 178 does not have enough neighbors. Skipping...
Chunk 245 does not have enough neighbors. Skipping...
Chunk 405 does not have enough neighbors. Skipping...
Chunk 550 does not have enough neighbors. Skipping...
Chunk 563 does not have enough neighbors. Skipping...
Chunk 573 does not have enough neighbors. Skipping...
Chunk 873 does not have enough neighbors. Skipping...
Chunk 925 does not have enough neighbors. Skipping...
Chunk 966 does not have enough neighbors. Skipping...
Chunk 1047 does not have enough neighbors. Skipping...
Chunk 1164 does not have enough neighbors. Skipping...
Chunk 1173 does not have enough neighbors. Skipping...
Chunk 1182 does not have enough neighbors. Skipping...
Chunk 1230 does not have enough neighbors. Skipping...
Chunk 1296 does not have enough neighbors. Skipping...
Chunk 1359 does not have enough neighbors. Skipping...
Chunk 1405 does not have enough neighbors. Skipping...
Chunk 1562 does not have enough neighbors. Skipping...
Chunk 1586 does not have enough neighbors. Skipping...
Chunk 1605 does not have enough neighbors. Skipping...
Chunk 1684 does not have enough neighbors. Skipping...
Chunk 1704 does not have enough neighbors. Skipping...
Chunk 1762 does not have enough neighbors. Skipping...
Chunk 1843 does not have enough neighbors. Skipping...
Chunk 1980 does not have enough neighbors. Skipping...
Chunk 2105 does not have enough neighbors. Skipping...
Chunk 2112 does not have enough neighbors. Skipping...
Chunk 2190 does not have enough neighbors. Skipping...
Chunk 2281 does not have enough neighbors. Skipping...
Chunk 2325 does not have enough neighbors. Skipping...
Chunk 2370 does not have enough neighbors. Skipping...
Chunk 2432 does not have enough neighbors. Skipping...
Chunk 2461 does not have enough neighbors. Skipping...
Chunk 2927 does not have enough neighbors. Skipping...
Chunk 2963 does not have enough neighbors. Skipping...
Chunk 3004 does not have enough neighbors. Skipping...
Chunk 3162 does not have enough neighbors. Skipping...
Chunk 3244 does not have enough neighbors. Skipping...
Chunk 3466 does not have enough neighbors. Skipping...
Chunk 3479 does not have enough neighbors. Skipping...
Chunk 3481 does not have enough neighbors. Skipping...
Chunk 3647 does not have enough neighbors. Skipping...
Chunk 3661 does not have enough neighbors. Skipping...
Chunk 3693 does not have enough neighbors. Skipping...
Chunk 3808 does not have enough neighbors. Skipping...
Chunk 3988 does not have enough neighbors. Skipping...
Chunk 4146 does not have enough neighbors. Skipping...
Chunk 4181 does not have enough neighbors. Skipping...
Chunk 4201 does not have enough neighbors. Skipping...
Chunk 4262 does not have enough neighbors. Skipping...
Chunk 4324 does not have enough neighbors. Skipping...
Chunk 4521 does not have enough neighbors. Skipping...
Chunk 4680 does not have enough neighbors. Skipping...
Chunk 4687 does not have enough neighbors. Skipping...
Chunk 4807 does not have enough neighbors. Skipping...
Chunk 4954 does not have enough neighbors. Skipping...
Chunk 5274 does not have enough neighbors. Skipping...
Chunk 5347 does not have enough neighbors. Skipping...
Chunk 5375 does not have enough neighbors. Skipping...
Chunk 5429 does not have enough neighbors. Skipping...
Chunk 5449 does not have enough neighbors. Skipping...
Chunk 5606 does not have enough neighbors. Skipping...
Chunk 5800 does not have enough neighbors. Skipping...
Chunk 5891 does not have enough neighbors. Skipping...
Chunk 6063 does not have enough neighbors. Skipping...
Chunk 6207 does not have enough neighbors. Skipping...
Chunk 6336 does not have enough neighbors. Skipping...
Chunk 6419 does not have enough neighbors. Skipping...
Chunk 6465 does not have enough neighbors. Skipping...
Chunk 6500 does not have enough neighbors. Skipping...
Chunk 6509 does not have enough neighbors. Skipping...
Chunk 6564 does not have enough neighbors. Skipping...
Chunk 6700 does not have enough neighbors. Skipping...
Chunk 6750 does not have enough neighbors. Skipping...
Chunk 6866 does not have enough neighbors. Skipping...
Chunk 6893 does not have enough neighbors. Skipping...
Chunk 7058 does not have enough neighbors. Skipping...
Chunk 7080 does not have enough neighbors. Skipping...
7_zenodo6368128/PBMC

AnnData object with n_obs × n_vars = 7108 × 3052
    obs: 'group', 'cell_type', 'Garfield_cluster', 'Multigrate_cluster', 'TotalVI_cluster', 'scArches_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'TotalVI', 'TotalVI_cluster', 'scArches', 'scArches_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'TotalVI', 'scArches', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'TotalVI_distances', 'TotalVI_connectivities', 'scArches_distances', 'scArches_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [37]:
method_list = ['Garfield', 'Multigrate', 'TotalVI', 'scArches', 'Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_Protein'
dataset = '12_GSE193181/P5'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

        ARI       NMI     cLISI      cASW       model               dataset
0  0.674712  0.720589  0.972405  0.588073    Garfield  7_zenodo6368128/PBMC
1  0.415778  0.617059  0.940645  0.533962  Multigrate  7_zenodo6368128/PBMC
2  0.467543  0.668589  0.926176  0.523700     TotalVI  7_zenodo6368128/PBMC
3  0.435581  0.591365  0.944616  0.522045    scArches  7_zenodo6368128/PBMC
4  0.422766  0.667751  0.984696  0.630589      Seurat  7_zenodo6368128/PBMC

### 数据集 12_GSE193181/P8

In [7]:
## 记录resolution
reso_dict = {
    '12_GSE193181/P8': {
        'Garfield': 0.38,
        'Multigrate': 0.6500000000000001,
        'TotalVI': 0.23914845000000007,
        'scArches': 0.2657205000000001,
        'Seurat': 0.05470949456575622, 
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('12_GSE193181/P8', reso_dict=reso_dict)
adata

the length of cell type: 10
method_reso is not None, using the 0.38 as resolution for Garfield...
Number of clusters: 10
the length of cell type: 10
Searching resolution for Multigrate...
Searching resolution...
resolution=1.9500000000000013, cluster number=28
resolution=1.9000000000000012, cluster number=28
resolution=1.8500000000000012, cluster number=27
resolution=1.8000000000000012, cluster number=26
resolution=1.750000000000001, cluster number=25
resolution=1.700000000000001, cluster number=25
resolution=1.650000000000001, cluster number=24
resolution=1.600000000000001, cluster number=22
resolution=1.550000000000001, cluster number=21
resolution=1.5000000000000009, cluster number=21
resolution=1.4500000000000008, cluster number=21
resolution=1.4000000000000008, cluster number=20
resolution=1.3500000000000008, cluster number=19
resolution=1.3000000000000007, cluster number=19
resolution=1.2500000000000007, cluster number=17
resolution=1.2000000000000006, cluster number=17
resolution=1.1500000000000006, cluster number=16
resolution=1.1000000000000005, cluster number=16
resolution=1.0500000000000005, cluster number=15
resolution=1.0000000000000004, cluster number=14
resolution=0.9500000000000004, cluster number=15
resolution=0.9000000000000004, cluster number=15
resolution=0.8500000000000003, cluster number=13
resolution=0.8000000000000003, cluster number=13
resolution=0.7500000000000002, cluster number=11
resolution=0.7000000000000002, cluster number=12
resolution=0.6500000000000001, cluster number=10
Number of clusters: 10
the length of cell type: 10
Searching resolution for TotalVI...
Searching resolution...
resolution=1.9500000000000013, cluster number=25
resolution=1.9000000000000012, cluster number=25
resolution=1.8500000000000012, cluster number=26
resolution=1.8000000000000012, cluster number=24
resolution=1.750000000000001, cluster number=24
resolution=1.700000000000001, cluster number=24
resolution=1.650000000000001, cluster number=25
resolution=1.600000000000001, cluster number=23
resolution=1.550000000000001, cluster number=23
resolution=1.5000000000000009, cluster number=23
resolution=1.4500000000000008, cluster number=23
resolution=1.4000000000000008, cluster number=23
resolution=1.3500000000000008, cluster number=22
resolution=1.3000000000000007, cluster number=22
resolution=1.2500000000000007, cluster number=22
resolution=1.2000000000000006, cluster number=22
resolution=1.1500000000000006, cluster number=21
resolution=1.1000000000000005, cluster number=21
resolution=1.0500000000000005, cluster number=21
resolution=1.0000000000000004, cluster number=21
resolution=0.9500000000000004, cluster number=19
resolution=0.9000000000000004, cluster number=19
resolution=0.8500000000000003, cluster number=19
resolution=0.8000000000000003, cluster number=18
resolution=0.7500000000000002, cluster number=18
resolution=0.7000000000000002, cluster number=18
resolution=0.6500000000000001, cluster number=18
resolution=0.6000000000000001, cluster number=18
resolution=0.55, cluster number=17
resolution=0.5, cluster number=17
Expanding search range: new range (0.45, 0.7875)
resolution=0.75, cluster number=18
resolution=0.7, cluster number=18
resolution=0.6499999999999999, cluster number=18
resolution=0.6, cluster number=18
resolution=0.55, cluster number=17
resolution=0.5, cluster number=17
resolution=0.45, cluster number=14
Expanding search range: new range (0.405, 0.70875)
resolution=0.705, cluster number=18
resolution=0.655, cluster number=18
resolution=0.605, cluster number=18
resolution=0.5549999999999999, cluster number=17
resolution=0.505, cluster number=17
resolution=0.455, cluster number=15
resolution=0.405, cluster number=14
Expanding search range: new range (0.36450000000000005, 0.6378750000000001)
resolution=0.6145, cluster number=18
resolution=0.5645, cluster number=18
resolution=0.5145, cluster number=17
resolution=0.4645, cluster number=16
resolution=0.41450000000000004, cluster number=15
resolution=0.36450000000000005, cluster number=12
Expanding search range: new range (0.32805000000000006, 0.5740875000000001)
resolution=0.52805, cluster number=18
resolution=0.47805000000000003, cluster number=17
resolution=0.42805000000000004, cluster number=13
resolution=0.37805000000000005, cluster number=11
resolution=0.32805000000000006, cluster number=11
Expanding search range: new range (0.2952450000000001, 0.5166787500000002)
resolution=0.49524500000000005, cluster number=14
resolution=0.44524500000000006, cluster number=15
resolution=0.39524500000000007, cluster number=14
resolution=0.3452450000000001, cluster number=11
resolution=0.2952450000000001, cluster number=11
Expanding search range: new range (0.2657205000000001, 0.46501087500000016)
resolution=0.41572050000000005, cluster number=14
resolution=0.36572050000000006, cluster number=12
resolution=0.31572050000000007, cluster number=11
resolution=0.2657205000000001, cluster number=11
Expanding search range: new range (0.23914845000000007, 0.4185097875000001)
resolution=0.38914845000000003, cluster number=13
resolution=0.33914845000000005, cluster number=11
resolution=0.28914845000000006, cluster number=11
resolution=0.23914845000000007, cluster number=10
Number of clusters: 10
the length of cell type: 10
Searching resolution for scArches...
Searching resolution...
resolution=1.9500000000000013, cluster number=31
resolution=1.9000000000000012, cluster number=30
resolution=1.8500000000000012, cluster number=30
resolution=1.8000000000000012, cluster number=30
resolution=1.750000000000001, cluster number=27
resolution=1.700000000000001, cluster number=29
resolution=1.650000000000001, cluster number=27
resolution=1.600000000000001, cluster number=26
resolution=1.550000000000001, cluster number=25
resolution=1.5000000000000009, cluster number=26
resolution=1.4500000000000008, cluster number=24
resolution=1.4000000000000008, cluster number=24
resolution=1.3500000000000008, cluster number=23
resolution=1.3000000000000007, cluster number=22
resolution=1.2500000000000007, cluster number=23
resolution=1.2000000000000006, cluster number=23
resolution=1.1500000000000006, cluster number=22
resolution=1.1000000000000005, cluster number=21
resolution=1.0500000000000005, cluster number=22
resolution=1.0000000000000004, cluster number=20
resolution=0.9500000000000004, cluster number=18
resolution=0.9000000000000004, cluster number=18
resolution=0.8500000000000003, cluster number=18
resolution=0.8000000000000003, cluster number=17
resolution=0.7500000000000002, cluster number=16
resolution=0.7000000000000002, cluster number=16
resolution=0.6500000000000001, cluster number=15
resolution=0.6000000000000001, cluster number=14
resolution=0.55, cluster number=14
resolution=0.5, cluster number=14
Expanding search range: new range (0.45, 0.7875)
resolution=0.75, cluster number=16
resolution=0.7, cluster number=16
resolution=0.6499999999999999, cluster number=15
resolution=0.6, cluster number=14
resolution=0.55, cluster number=14
resolution=0.5, cluster number=14
resolution=0.45, cluster number=13
Expanding search range: new range (0.405, 0.70875)
resolution=0.705, cluster number=15
resolution=0.655, cluster number=16
resolution=0.605, cluster number=15
resolution=0.5549999999999999, cluster number=14
resolution=0.505, cluster number=14
resolution=0.455, cluster number=13
resolution=0.405, cluster number=12
Expanding search range: new range (0.36450000000000005, 0.6378750000000001)
resolution=0.6145, cluster number=14
resolution=0.5645, cluster number=14
resolution=0.5145, cluster number=14
resolution=0.4645, cluster number=13
resolution=0.41450000000000004, cluster number=13
resolution=0.36450000000000005, cluster number=12
Expanding search range: new range (0.32805000000000006, 0.5740875000000001)
resolution=0.52805, cluster number=14
resolution=0.47805000000000003, cluster number=13
resolution=0.42805000000000004, cluster number=12
resolution=0.37805000000000005, cluster number=12
resolution=0.32805000000000006, cluster number=12
Expanding search range: new range (0.2952450000000001, 0.5166787500000002)
resolution=0.49524500000000005, cluster number=14
resolution=0.44524500000000006, cluster number=13
resolution=0.39524500000000007, cluster number=12
resolution=0.3452450000000001, cluster number=12
resolution=0.2952450000000001, cluster number=12
Expanding search range: new range (0.2657205000000001, 0.46501087500000016)
resolution=0.41572050000000005, cluster number=13
resolution=0.36572050000000006, cluster number=12
resolution=0.31572050000000007, cluster number=12
resolution=0.2657205000000001, cluster number=10
Number of clusters: 10
the length of cell type: 10
Searching resolution for Seurat...
Searching resolution...
resolution=1.9500000000000013, cluster number=91
resolution=1.9000000000000012, cluster number=90
resolution=1.8500000000000012, cluster number=92
resolution=1.8000000000000012, cluster number=89
resolution=1.750000000000001, cluster number=88
resolution=1.700000000000001, cluster number=89
resolution=1.650000000000001, cluster number=84
resolution=1.600000000000001, cluster number=83
resolution=1.550000000000001, cluster number=81
resolution=1.5000000000000009, cluster number=75
resolution=1.4500000000000008, cluster number=73
resolution=1.4000000000000008, cluster number=75
resolution=1.3500000000000008, cluster number=74
resolution=1.3000000000000007, cluster number=69
resolution=1.2500000000000007, cluster number=68
resolution=1.2000000000000006, cluster number=68
resolution=1.1500000000000006, cluster number=66
resolution=1.1000000000000005, cluster number=66
resolution=1.0500000000000005, cluster number=66
resolution=1.0000000000000004, cluster number=62
resolution=0.9500000000000004, cluster number=60
resolution=0.9000000000000004, cluster number=57
resolution=0.8500000000000003, cluster number=50
resolution=0.8000000000000003, cluster number=49
resolution=0.7500000000000002, cluster number=46
resolution=0.7000000000000002, cluster number=46
resolution=0.6500000000000001, cluster number=45
resolution=0.6000000000000001, cluster number=40
resolution=0.55, cluster number=39
resolution=0.5, cluster number=37
Expanding search range: new range (0.45, 0.7875)
resolution=0.75, cluster number=46
resolution=0.7, cluster number=46
resolution=0.6499999999999999, cluster number=45
resolution=0.6, cluster number=40
resolution=0.55, cluster number=39
resolution=0.5, cluster number=37
resolution=0.45, cluster number=35
Expanding search range: new range (0.405, 0.70875)
resolution=0.705, cluster number=47
resolution=0.655, cluster number=47
resolution=0.605, cluster number=40
resolution=0.5549999999999999, cluster number=40
resolution=0.505, cluster number=35
resolution=0.455, cluster number=34
resolution=0.405, cluster number=33
Expanding search range: new range (0.36450000000000005, 0.6378750000000001)
resolution=0.6145, cluster number=42
resolution=0.5645, cluster number=39
resolution=0.5145, cluster number=36
resolution=0.4645, cluster number=35
resolution=0.41450000000000004, cluster number=33
resolution=0.36450000000000005, cluster number=29
Expanding search range: new range (0.32805000000000006, 0.5740875000000001)
resolution=0.52805, cluster number=39
resolution=0.47805000000000003, cluster number=34
resolution=0.42805000000000004, cluster number=33
resolution=0.37805000000000005, cluster number=30
resolution=0.32805000000000006, cluster number=29
Expanding search range: new range (0.2952450000000001, 0.5166787500000002)
resolution=0.49524500000000005, cluster number=36
resolution=0.44524500000000006, cluster number=34
resolution=0.39524500000000007, cluster number=33
resolution=0.3452450000000001, cluster number=29
resolution=0.2952450000000001, cluster number=25
Expanding search range: new range (0.2657205000000001, 0.46501087500000016)
resolution=0.41572050000000005, cluster number=33
resolution=0.36572050000000006, cluster number=32
resolution=0.31572050000000007, cluster number=27
resolution=0.2657205000000001, cluster number=24
Expanding search range: new range (0.23914845000000007, 0.4185097875000001)
resolution=0.38914845000000003, cluster number=33
resolution=0.33914845000000005, cluster number=29
resolution=0.28914845000000006, cluster number=28
resolution=0.23914845000000007, cluster number=24
Expanding search range: new range (0.21523360500000008, 0.37665880875000013)
resolution=0.3652336050000001, cluster number=31
resolution=0.3152336050000001, cluster number=27
resolution=0.2652336050000001, cluster number=24
resolution=0.21523360500000008, cluster number=22
Expanding search range: new range (0.19371024450000007, 0.3389929278750001)
resolution=0.29371024450000005, cluster number=25
resolution=0.24371024450000006, cluster number=24
resolution=0.19371024450000007, cluster number=21
Expanding search range: new range (0.17433922005000008, 0.30509363508750015)
resolution=0.27433922005000005, cluster number=26
resolution=0.22433922005000007, cluster number=22
resolution=0.17433922005000008, cluster number=20
Expanding search range: new range (0.15690529804500009, 0.27458427157875015)
resolution=0.25690529804500006, cluster number=24
resolution=0.20690529804500007, cluster number=22
resolution=0.15690529804500009, cluster number=20
Expanding search range: new range (0.14121476824050008, 0.24712584442087515)
resolution=0.24121476824050012, cluster number=24
resolution=0.1912147682405001, cluster number=21
resolution=0.14121476824050008, cluster number=20
Expanding search range: new range (0.12709329141645007, 0.2224132599787876)
resolution=0.17709329141645008, cluster number=20
resolution=0.12709329141645007, cluster number=19
Expanding search range: new range (0.11438396227480506, 0.20017193398090885)
resolution=0.16438396227480506, cluster number=19
resolution=0.11438396227480506, cluster number=17
Expanding search range: new range (0.10294556604732455, 0.18015474058281797)
resolution=0.15294556604732457, cluster number=19
resolution=0.10294556604732455, cluster number=16
Expanding search range: new range (0.0926510094425921, 0.16213926652453617)
resolution=0.1426510094425921, cluster number=19
resolution=0.0926510094425921, cluster number=14
Expanding search range: new range (0.08338590849833288, 0.14592533987208256)
resolution=0.13338590849833287, cluster number=20
resolution=0.08338590849833288, cluster number=13
Expanding search range: new range (0.0750473176484996, 0.1313328058848743)
resolution=0.1250473176484996, cluster number=19
resolution=0.0750473176484996, cluster number=12
Expanding search range: new range (0.06754258588364964, 0.11819952529638687)
resolution=0.11754258588364964, cluster number=19
resolution=0.06754258588364964, cluster number=12
Expanding search range: new range (0.06078832729528468, 0.1063795727667482)
resolution=0.06078832729528468, cluster number=12
Expanding search range: new range (0.05470949456575622, 0.09574161549007337)
resolution=0.05470949456575622, cluster number=10
Number of clusters: 10
12_GSE193181/P8

AnnData object with n_obs × n_vars = 21042 × 3021
    obs: 'group', 'cell_type', 'Garfield_cluster', 'Multigrate_cluster', 'TotalVI_cluster', 'scArches_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'TotalVI', 'TotalVI_cluster', 'scArches', 'scArches_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'TotalVI', 'scArches', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'TotalVI_distances', 'TotalVI_connectivities', 'scArches_distances', 'scArches_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [8]:
import matplotlib.pyplot as plt

dataset = '12_GSE193181/P8'
res_dir = f'/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_Protein/{dataset}'

latent_key_list = ['Garfield', 'Multigrate', 'TotalVI', 'scArches', 'Seurat']
for latent_key in latent_key_list:
    sc.tl.umap(adata, neighbors_key=latent_key)
    latent_key_cluster = latent_key + '_cluster'
    
    # Create a new figure for each plot with an appropriate size
    plt.figure(figsize=(12, 6))  # Adjust the figsize as needed
    sc.pl.umap(adata, color=['cell_type', latent_key_cluster], wspace=0.5, hspace=0.5, show=False, ncols=2)
    # Save the figure
    plt.savefig(res_dir + f"/{latent_key}_UMAP_clusters.png", bbox_inches='tight')  # Use bbox_inches to ensure full legend display
    plt.close()

In [9]:
method_list = ['Garfield', 'Multigrate', 'TotalVI', 'scArches', 'Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_Protein'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

        ARI       NMI     cLISI      cASW       model          dataset
0  0.358035  0.441918  0.921081  0.514515    Garfield  12_GSE193181/P8
1  0.417393  0.443053  0.900223  0.506198  Multigrate  12_GSE193181/P8
2  0.178194  0.306676  0.898623  0.503576     TotalVI  12_GSE193181/P8
3  0.195646  0.286759  0.892970  0.501884    scArches  12_GSE193181/P8
4  0.300844  0.455369  0.936783  0.499165      Seurat  12_GSE193181/P8

#### 探索一下用最佳分辨率

In [10]:
# calculate the metrics based on the best resolution
adata = count_metrics_for_best_resolution('12_GSE193181/P8')
adata

resolution: 0.1, nmi: 0.5237007962606849
resolution: 0.2, nmi: 0.4857880065501947
resolution: 0.3, nmi: 0.4509984164183313
resolution: 0.4, nmi: 0.44145549926749994
resolution: 0.5, nmi: 0.4284877635697771
resolution: 0.6, nmi: 0.423577007776728
resolution: 0.7, nmi: 0.4127243580789494
resolution: 0.8, nmi: 0.43412165869081953
resolution: 0.9, nmi: 0.40740888591898494
resolution: 1.0, nmi: 0.38894606831311657
resolution: 1.1, nmi: 0.4045944231435975
resolution: 1.2, nmi: 0.39175197911229726
resolution: 1.3, nmi: 0.39014021071841265
resolution: 1.4, nmi: 0.3914893076208446
resolution: 1.5, nmi: 0.3885419600088378
resolution: 1.6, nmi: 0.3878478948785048
resolution: 1.7, nmi: 0.38880104468062987
resolution: 1.8, nmi: 0.3861920080182795
resolution: 1.9, nmi: 0.38792471264539635
resolution: 2.0, nmi: 0.3838597477670859
optimised clustering against cell_type
optimal cluster resolution: 0.1
optimal score: 0.5237007962606849
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.5114466792229645
resolution: 0.2, nmi: 0.5047147478266937
resolution: 0.3, nmi: 0.47259560439398224
resolution: 0.4, nmi: 0.46719097295740136
resolution: 0.5, nmi: 0.45755442688365416
resolution: 0.6, nmi: 0.44975437183688005
resolution: 0.7, nmi: 0.44038641654383653
resolution: 0.8, nmi: 0.4169876662003441
resolution: 0.9, nmi: 0.3992559372011061
resolution: 1.0, nmi: 0.4227257726206362
resolution: 1.1, nmi: 0.40877867377049054
resolution: 1.2, nmi: 0.3939824480048327
resolution: 1.3, nmi: 0.384909499080561
resolution: 1.4, nmi: 0.37229807510454693
resolution: 1.5, nmi: 0.37036058605984234
resolution: 1.6, nmi: 0.3695091306640541
resolution: 1.7, nmi: 0.36217193805556913
resolution: 1.8, nmi: 0.3567080632230135
resolution: 1.9, nmi: 0.353017133512559
resolution: 2.0, nmi: 0.34857675442542974
optimised clustering against cell_type
optimal cluster resolution: 0.1
optimal score: 0.5114466792229645
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.26080860660684224
resolution: 0.2, nmi: 0.27447579198802047
resolution: 0.3, nmi: 0.32796078596316036
resolution: 0.4, nmi: 0.3376585055785789
resolution: 0.5, nmi: 0.34203669769635825
resolution: 0.6, nmi: 0.34431883619983145
resolution: 0.7, nmi: 0.343326071129525
resolution: 0.8, nmi: 0.34560258785655756
resolution: 0.9, nmi: 0.34577024135265605
resolution: 1.0, nmi: 0.3474251350326079
resolution: 1.1, nmi: 0.3477889966232637
resolution: 1.2, nmi: 0.3425262748635877
resolution: 1.3, nmi: 0.3373999763644418
resolution: 1.4, nmi: 0.3389512287011813
resolution: 1.5, nmi: 0.33938440820450555
resolution: 1.6, nmi: 0.3395271640118084
resolution: 1.7, nmi: 0.3372626946466421
resolution: 1.8, nmi: 0.3379668757532862
resolution: 1.9, nmi: 0.3370489442429701
resolution: 2.0, nmi: 0.33727746427114147
optimised clustering against cell_type
optimal cluster resolution: 1.1
optimal score: 0.3477889966232637
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.25849839048116113
resolution: 0.2, nmi: 0.2829575223906753
resolution: 0.3, nmi: 0.26741268712052213
resolution: 0.4, nmi: 0.26134752181284565
resolution: 0.5, nmi: 0.27023191626798526
resolution: 0.6, nmi: 0.29799877297909433
resolution: 0.7, nmi: 0.3093097638115818
resolution: 0.8, nmi: 0.2991580066922664
resolution: 0.9, nmi: 0.3045692161157706
resolution: 1.0, nmi: 0.30967902465861746
resolution: 1.1, nmi: 0.31586757944396393
resolution: 1.2, nmi: 0.3322870095574164
resolution: 1.3, nmi: 0.33428335347903004
resolution: 1.4, nmi: 0.3334896733374427
resolution: 1.5, nmi: 0.33862899115929096
resolution: 1.6, nmi: 0.336619833149632
resolution: 1.7, nmi: 0.3312643675408707
resolution: 1.8, nmi: 0.3323133162304555
resolution: 1.9, nmi: 0.326922138133514
resolution: 2.0, nmi: 0.32627653890571406
optimised clustering against cell_type
optimal cluster resolution: 1.5
optimal score: 0.33862899115929096
WARNING: cluster key cluster already exists in adata.obs and will be overwritten because force=True
resolution: 0.1, nmi: 0.4487210418647993
resolution: 0.2, nmi: 0.42183125861411785
resolution: 0.3, nmi: 0.41558325211623637
resolution: 0.4, nmi: 0.4020033520102
resolution: 0.5, nmi: 0.3992726490260312
resolution: 0.6, nmi: 0.39369448808688534
resolution: 0.7, nmi: 0.38396905955511873
resolution: 0.8, nmi: 0.3855035720889103
resolution: 0.9, nmi: 0.37921924320971423
resolution: 1.0, nmi: 0.3761285480419651
resolution: 1.1, nmi: 0.3738607327839951
resolution: 1.2, nmi: 0.37400879280772187
resolution: 1.3, nmi: 0.37492080736806405
resolution: 1.4, nmi: 0.37060505932051163
resolution: 1.5, nmi: 0.3713178703271981
resolution: 1.6, nmi: 0.3671460568141299
resolution: 1.7, nmi: 0.3651852702228957
resolution: 1.8, nmi: 0.36584503932546303
resolution: 1.9, nmi: 0.36451612506681397
resolution: 2.0, nmi: 0.36366317801060305
optimised clustering against cell_type
optimal cluster resolution: 0.1
optimal score: 0.4487210418647993
12_GSE193181/P8

AnnData object with n_obs × n_vars = 21042 × 3021
    obs: 'group', 'cell_type', 'batch', 'cluster'
    var: 'modality'
    uns: 'modality_lengths', 'neighbors', 'umap', 'cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'TotalVI', 'scArches', 'Seurat'
    layers: 'counts'
    obsp: 'distances', 'connectivities'

In [11]:
method_list = ['Garfield', 'Multigrate', 'TotalVI', 'scArches', 'Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_Protein'
dataset = '12_GSE193181/P8'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result_best_reso.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

        ARI       NMI     cLISI      cASW       model          dataset
0  0.419280  0.523701  0.921081  0.514515    Garfield  12_GSE193181/P8
1  0.411968  0.511447  0.900223  0.506198  Multigrate  12_GSE193181/P8
2  0.154174  0.347789  0.898623  0.503576     TotalVI  12_GSE193181/P8
3  0.143288  0.338629  0.892970  0.501884    scArches  12_GSE193181/P8
4  0.268088  0.448721  0.936783  0.499165      Seurat  12_GSE193181/P8

#### 利用最佳分辨率计算指标(Garfield);

In [12]:
## 记录resolution
reso_dict = {
    '12_GSE193181/P8': {
        'Garfield': 0.1, #0.38,
        'Multigrate': 0.6500000000000001,
        'TotalVI': 0.23914845000000007,
        'scArches': 0.2657205000000001,
        'Seurat': 0.05470949456575622, 
    }
}

# search the resolution for each method
adata = count_metrics_for_resolution('12_GSE193181/P8', reso_dict=reso_dict)
adata

the length of cell type: 10
method_reso is not None, using the 0.1 as resolution for Garfield...
Number of clusters: 4
the length of cell type: 10
method_reso is not None, using the 0.6500000000000001 as resolution for Multigrate...
Number of clusters: 10
the length of cell type: 10
method_reso is not None, using the 0.23914845000000007 as resolution for TotalVI...
Number of clusters: 10
the length of cell type: 10
method_reso is not None, using the 0.2657205000000001 as resolution for scArches...
Number of clusters: 10
the length of cell type: 10
method_reso is not None, using the 0.05470949456575622 as resolution for Seurat...
Number of clusters: 10
12_GSE193181/P8

AnnData object with n_obs × n_vars = 21042 × 3021
    obs: 'group', 'cell_type', 'Garfield_cluster', 'Multigrate_cluster', 'TotalVI_cluster', 'scArches_cluster', 'Seurat_cluster'
    var: 'modality'
    uns: 'modality_lengths', 'Garfield', 'Garfield_cluster', 'umap', 'Multigrate', 'Multigrate_cluster', 'TotalVI', 'TotalVI_cluster', 'scArches', 'scArches_cluster', 'Seurat', 'Seurat_cluster'
    obsm: 'Garfield', 'X_umap', 'Multigrate', 'TotalVI', 'scArches', 'Seurat'
    layers: 'counts'
    obsp: 'Garfield_distances', 'Garfield_connectivities', 'Multigrate_distances', 'Multigrate_connectivities', 'TotalVI_distances', 'TotalVI_connectivities', 'scArches_distances', 'scArches_connectivities', 'Seurat_distances', 'Seurat_connectivities'

In [13]:
method_list = ['Garfield', 'Multigrate', 'TotalVI', 'scArches', 'Seurat']
save_path = '/data2/zhouwg_data/project/Garfield_benchmark/results/Vertical/RNA_Protein'
dataset = '12_GSE193181/P8'

df = pd.read_csv(f'{save_path}/{dataset}_metrics_result.csv')
# df = df.drop('Dataset', axis=0)
df
# PlotTable(df, num_embeds = len(method_list), min_max_scale=False, save_dir = save_path)

        ARI       NMI     cLISI      cASW       model          dataset
0  0.419280  0.523701  0.921081  0.514515    Garfield  12_GSE193181/P8
1  0.417393  0.443053  0.900223  0.506198  Multigrate  12_GSE193181/P8
2  0.178194  0.306676  0.898623  0.503576     TotalVI  12_GSE193181/P8
3  0.195646  0.286759  0.892970  0.501884    scArches  12_GSE193181/P8
4  0.300844  0.455369  0.936783  0.499165      Seurat  12_GSE193181/P8